// AUTO-GENERATED by cap_nhat_dashboard.js - DO NOT EDIT MANUALLY
// Thời gian cập nhật: 14:04 01/04/2026
const TAWACO_DATA = {
  capNhat: "14:04 01/04/2026",
  alertCount: 0,

  // Tổng Công Ty
  slQuy:   0,
  dtQuy:   173891451889,
  tlSL:    "0.00",
  tlDT:    "50.87",

  // Hóa Đơn 0m3
  hdPct:   0.00,
  hd1Pct:  0.00,
  hd2Pct:  0.00,
  khHd:    6.23,
  khHd1:   6.68,
  khHd2:   5.86,

  // Tỷ Lệ Thu Tiền
  tlTT:    95.41,
  tlTT1:   95.09,
  tlTT2:   95.68,
  khTT:    80,

  // Chi tiết chi nhánh
  slPct1:  0.00,
  slPct2:  0.00,
  dt1Pct:  51.99,
  dt2Pct:  49.96,

  // Thay Đồng Hồ Nước (lấy từ SL object nếu có, mặc định null nếu API không trả)
  tctbSoLuong:  null,
  tctbKH:       null,
  dvtcSoLuong:  null,
  dvtcKH:       null,
  dhnLonThucHien: 0,
  dhnLonKH:       2,
};
