// Auto-generated by fetch_sai_gia_bieu.py
const TAWACO_SAIGIABIEU = {
  "lastUpdated": "2026-07-08 11:10:21",
  "ky_hien_tai": "07/2026",
  "tong_sinh_hoat": 46891,
  "tong_nghi_ngo": 101,
  "level_1_count": 9,
  "level_2_count": 69,
  "level_3_count": 23,
  "danh_sach": [
    {
      "DanhBa": "22043311376",
      "TenKH": "CONG TY TNHH TM VA DICH VU Y TE THANH XUAN",
      "GiaBieu": "11",
      "DinhMuc": 184.0,
      "Mean_6M": 176.33,
      "Std_6M": 94.87,
      "Alert_Level": 1
    },
    {
      "DanhBa": "22103391690",
      "TenKH": "CT TNHH MAY-IN-THEU M & J",
      "GiaBieu": "11",
      "DinhMuc": 0.0,
      "Mean_6M": 130.17,
      "Std_6M": 85.98,
      "Alert_Level": 1
    },
    {
      "DanhBa": "22103411584",
      "TenKH": "CTY TNHH TM-SX S.G.M",
      "GiaBieu": "11",
      "DinhMuc": 0.0,
      "Mean_6M": 109.83,
      "Std_6M": 55.14,
      "Alert_Level": 1
    },
    {
      "DanhBa": "22103410278",
      "TenKH": "CONG TY TNHH TM BRT VIET NAM",
      "GiaBieu": "11",
      "DinhMuc": 24.0,
      "Mean_6M": 32.33,
      "Std_6M": 20.75,
      "Alert_Level": 1
    },
    {
      "DanhBa": "15122861571",
      "TenKH": "CONG TY TNHH SAN XUAT THUONG MAI DICH VU VINH HIEN",
      "GiaBieu": "11",
      "DinhMuc": 16.0,
      "Mean_6M": 22.5,
      "Std_6M": 11.67,
      "Alert_Level": 1
    },
    {
      "DanhBa": "15072444147",
      "TenKH": "CT TNHH SX CK TM DV THANH SON",
      "GiaBieu": "11",
      "DinhMuc": 24.0,
      "Mean_6M": 14.67,
      "Std_6M": 8.59,
      "Alert_Level": 1
    },
    {
      "DanhBa": "22103412220",
      "TenKH": "CONG TY TNHH DET LUA TO TAM TOAN THINH",
      "GiaBieu": "11",
      "DinhMuc": 0.0,
      "Mean_6M": 5.5,
      "Std_6M": 3.39,
      "Alert_Level": 1
    },
    {
      "DanhBa": "22033278898",
      "TenKH": "CONG TY TNHH KD SX TM DT MINH ANH",
      "GiaBieu": "11",
      "DinhMuc": 20.0,
      "Mean_6M": 5.33,
      "Std_6M": 4.84,
      "Alert_Level": 1
    },
    {
      "DanhBa": "22103413827",
      "TenKH": "CONG TY TNHH VIET UC AUTO",
      "GiaBieu": "11",
      "DinhMuc": 0.0,
      "Mean_6M": 0.0,
      "Std_6M": 0.0,
      "Alert_Level": 1
    },
    {
      "DanhBa": "22103410501",
      "TenKH": "HOANG THI THUY TRANG",
      "GiaBieu": "11",
      "DinhMuc": 0.0,
      "Mean_6M": 438.67,
      "Std_6M": 1072.55,
      "Alert_Level": 2
    },
    {
      "DanhBa": "22073343285",
      "TenKH": "NGUYEN DUY LINH",
      "GiaBieu": "11",
      "DinhMuc": 0.0,
      "Mean_6M": 417.0,
      "Std_6M": 218.62,
      "Alert_Level": 2
    },
    {
      "DanhBa": "22103412290",
      "TenKH": "HA HOANG HAI",
      "GiaBieu": "11",
      "DinhMuc": 528.0,
      "Mean_6M": 364.83,
      "Std_6M": 187.74,
      "Alert_Level": 2
    },
    {
      "DanhBa": "15112823137",
      "TenKH": "TRAN DAI HAI",
      "GiaBieu": "11",
      "DinhMuc": 488.0,
      "Mean_6M": 342.67,
      "Std_6M": 178.31,
      "Alert_Level": 2
    },
    {
      "DanhBa": "15112829418",
      "TenKH": "LE ANH TUAN",
      "GiaBieu": "11",
      "DinhMuc": 0.0,
      "Mean_6M": 305.67,
      "Std_6M": 228.35,
      "Alert_Level": 2
    },
    {
      "DanhBa": "15062135394",
      "TenKH": "TRUONG THI NAM",
      "GiaBieu": "11",
      "DinhMuc": 664.0,
      "Mean_6M": 301.67,
      "Std_6M": 167.45,
      "Alert_Level": 2
    },
    {
      "DanhBa": "15062138848",
      "TenKH": "NGUYEN VAN HANH",
      "GiaBieu": "11",
      "DinhMuc": 292.0,
      "Mean_6M": 294.17,
      "Std_6M": 153.22,
      "Alert_Level": 2
    },
    {
      "DanhBa": "15062133585",
      "TenKH": "PHAM THI KIM PHUONG",
      "GiaBieu": "11",
      "DinhMuc": 380.0,
      "Mean_6M": 291.0,
      "Std_6M": 160.08,
      "Alert_Level": 2
    },
    {
      "DanhBa": "22103412770",
      "TenKH": "CHU DINH VIEN",
      "GiaBieu": "11",
      "DinhMuc": 344.0,
      "Mean_6M": 290.17,
      "Std_6M": 151.28,
      "Alert_Level": 2
    },
    {
      "DanhBa": "15062141062",
      "TenKH": "NGUYEN MINH TRI",
      "GiaBieu": "11",
      "DinhMuc": 116.0,
      "Mean_6M": 284.17,
      "Std_6M": 154.7,
      "Alert_Level": 2
    },
    {
      "DanhBa": "15062140947",
      "TenKH": "LE THI NGOC HONG",
      "GiaBieu": "11",
      "DinhMuc": 0.0,
      "Mean_6M": 246.67,
      "Std_6M": 161.96,
      "Alert_Level": 2
    },
    {
      "DanhBa": "15062130167",
      "TenKH": "DO MINH TIEN",
      "GiaBieu": "11",
      "DinhMuc": 0.0,
      "Mean_6M": 240.67,
      "Std_6M": 136.17,
      "Alert_Level": 2
    },
    {
      "DanhBa": "15062141187",
      "TenKH": "TRUONG THI NGOC LIEN",
      "GiaBieu": "11",
      "DinhMuc": 0.0,
      "Mean_6M": 235.83,
      "Std_6M": 133.53,
      "Alert_Level": 2
    },
    {
      "DanhBa": "22103396344",
      "TenKH": "NGUYEN THI NGOC HA",
      "GiaBieu": "11",
      "DinhMuc": 240.0,
      "Mean_6M": 230.0,
      "Std_6M": 121.07,
      "Alert_Level": 2
    },
    {
      "DanhBa": "15062130190",
      "TenKH": "TRUONG TRI TU HUYNH",
      "GiaBieu": "11",
      "DinhMuc": 132.0,
      "Mean_6M": 229.5,
      "Std_6M": 305.79,
      "Alert_Level": 2
    },
    {
      "DanhBa": "15062133596",
      "TenKH": "NGUYEN THU HANG",
      "GiaBieu": "11",
      "DinhMuc": 256.0,
      "Mean_6M": 228.0,
      "Std_6M": 116.65,
      "Alert_Level": 2
    },
    {
      "DanhBa": "15062141197",
      "TenKH": "TRAN THI XIN",
      "GiaBieu": "11",
      "DinhMuc": 476.0,
      "Mean_6M": 228.0,
      "Std_6M": 119.91,
      "Alert_Level": 2
    },
    {
      "DanhBa": "22073342777",
      "TenKH": "NGUYEN DUY DAI",
      "GiaBieu": "11",
      "DinhMuc": 304.0,
      "Mean_6M": 222.5,
      "Std_6M": 113.86,
      "Alert_Level": 2
    },
    {
      "DanhBa": "15112827004",
      "TenKH": "PHAN THI SUONG",
      "GiaBieu": "11",
      "DinhMuc": 0.0,
      "Mean_6M": 221.33,
      "Std_6M": 116.13,
      "Alert_Level": 2
    },
    {
      "DanhBa": "22103410512",
      "TenKH": "VU HOANG LONG",
      "GiaBieu": "11",
      "DinhMuc": 200.0,
      "Mean_6M": 214.0,
      "Std_6M": 107.8,
      "Alert_Level": 2
    },
    {
      "DanhBa": "22073238437",
      "TenKH": "NGUYEN QUOC CHIEN",
      "GiaBieu": "11",
      "DinhMuc": 112.0,
      "Mean_6M": 213.17,
      "Std_6M": 108.22,
      "Alert_Level": 2
    },
    {
      "DanhBa": "15062140367",
      "TenKH": "LE THI HUONG",
      "GiaBieu": "11",
      "DinhMuc": 288.0,
      "Mean_6M": 208.17,
      "Std_6M": 105.35,
      "Alert_Level": 2
    },
    {
      "DanhBa": "15112864181",
      "TenKH": "NGUYEN THI DOAN",
      "GiaBieu": "11",
      "DinhMuc": 288.0,
      "Mean_6M": 203.67,
      "Std_6M": 110.81,
      "Alert_Level": 2
    },
    {
      "DanhBa": "22103406200",
      "TenKH": "PHAN VAN THO",
      "GiaBieu": "11",
      "DinhMuc": 100.0,
      "Mean_6M": 202.67,
      "Std_6M": 102.77,
      "Alert_Level": 2
    },
    {
      "DanhBa": "15062132325",
      "TenKH": "NGUYEN THI HUONG",
      "GiaBieu": "11",
      "DinhMuc": 20.0,
      "Mean_6M": 202.33,
      "Std_6M": 99.87,
      "Alert_Level": 2
    },
    {
      "DanhBa": "15062141195",
      "TenKH": "TRINH THAI QUYNH LAM",
      "GiaBieu": "11",
      "DinhMuc": 128.0,
      "Mean_6M": 200.33,
      "Std_6M": 98.66,
      "Alert_Level": 2
    },
    {
      "DanhBa": "15112829086",
      "TenKH": "HUYNH VAN TAN",
      "GiaBieu": "11",
      "DinhMuc": 228.0,
      "Mean_6M": 199.67,
      "Std_6M": 111.02,
      "Alert_Level": 2
    },
    {
      "DanhBa": "15062141137",
      "TenKH": "NGUYEN THI TRUONG",
      "GiaBieu": "11",
      "DinhMuc": 68.0,
      "Mean_6M": 197.17,
      "Std_6M": 99.67,
      "Alert_Level": 2
    },
    {
      "DanhBa": "15062132424",
      "TenKH": "TRAN HUU TUAN",
      "GiaBieu": "11",
      "DinhMuc": 4.0,
      "Mean_6M": 196.0,
      "Std_6M": 100.97,
      "Alert_Level": 2
    },
    {
      "DanhBa": "15062132406",
      "TenKH": "NGUYEN THI BINH",
      "GiaBieu": "11",
      "DinhMuc": 240.0,
      "Mean_6M": 194.0,
      "Std_6M": 105.44,
      "Alert_Level": 2
    },
    {
      "DanhBa": "15062140644",
      "TenKH": "PHAN THI KIM CHUNG",
      "GiaBieu": "11",
      "DinhMuc": 152.0,
      "Mean_6M": 193.5,
      "Std_6M": 97.33,
      "Alert_Level": 2
    },
    {
      "DanhBa": "15062132258",
      "TenKH": "LE THI MIEN(DD 2 HO)",
      "GiaBieu": "11",
      "DinhMuc": 48.0,
      "Mean_6M": 192.33,
      "Std_6M": 105.24,
      "Alert_Level": 2
    },
    {
      "DanhBa": "22103394033",
      "TenKH": "NGUYEN VAN QUANG",
      "GiaBieu": "11",
      "DinhMuc": 0.0,
      "Mean_6M": 191.0,
      "Std_6M": 96.09,
      "Alert_Level": 2
    },
    {
      "DanhBa": "15062140136",
      "TenKH": "DUONG THI MY LINH",
      "GiaBieu": "11",
      "DinhMuc": 292.0,
      "Mean_6M": 186.33,
      "Std_6M": 92.75,
      "Alert_Level": 2
    },
    {
      "DanhBa": "22033276934",
      "TenKH": "TRAN VAN BINH",
      "GiaBieu": "11",
      "DinhMuc": 220.0,
      "Mean_6M": 186.0,
      "Std_6M": 96.99,
      "Alert_Level": 2
    },
    {
      "DanhBa": "22103410823",
      "TenKH": "NGUYEN PHUC LOC",
      "GiaBieu": "11",
      "DinhMuc": 196.0,
      "Mean_6M": 184.67,
      "Std_6M": 93.69,
      "Alert_Level": 2
    },
    {
      "DanhBa": "15062135393",
      "TenKH": "LA THI THU THAO",
      "GiaBieu": "11",
      "DinhMuc": 224.0,
      "Mean_6M": 180.5,
      "Std_6M": 100.78,
      "Alert_Level": 2
    },
    {
      "DanhBa": "15112869092",
      "TenKH": "DO THANH BINH",
      "GiaBieu": "11",
      "DinhMuc": 0.0,
      "Mean_6M": 180.33,
      "Std_6M": 95.33,
      "Alert_Level": 2
    },
    {
      "DanhBa": "22073230085",
      "TenKH": "PHAN THI NGOC",
      "GiaBieu": "11",
      "DinhMuc": 252.0,
      "Mean_6M": 179.67,
      "Std_6M": 98.33,
      "Alert_Level": 2
    },
    {
      "DanhBa": "15062133408",
      "TenKH": "LY DIEU NGA",
      "GiaBieu": "11",
      "DinhMuc": 0.0,
      "Mean_6M": 179.5,
      "Std_6M": 100.51,
      "Alert_Level": 2
    },
    {
      "DanhBa": "22103410149",
      "TenKH": "VUONG TRI DUNG",
      "GiaBieu": "11",
      "DinhMuc": 24.0,
      "Mean_6M": 178.67,
      "Std_6M": 90.28,
      "Alert_Level": 2
    },
    {
      "DanhBa": "15072468269",
      "TenKH": "LÝ LÊ MỸ HOÀNG ",
      "GiaBieu": "11",
      "DinhMuc": 0.0,
      "Mean_6M": 178.5,
      "Std_6M": 204.93,
      "Alert_Level": 2
    },
    {
      "DanhBa": "22043290194",
      "TenKH": "NGUYEN VAN RO",
      "GiaBieu": "11",
      "DinhMuc": 64.0,
      "Mean_6M": 177.17,
      "Std_6M": 278.25,
      "Alert_Level": 2
    },
    {
      "DanhBa": "15062140848",
      "TenKH": "NGUYEN THI THUY HANG",
      "GiaBieu": "11",
      "DinhMuc": 0.0,
      "Mean_6M": 176.0,
      "Std_6M": 94.93,
      "Alert_Level": 2
    },
    {
      "DanhBa": "15062133579",
      "TenKH": "NGUYEN THI PHONG",
      "GiaBieu": "11",
      "DinhMuc": 64.0,
      "Mean_6M": 175.0,
      "Std_6M": 104.85,
      "Alert_Level": 2
    },
    {
      "DanhBa": "22043310946",
      "TenKH": "VU THI BICH",
      "GiaBieu": "11",
      "DinhMuc": 232.0,
      "Mean_6M": 175.0,
      "Std_6M": 87.95,
      "Alert_Level": 2
    },
    {
      "DanhBa": "22043310271",
      "TenKH": "TU THI THU NGUYET",
      "GiaBieu": "11",
      "DinhMuc": 0.0,
      "Mean_6M": 174.67,
      "Std_6M": 99.0,
      "Alert_Level": 2
    },
    {
      "DanhBa": "22103410984",
      "TenKH": "NGUYEN THI VY",
      "GiaBieu": "11",
      "DinhMuc": 0.0,
      "Mean_6M": 171.17,
      "Std_6M": 86.14,
      "Alert_Level": 2
    },
    {
      "DanhBa": "22103413306",
      "TenKH": "NGUYEN THANH SON",
      "GiaBieu": "11",
      "DinhMuc": 0.0,
      "Mean_6M": 167.0,
      "Std_6M": 94.17,
      "Alert_Level": 2
    },
    {
      "DanhBa": "22103413168",
      "TenKH": "NGUYEN THANH SON",
      "GiaBieu": "11",
      "DinhMuc": 0.0,
      "Mean_6M": 166.83,
      "Std_6M": 86.67,
      "Alert_Level": 2
    },
    {
      "DanhBa": "15112841327",
      "TenKH": "NGUYEN VAN LUONG",
      "GiaBieu": "11",
      "DinhMuc": 0.0,
      "Mean_6M": 163.0,
      "Std_6M": 90.37,
      "Alert_Level": 2
    },
    {
      "DanhBa": "15062133850",
      "TenKH": "THAN TRONG NINH",
      "GiaBieu": "11",
      "DinhMuc": 0.0,
      "Mean_6M": 161.67,
      "Std_6M": 82.65,
      "Alert_Level": 2
    },
    {
      "DanhBa": "15062140980",
      "TenKH": "NGUYEN THI LIEU",
      "GiaBieu": "11",
      "DinhMuc": 208.0,
      "Mean_6M": 160.83,
      "Std_6M": 81.6,
      "Alert_Level": 2
    },
    {
      "DanhBa": "22043311165",
      "TenKH": "VO THI LAN HUONG",
      "GiaBieu": "11",
      "DinhMuc": 108.0,
      "Mean_6M": 158.17,
      "Std_6M": 114.42,
      "Alert_Level": 2
    },
    {
      "DanhBa": "22043310495",
      "TenKH": "NGUYEN THI HOANG YEN",
      "GiaBieu": "11",
      "DinhMuc": 220.0,
      "Mean_6M": 158.0,
      "Std_6M": 82.09,
      "Alert_Level": 2
    },
    {
      "DanhBa": "22043271135",
      "TenKH": "NGUYEN THANH BINH",
      "GiaBieu": "11",
      "DinhMuc": 0.0,
      "Mean_6M": 157.67,
      "Std_6M": 82.37,
      "Alert_Level": 2
    },
    {
      "DanhBa": "15112822451",
      "TenKH": "TRINH THI DOAN TRANG",
      "GiaBieu": "11",
      "DinhMuc": 16.0,
      "Mean_6M": 153.33,
      "Std_6M": 85.83,
      "Alert_Level": 2
    },
    {
      "DanhBa": "22043312179",
      "TenKH": "NGUYEN THANH TUOC",
      "GiaBieu": "11",
      "DinhMuc": 56.0,
      "Mean_6M": 152.83,
      "Std_6M": 78.56,
      "Alert_Level": 2
    },
    {
      "DanhBa": "15062134467",
      "TenKH": "PHAN MAU NINH",
      "GiaBieu": "11",
      "DinhMuc": 168.0,
      "Mean_6M": 150.17,
      "Std_6M": 81.06,
      "Alert_Level": 2
    },
    {
      "DanhBa": "22073230425",
      "TenKH": "LAI VAN NGA",
      "GiaBieu": "11",
      "DinhMuc": 0.0,
      "Mean_6M": 148.5,
      "Std_6M": 133.36,
      "Alert_Level": 2
    },
    {
      "DanhBa": "15062137351",
      "TenKH": "NGUYEN QUYET THANG",
      "GiaBieu": "11",
      "DinhMuc": 4.0,
      "Mean_6M": 132.33,
      "Std_6M": 317.8,
      "Alert_Level": 2
    },
    {
      "DanhBa": "22033270955",
      "TenKH": "TRAN NHAT KY",
      "GiaBieu": "11",
      "DinhMuc": 16.0,
      "Mean_6M": 131.67,
      "Std_6M": 116.48,
      "Alert_Level": 2
    },
    {
      "DanhBa": "22103411063",
      "TenKH": "VUONG TRI DUNG",
      "GiaBieu": "11",
      "DinhMuc": 92.0,
      "Mean_6M": 127.83,
      "Std_6M": 130.14,
      "Alert_Level": 2
    },
    {
      "DanhBa": "22033275303",
      "TenKH": "TRAN VAN LAM",
      "GiaBieu": "11",
      "DinhMuc": 16.0,
      "Mean_6M": 122.33,
      "Std_6M": 273.75,
      "Alert_Level": 2
    },
    {
      "DanhBa": "22043310289",
      "TenKH": "DO MAU BINH MINH",
      "GiaBieu": "11",
      "DinhMuc": 0.0,
      "Mean_6M": 114.83,
      "Std_6M": 237.02,
      "Alert_Level": 2
    },
    {
      "DanhBa": "22033275180",
      "TenKH": "NGUYEN VAN HA",
      "GiaBieu": "11",
      "DinhMuc": 16.0,
      "Mean_6M": 107.67,
      "Std_6M": 231.5,
      "Alert_Level": 2
    },
    {
      "DanhBa": "22073241246",
      "TenKH": "PHAM VAN DINH",
      "GiaBieu": "11",
      "DinhMuc": 16.0,
      "Mean_6M": 94.33,
      "Std_6M": 163.48,
      "Alert_Level": 2
    },
    {
      "DanhBa": "22033272422",
      "TenKH": "NGUYEN VAN MAN",
      "GiaBieu": "11",
      "DinhMuc": 16.0,
      "Mean_6M": 93.33,
      "Std_6M": 192.3,
      "Alert_Level": 2
    },
    {
      "DanhBa": "15062140091",
      "TenKH": "PHAM THI KIM THOA",
      "GiaBieu": "11",
      "DinhMuc": 188.0,
      "Mean_6M": 91.0,
      "Std_6M": 214.58,
      "Alert_Level": 2
    },
    {
      "DanhBa": "15062138209",
      "TenKH": "NGUYEN THANH DUY",
      "GiaBieu": "11",
      "DinhMuc": 4.0,
      "Mean_6M": 146.17,
      "Std_6M": 79.28,
      "Alert_Level": 3
    },
    {
      "DanhBa": "22103408736",
      "TenKH": "NGUYEN VAN HUONG",
      "GiaBieu": "11",
      "DinhMuc": 4.0,
      "Mean_6M": 111.33,
      "Std_6M": 56.66,
      "Alert_Level": 3
    },
    {
      "DanhBa": "22043304402",
      "TenKH": "NGUYEN THI BAY",
      "GiaBieu": "11",
      "DinhMuc": 4.0,
      "Mean_6M": 107.17,
      "Std_6M": 55.28,
      "Alert_Level": 3
    },
    {
      "DanhBa": "15072428792",
      "TenKH": "LU QUOC TRUNG",
      "GiaBieu": "11",
      "DinhMuc": 4.0,
      "Mean_6M": 105.33,
      "Std_6M": 57.22,
      "Alert_Level": 3
    },
    {
      "DanhBa": "15062140993",
      "TenKH": "NGUYEN TRAN KHUONG",
      "GiaBieu": "11",
      "DinhMuc": 4.0,
      "Mean_6M": 93.33,
      "Std_6M": 51.52,
      "Alert_Level": 3
    },
    {
      "DanhBa": "15062138301",
      "TenKH": "NGUYEN VAN PHONG",
      "GiaBieu": "11",
      "DinhMuc": 4.0,
      "Mean_6M": 85.83,
      "Std_6M": 89.09,
      "Alert_Level": 3
    },
    {
      "DanhBa": "22033278412",
      "TenKH": "TRUONG THI LUYEN",
      "GiaBieu": "11",
      "DinhMuc": 4.0,
      "Mean_6M": 78.33,
      "Std_6M": 39.93,
      "Alert_Level": 3
    },
    {
      "DanhBa": "22043313218",
      "TenKH": "NGUYEN THANH THANH",
      "GiaBieu": "11",
      "DinhMuc": 4.0,
      "Mean_6M": 70.83,
      "Std_6M": 61.9,
      "Alert_Level": 3
    },
    {
      "DanhBa": "15173422170",
      "TenKH": "NG QUANG NGOC (DD 5 HO)",
      "GiaBieu": "11",
      "DinhMuc": 4.0,
      "Mean_6M": 67.33,
      "Std_6M": 37.61,
      "Alert_Level": 3
    },
    {
      "DanhBa": "15112828508",
      "TenKH": NaN,
      "GiaBieu": "11",
      "DinhMuc": 4.0,
      "Mean_6M": 65.83,
      "Std_6M": 34.24,
      "Alert_Level": 3
    },
    {
      "DanhBa": "22103391241",
      "TenKH": "BUI QUANG TRU",
      "GiaBieu": "11",
      "DinhMuc": 4.0,
      "Mean_6M": 59.67,
      "Std_6M": 30.64,
      "Alert_Level": 3
    },
    {
      "DanhBa": "15122886561",
      "TenKH": "PHUNG QUOC DUNG",
      "GiaBieu": "11",
      "DinhMuc": 4.0,
      "Mean_6M": 57.67,
      "Std_6M": 28.47,
      "Alert_Level": 3
    },
    {
      "DanhBa": "22103390801",
      "TenKH": "VAN NU PHAN THANH THAO",
      "GiaBieu": "11",
      "DinhMuc": 4.0,
      "Mean_6M": 56.67,
      "Std_6M": 32.12,
      "Alert_Level": 3
    },
    {
      "DanhBa": "22033273104",
      "TenKH": "TRAN TRONG DAI",
      "GiaBieu": "11",
      "DinhMuc": 4.0,
      "Mean_6M": 56.0,
      "Std_6M": 28.21,
      "Alert_Level": 3
    },
    {
      "DanhBa": "22043313345",
      "TenKH": "LUU THANH BINH",
      "GiaBieu": "11",
      "DinhMuc": 4.0,
      "Mean_6M": 53.67,
      "Std_6M": 27.83,
      "Alert_Level": 3
    },
    {
      "DanhBa": "15112820383",
      "TenKH": "LE THI TUYET",
      "GiaBieu": "11",
      "DinhMuc": 4.0,
      "Mean_6M": 53.5,
      "Std_6M": 123.84,
      "Alert_Level": 3
    },
    {
      "DanhBa": "22103413844",
      "TenKH": "DINH QUANG TRI",
      "GiaBieu": "11",
      "DinhMuc": 4.0,
      "Mean_6M": 53.5,
      "Std_6M": 27.65,
      "Alert_Level": 3
    },
    {
      "DanhBa": "22073239399",
      "TenKH": "LU NGOC LUAN",
      "GiaBieu": "11",
      "DinhMuc": 4.0,
      "Mean_6M": 53.33,
      "Std_6M": 56.46,
      "Alert_Level": 3
    },
    {
      "DanhBa": "22103413845",
      "TenKH": "HO THI HIEP",
      "GiaBieu": "11",
      "DinhMuc": 4.0,
      "Mean_6M": 52.67,
      "Std_6M": 28.81,
      "Alert_Level": 3
    },
    {
      "DanhBa": "15112822397",
      "TenKH": "CAO THI MINH TAM",
      "GiaBieu": "11",
      "DinhMuc": 4.0,
      "Mean_6M": 52.33,
      "Std_6M": 26.74,
      "Alert_Level": 3
    },
    {
      "DanhBa": "22033257862",
      "TenKH": "HUYNH XUAN HIEP",
      "GiaBieu": "11",
      "DinhMuc": 4.0,
      "Mean_6M": 52.0,
      "Std_6M": 29.22,
      "Alert_Level": 3
    },
    {
      "DanhBa": "22103401192",
      "TenKH": "TRAN THI UT",
      "GiaBieu": "11",
      "DinhMuc": 4.0,
      "Mean_6M": 51.17,
      "Std_6M": 25.64,
      "Alert_Level": 3
    },
    {
      "DanhBa": "15062141156",
      "TenKH": "NGUYEN QUANG THAO",
      "GiaBieu": "11",
      "DinhMuc": 4.0,
      "Mean_6M": 50.67,
      "Std_6M": 25.48,
      "Alert_Level": 3
    }
  ]
};