// Auto-generated by fetch_sai_gia_bieu.py
const TAWACO_SAIGIABIEU = {
  "lastUpdated": "2026-08-21 16:01:20",
  "ky_hien_tai": "08/2026",
  "tong_sinh_hoat": 209822,
  "tong_nghi_ngo": 342,
  "level_1_count": 46,
  "level_2_count": 225,
  "level_3_count": 71,
  "danh_sach": [
    {
      "DanhBa": "22103391690",
      "TenKH": "CT TNHH MAY-IN-THEU M & J",
      "GiaBieu": "11",
      "DinhMuc": 0.0,
      "Mean_6M": 118.17,
      "Std_6M": 106.04,
      "Alert_Level": 1
    },
    {
      "DanhBa": "22103411584",
      "TenKH": "CTY TNHH TM-SX S.G.M",
      "GiaBieu": "11",
      "DinhMuc": 0.0,
      "Mean_6M": 91.5,
      "Std_6M": 71.58,
      "Alert_Level": 1
    },
    {
      "DanhBa": "22093380795",
      "TenKH": "CONG TY TNHH TM DV VA XD TAN QUANG",
      "GiaBieu": "11",
      "DinhMuc": 24.0,
      "Mean_6M": 44.83,
      "Std_6M": 35.24,
      "Alert_Level": 1
    },
    {
      "DanhBa": "15052170273",
      "TenKH": "CONG TY TNHH THUONG MAI HMSP QUOC TE ( VIET NAM )",
      "GiaBieu": "11",
      "DinhMuc": 0.0,
      "Mean_6M": 39.5,
      "Std_6M": 31.63,
      "Alert_Level": 1
    },
    {
      "DanhBa": "15082528445",
      "TenKH": "CONG TY TNHH TU GIAT SAY CHANTE",
      "GiaBieu": "11",
      "DinhMuc": 16.0,
      "Mean_6M": 33.0,
      "Std_6M": 25.72,
      "Alert_Level": 1
    },
    {
      "DanhBa": "22103410278",
      "TenKH": "CONG TY TNHH TM BRT VIET NAM",
      "GiaBieu": "11",
      "DinhMuc": 24.0,
      "Mean_6M": 31.67,
      "Std_6M": 27.69,
      "Alert_Level": 1
    },
    {
      "DanhBa": "15011501327",
      "TenKH": "CT TNHH XDTM DVTV-AN CU",
      "GiaBieu": "11",
      "DinhMuc": 24.0,
      "Mean_6M": 23.0,
      "Std_6M": 17.87,
      "Alert_Level": 1
    },
    {
      "DanhBa": "15102722113",
      "TenKH": "CTY XD GO VAP",
      "GiaBieu": "11",
      "DinhMuc": 0.0,
      "Mean_6M": 22.5,
      "Std_6M": 17.55,
      "Alert_Level": 1
    },
    {
      "DanhBa": "15042020394",
      "TenKH": "CTY TNHH TM VAN PHUC LOC",
      "GiaBieu": "11",
      "DinhMuc": 0.0,
      "Mean_6M": 21.83,
      "Std_6M": 19.95,
      "Alert_Level": 1
    },
    {
      "DanhBa": "22083364003",
      "TenKH": "CONG TY TNHH THUONG MAI DICH VU XAY DUNG VAN TAI MANH THANH TIEN",
      "GiaBieu": "11",
      "DinhMuc": 0.0,
      "Mean_6M": 21.0,
      "Std_6M": 16.43,
      "Alert_Level": 1
    },
    {
      "DanhBa": "22073330109",
      "TenKH": "CTY TNHH HOA CHAT AN PHA",
      "GiaBieu": "11",
      "DinhMuc": 24.0,
      "Mean_6M": 20.67,
      "Std_6M": 16.32,
      "Alert_Level": 1
    },
    {
      "DanhBa": "15122861571",
      "TenKH": "CONG TY TNHH SAN XUAT THUONG MAI DICH VU VINH HIEN",
      "GiaBieu": "11",
      "DinhMuc": 16.0,
      "Mean_6M": 18.67,
      "Std_6M": 14.83,
      "Alert_Level": 1
    },
    {
      "DanhBa": "15011500204",
      "TenKH": "CTY TNHH GP CNTT LE HUAN",
      "GiaBieu": "11",
      "DinhMuc": 16.0,
      "Mean_6M": 18.67,
      "Std_6M": 14.47,
      "Alert_Level": 1
    },
    {
      "DanhBa": "15102721752",
      "TenKH": "CTY XD QUAN GV",
      "GiaBieu": "11",
      "DinhMuc": 0.0,
      "Mean_6M": 18.17,
      "Std_6M": 14.18,
      "Alert_Level": 1
    },
    {
      "DanhBa": "22053328650",
      "TenKH": "CONG TY TNHH AN NHIEN CASA",
      "GiaBieu": "11",
      "DinhMuc": 0.0,
      "Mean_6M": 16.33,
      "Std_6M": 36.11,
      "Alert_Level": 1
    },
    {
      "DanhBa": "22023241235",
      "TenKH": "CONG TY TNHH SAN XUAT VA THUONG MAI NGUYEN DUONG",
      "GiaBieu": "11",
      "DinhMuc": 0.0,
      "Mean_6M": 15.5,
      "Std_6M": 12.66,
      "Alert_Level": 1
    },
    {
      "DanhBa": "15052160906",
      "TenKH": "CTY CP DIA OC VUON XANH",
      "GiaBieu": "11",
      "DinhMuc": 16.0,
      "Mean_6M": 13.17,
      "Std_6M": 10.42,
      "Alert_Level": 1
    },
    {
      "DanhBa": "15031708601",
      "TenKH": "CONG TY TNHH XUAT NHAP KHAU SAN XUAT THUONG MAI TRAN PHAT",
      "GiaBieu": "11",
      "DinhMuc": 20.0,
      "Mean_6M": 13.0,
      "Std_6M": 10.1,
      "Alert_Level": 1
    },
    {
      "DanhBa": "15072444147",
      "TenKH": "CT TNHH SX CK TM DV THANH SON",
      "GiaBieu": "11",
      "DinhMuc": 24.0,
      "Mean_6M": 12.33,
      "Std_6M": 9.97,
      "Alert_Level": 1
    },
    {
      "DanhBa": "22063323598",
      "TenKH": "CONG TY TNHH DICH VU AN PHU DONG",
      "GiaBieu": "11",
      "DinhMuc": 16.0,
      "Mean_6M": 12.17,
      "Std_6M": 20.76,
      "Alert_Level": 1
    },
    {
      "DanhBa": "22023251052",
      "TenKH": "CONG TY TNHH CO KHI XAY DUNG HOANG GIA VIET",
      "GiaBieu": "11",
      "DinhMuc": 16.0,
      "Mean_6M": 11.83,
      "Std_6M": 9.26,
      "Alert_Level": 1
    },
    {
      "DanhBa": "22083366066",
      "TenKH": "CONG TY TNHH MTV VIET NAM THANG",
      "GiaBieu": "11",
      "DinhMuc": 12.0,
      "Mean_6M": 11.0,
      "Std_6M": 8.72,
      "Alert_Level": 1
    },
    {
      "DanhBa": "15102721689",
      "TenKH": "CTY XD Q.GO VAP",
      "GiaBieu": "11",
      "DinhMuc": 0.0,
      "Mean_6M": 10.67,
      "Std_6M": 9.16,
      "Alert_Level": 1
    },
    {
      "DanhBa": "22023230842",
      "TenKH": "CONG TY TNHH SX TM DV KHA TU",
      "GiaBieu": "11",
      "DinhMuc": 12.0,
      "Mean_6M": 10.17,
      "Std_6M": 7.91,
      "Alert_Level": 1
    },
    {
      "DanhBa": "15141933995",
      "TenKH": "CTY TNHH KD BDS VIET THANH",
      "GiaBieu": "11",
      "DinhMuc": 24.0,
      "Mean_6M": 10.0,
      "Std_6M": 8.6,
      "Alert_Level": 1
    },
    {
      "DanhBa": "15173420880",
      "TenKH": "CTY TNHH SXTMDV HOA SINH TAN",
      "GiaBieu": "11",
      "DinhMuc": 16.0,
      "Mean_6M": 8.5,
      "Std_6M": 6.63,
      "Alert_Level": 1
    },
    {
      "DanhBa": "22073241613",
      "TenKH": "CONG TY TNHH SAN XUAT THUONG MAI NGUYEN LIEU CONG NGHIEP MIEN NAM",
      "GiaBieu": "11",
      "DinhMuc": 16.0,
      "Mean_6M": 8.17,
      "Std_6M": 9.15,
      "Alert_Level": 1
    },
    {
      "DanhBa": "15102721686",
      "TenKH": "CTY XD Q.GO VAP",
      "GiaBieu": "11",
      "DinhMuc": 16.0,
      "Mean_6M": 8.17,
      "Std_6M": 6.55,
      "Alert_Level": 1
    },
    {
      "DanhBa": "15102721742",
      "TenKH": "CTY XD Q.GO VAP",
      "GiaBieu": "11",
      "DinhMuc": 8.0,
      "Mean_6M": 8.17,
      "Std_6M": 6.71,
      "Alert_Level": 1
    },
    {
      "DanhBa": "15072448387",
      "TenKH": "CONG TY TNHH MTV THUONG MAI VA DICH VU PHAT TRIEN A CHAU",
      "GiaBieu": "11",
      "DinhMuc": 0.0,
      "Mean_6M": 7.0,
      "Std_6M": 5.62,
      "Alert_Level": 1
    },
    {
      "DanhBa": "15041908179",
      "TenKH": "CONG TY TNHH KIREI NETWORK",
      "GiaBieu": "11",
      "DinhMuc": 0.0,
      "Mean_6M": 6.33,
      "Std_6M": 6.15,
      "Alert_Level": 1
    },
    {
      "DanhBa": "22043270250",
      "TenKH": "CTY TNHH TM AU A",
      "GiaBieu": "11",
      "DinhMuc": 0.0,
      "Mean_6M": 5.83,
      "Std_6M": 6.08,
      "Alert_Level": 1
    },
    {
      "DanhBa": "22073241614",
      "TenKH": "CONG TY TNHH SAN XUAT THUONG MAI NGUYEN LIEU CONG NGHIEP MIEN NAM",
      "GiaBieu": "11",
      "DinhMuc": 24.0,
      "Mean_6M": 5.0,
      "Std_6M": 8.07,
      "Alert_Level": 1
    },
    {
      "DanhBa": "22103412220",
      "TenKH": "CONG TY TNHH DET LUA TO TAM TOAN THINH",
      "GiaBieu": "11",
      "DinhMuc": 0.0,
      "Mean_6M": 4.83,
      "Std_6M": 3.82,
      "Alert_Level": 1
    },
    {
      "DanhBa": "15011500327",
      "TenKH": "CTY XD GO VAP",
      "GiaBieu": "11",
      "DinhMuc": 0.0,
      "Mean_6M": 4.33,
      "Std_6M": 3.83,
      "Alert_Level": 1
    },
    {
      "DanhBa": "22033278898",
      "TenKH": "CONG TY TNHH KD SX TM DT MINH ANH",
      "GiaBieu": "11",
      "DinhMuc": 20.0,
      "Mean_6M": 4.33,
      "Std_6M": 4.8,
      "Alert_Level": 1
    },
    {
      "DanhBa": "22043302627",
      "TenKH": "CONG TY TNHH PHUC QUAN",
      "GiaBieu": "11",
      "DinhMuc": 0.0,
      "Mean_6M": 3.5,
      "Std_6M": 2.81,
      "Alert_Level": 1
    },
    {
      "DanhBa": "15102721927",
      "TenKH": "CTY XD GO VAP",
      "GiaBieu": "11",
      "DinhMuc": 0.0,
      "Mean_6M": 3.5,
      "Std_6M": 2.88,
      "Alert_Level": 1
    },
    {
      "DanhBa": "22083361308",
      "TenKH": "THAN TRUONG HOC",
      "GiaBieu": "11",
      "DinhMuc": 0.0,
      "Mean_6M": 1.5,
      "Std_6M": 1.64,
      "Alert_Level": 1
    },
    {
      "DanhBa": "22083360689",
      "TenKH": "THAN TRUONG HOC",
      "GiaBieu": "11",
      "DinhMuc": 16.0,
      "Mean_6M": 0.83,
      "Std_6M": 1.33,
      "Alert_Level": 1
    },
    {
      "DanhBa": "15102721674",
      "TenKH": "CTY XD QUAN GV",
      "GiaBieu": "11",
      "DinhMuc": 0.0,
      "Mean_6M": 0.67,
      "Std_6M": 0.52,
      "Alert_Level": 1
    },
    {
      "DanhBa": "15102721675",
      "TenKH": "CTY XD QUAN GV",
      "GiaBieu": "11",
      "DinhMuc": 0.0,
      "Mean_6M": 0.33,
      "Std_6M": 0.82,
      "Alert_Level": 1
    },
    {
      "DanhBa": "22083369622",
      "TenKH": "THAN TRUONG HOC",
      "GiaBieu": "11",
      "DinhMuc": 0.0,
      "Mean_6M": 0.0,
      "Std_6M": 0.0,
      "Alert_Level": 1
    },
    {
      "DanhBa": "22083364989",
      "TenKH": "CN CONG TY TNHH TM VA DV DAI GIA",
      "GiaBieu": "11",
      "DinhMuc": 0.0,
      "Mean_6M": 0.0,
      "Std_6M": 0.0,
      "Alert_Level": 1
    },
    {
      "DanhBa": "22103413827",
      "TenKH": "CONG TY TNHH VIET UC AUTO",
      "GiaBieu": "11",
      "DinhMuc": 0.0,
      "Mean_6M": 0.0,
      "Std_6M": 0.0,
      "Alert_Level": 1
    },
    {
      "DanhBa": "15173422511",
      "TenKH": "CTY THANH BINH",
      "GiaBieu": "11",
      "DinhMuc": 0.0,
      "Mean_6M": 0.0,
      "Std_6M": 0.0,
      "Alert_Level": 1
    },
    {
      "DanhBa": "15151900219",
      "TenKH": "NGUYEN DUC HANH",
      "GiaBieu": "11",
      "DinhMuc": 228.0,
      "Mean_6M": 598.83,
      "Std_6M": 465.04,
      "Alert_Level": 2
    },
    {
      "DanhBa": "22043277669",
      "TenKH": "NGUYEN DUY LINH",
      "GiaBieu": "11",
      "DinhMuc": 0.0,
      "Mean_6M": 571.17,
      "Std_6M": 447.82,
      "Alert_Level": 2
    },
    {
      "DanhBa": "15052171175",
      "TenKH": "NGUYEN THI BICH PHUONG",
      "GiaBieu": "11",
      "DinhMuc": 432.0,
      "Mean_6M": 539.33,
      "Std_6M": 430.49,
      "Alert_Level": 2
    },
    {
      "DanhBa": "15041988247",
      "TenKH": "TRUNG TAM NUOI DUONG BAO TRO TRE EM GO VAP",
      "GiaBieu": "21",
      "DinhMuc": 184.0,
      "Mean_6M": 503.33,
      "Std_6M": 398.05,
      "Alert_Level": 2
    },
    {
      "DanhBa": "15052128243",
      "TenKH": "TRAN TRONG TOAN",
      "GiaBieu": "11",
      "DinhMuc": 848.0,
      "Mean_6M": 452.17,
      "Std_6M": 395.52,
      "Alert_Level": 2
    },
    {
      "DanhBa": "22053327386",
      "TenKH": "HUYNH TU",
      "GiaBieu": "11",
      "DinhMuc": 680.0,
      "Mean_6M": 451.83,
      "Std_6M": 358.83,
      "Alert_Level": 2
    },
    {
      "DanhBa": "22053328830",
      "TenKH": "CHU MINH THANH",
      "GiaBieu": "11",
      "DinhMuc": 696.0,
      "Mean_6M": 407.83,
      "Std_6M": 337.52,
      "Alert_Level": 2
    },
    {
      "DanhBa": "22063326245",
      "TenKH": "PHAN THI THUY",
      "GiaBieu": "11",
      "DinhMuc": 0.0,
      "Mean_6M": 383.5,
      "Std_6M": 299.45,
      "Alert_Level": 2
    },
    {
      "DanhBa": "22063310099",
      "TenKH": "NGUYEN THANH NHAN",
      "GiaBieu": "11",
      "DinhMuc": 664.0,
      "Mean_6M": 373.67,
      "Std_6M": 292.44,
      "Alert_Level": 2
    },
    {
      "DanhBa": "15052170991",
      "TenKH": "LA THI THANH HUYEN",
      "GiaBieu": "11",
      "DinhMuc": 528.0,
      "Mean_6M": 372.0,
      "Std_6M": 300.8,
      "Alert_Level": 2
    },
    {
      "DanhBa": "22063310522",
      "TenKH": "TRAN HUU TRONG",
      "GiaBieu": "11",
      "DinhMuc": 404.0,
      "Mean_6M": 367.33,
      "Std_6M": 285.51,
      "Alert_Level": 2
    },
    {
      "DanhBa": "22073343285",
      "TenKH": "NGUYEN DUY LINH",
      "GiaBieu": "11",
      "DinhMuc": 0.0,
      "Mean_6M": 360.67,
      "Std_6M": 287.08,
      "Alert_Level": 2
    },
    {
      "DanhBa": "15052161460",
      "TenKH": "DOAN VAN THAI",
      "GiaBieu": "11",
      "DinhMuc": 644.0,
      "Mean_6M": 347.33,
      "Std_6M": 281.56,
      "Alert_Level": 2
    },
    {
      "DanhBa": "22063325407",
      "TenKH": "NGUYEN THI THUY CHAU",
      "GiaBieu": "11",
      "DinhMuc": 512.0,
      "Mean_6M": 339.83,
      "Std_6M": 283.87,
      "Alert_Level": 2
    },
    {
      "DanhBa": "22063323406",
      "TenKH": "HUYNH THI PHUONG",
      "GiaBieu": "11",
      "DinhMuc": 0.0,
      "Mean_6M": 331.67,
      "Std_6M": 264.56,
      "Alert_Level": 2
    },
    {
      "DanhBa": "15072488195",
      "TenKH": "NGUYEN THANH DANH",
      "GiaBieu": "11",
      "DinhMuc": 332.0,
      "Mean_6M": 331.33,
      "Std_6M": 291.78,
      "Alert_Level": 2
    },
    {
      "DanhBa": "22063325301",
      "TenKH": "VU HOANG LOAN",
      "GiaBieu": "11",
      "DinhMuc": 464.0,
      "Mean_6M": 327.0,
      "Std_6M": 332.38,
      "Alert_Level": 2
    },
    {
      "DanhBa": "15052171535",
      "TenKH": "LÊ CÔNG QUỐC TUẤN",
      "GiaBieu": "11",
      "DinhMuc": 156.0,
      "Mean_6M": 322.5,
      "Std_6M": 266.65,
      "Alert_Level": 2
    },
    {
      "DanhBa": "15052163714",
      "TenKH": "VU LE BAC",
      "GiaBieu": "11",
      "DinhMuc": 848.0,
      "Mean_6M": 316.0,
      "Std_6M": 247.92,
      "Alert_Level": 2
    },
    {
      "DanhBa": "22053397032",
      "TenKH": "NGUYỄN THỊ TƯƠI",
      "GiaBieu": "11",
      "DinhMuc": 376.0,
      "Mean_6M": 313.67,
      "Std_6M": 408.84,
      "Alert_Level": 2
    },
    {
      "DanhBa": "22063320938",
      "TenKH": "DUONG KIM ANH",
      "GiaBieu": "11",
      "DinhMuc": 504.0,
      "Mean_6M": 312.33,
      "Std_6M": 272.4,
      "Alert_Level": 2
    },
    {
      "DanhBa": "22103412290",
      "TenKH": "HA HOANG HAI",
      "GiaBieu": "11",
      "DinhMuc": 524.0,
      "Mean_6M": 308.5,
      "Std_6M": 247.62,
      "Alert_Level": 2
    },
    {
      "DanhBa": "22053296348",
      "TenKH": "TRUONG THI LE THU(DD 3 HO)",
      "GiaBieu": "11",
      "DinhMuc": 416.0,
      "Mean_6M": 307.0,
      "Std_6M": 238.08,
      "Alert_Level": 2
    },
    {
      "DanhBa": "22063310500",
      "TenKH": "NGUYEN TRONG DUNG",
      "GiaBieu": "11",
      "DinhMuc": 288.0,
      "Mean_6M": 303.83,
      "Std_6M": 238.91,
      "Alert_Level": 2
    },
    {
      "DanhBa": "22063328143",
      "TenKH": "PHẠM THỊ KIM PHƯỢNG",
      "GiaBieu": "11",
      "DinhMuc": 188.0,
      "Mean_6M": 303.0,
      "Std_6M": 237.41,
      "Alert_Level": 2
    },
    {
      "DanhBa": "22053327702",
      "TenKH": "LE THI KIEU OANH",
      "GiaBieu": "11",
      "DinhMuc": 652.0,
      "Mean_6M": 301.5,
      "Std_6M": 235.11,
      "Alert_Level": 2
    },
    {
      "DanhBa": "22063321855",
      "TenKH": "NGUYEN THI CONG",
      "GiaBieu": "11",
      "DinhMuc": 360.0,
      "Mean_6M": 298.5,
      "Std_6M": 231.82,
      "Alert_Level": 2
    },
    {
      "DanhBa": "22063323880",
      "TenKH": "HUYNH THI PHUONG",
      "GiaBieu": "11",
      "DinhMuc": 0.0,
      "Mean_6M": 287.17,
      "Std_6M": 296.05,
      "Alert_Level": 2
    },
    {
      "DanhBa": "15092661425",
      "TenKH": "HOANG THI HIEN",
      "GiaBieu": "11",
      "DinhMuc": 292.0,
      "Mean_6M": 283.17,
      "Std_6M": 222.81,
      "Alert_Level": 2
    },
    {
      "DanhBa": "15112823137",
      "TenKH": "TRAN DAI HAI",
      "GiaBieu": "11",
      "DinhMuc": 480.0,
      "Mean_6M": 281.67,
      "Std_6M": 226.17,
      "Alert_Level": 2
    },
    {
      "DanhBa": "22063324381",
      "TenKH": "NGUYEN DUC TUYEN",
      "GiaBieu": "11",
      "DinhMuc": 0.0,
      "Mean_6M": 281.33,
      "Std_6M": 667.12,
      "Alert_Level": 2
    },
    {
      "DanhBa": "15052170956",
      "TenKH": "TRAN VAN DUONG",
      "GiaBieu": "11",
      "DinhMuc": 184.0,
      "Mean_6M": 275.17,
      "Std_6M": 214.45,
      "Alert_Level": 2
    },
    {
      "DanhBa": "15052162514",
      "TenKH": "NGUYEN TUONG QUOC",
      "GiaBieu": "11",
      "DinhMuc": 548.0,
      "Mean_6M": 273.0,
      "Std_6M": 217.1,
      "Alert_Level": 2
    },
    {
      "DanhBa": "22063318225",
      "TenKH": "TRAN DINH HIEN",
      "GiaBieu": "11",
      "DinhMuc": 548.0,
      "Mean_6M": 271.83,
      "Std_6M": 211.0,
      "Alert_Level": 2
    },
    {
      "DanhBa": "22063314130",
      "TenKH": "HO QUANG DIEU",
      "GiaBieu": "11",
      "DinhMuc": 536.0,
      "Mean_6M": 270.17,
      "Std_6M": 209.42,
      "Alert_Level": 2
    },
    {
      "DanhBa": "15052168205",
      "TenKH": "DINH THANH PHONG",
      "GiaBieu": "11",
      "DinhMuc": 208.0,
      "Mean_6M": 264.83,
      "Std_6M": 223.95,
      "Alert_Level": 2
    },
    {
      "DanhBa": "22023249536",
      "TenKH": "TRAN THI MEN",
      "GiaBieu": "11",
      "DinhMuc": 0.0,
      "Mean_6M": 261.17,
      "Std_6M": 325.34,
      "Alert_Level": 2
    },
    {
      "DanhBa": "22053328648",
      "TenKH": "NGUYEN THI THUY TIEN",
      "GiaBieu": "11",
      "DinhMuc": 0.0,
      "Mean_6M": 260.17,
      "Std_6M": 348.95,
      "Alert_Level": 2
    },
    {
      "DanhBa": "22093221311",
      "TenKH": "NGUYEN ANH DUC",
      "GiaBieu": "11",
      "DinhMuc": 524.0,
      "Mean_6M": 259.5,
      "Std_6M": 205.3,
      "Alert_Level": 2
    },
    {
      "DanhBa": "22113422450",
      "TenKH": "CAO THI NGOC AN",
      "GiaBieu": "11",
      "DinhMuc": 0.0,
      "Mean_6M": 259.33,
      "Std_6M": 204.84,
      "Alert_Level": 2
    },
    {
      "DanhBa": "22063328466",
      "TenKH": "TRỊNH VĂN KHANH",
      "GiaBieu": "11",
      "DinhMuc": 0.0,
      "Mean_6M": 256.5,
      "Std_6M": 448.06,
      "Alert_Level": 2
    },
    {
      "DanhBa": "22053290650",
      "TenKH": "TRAN THI HUONG NHU",
      "GiaBieu": "11",
      "DinhMuc": 0.0,
      "Mean_6M": 254.0,
      "Std_6M": 199.76,
      "Alert_Level": 2
    },
    {
      "DanhBa": "15112829418",
      "TenKH": "LE ANH TUAN",
      "GiaBieu": "11",
      "DinhMuc": 0.0,
      "Mean_6M": 250.0,
      "Std_6M": 258.43,
      "Alert_Level": 2
    },
    {
      "DanhBa": "15072428643",
      "TenKH": "TA HUU LONG",
      "GiaBieu": "11",
      "DinhMuc": 0.0,
      "Mean_6M": 248.17,
      "Std_6M": 201.49,
      "Alert_Level": 2
    },
    {
      "DanhBa": "22093221310",
      "TenKH": "NGUYEN ANH DUC",
      "GiaBieu": "11",
      "DinhMuc": 472.0,
      "Mean_6M": 247.83,
      "Std_6M": 195.97,
      "Alert_Level": 2
    },
    {
      "DanhBa": "15052167130",
      "TenKH": "NGUYEN THI THANH PHUONG",
      "GiaBieu": "11",
      "DinhMuc": 96.0,
      "Mean_6M": 244.17,
      "Std_6M": 290.6,
      "Alert_Level": 2
    },
    {
      "DanhBa": "22103412770",
      "TenKH": "CHU DINH VIEN",
      "GiaBieu": "11",
      "DinhMuc": 340.0,
      "Mean_6M": 244.17,
      "Std_6M": 195.78,
      "Alert_Level": 2
    },
    {
      "DanhBa": "22053327078",
      "TenKH": "NGUYEN THANH TAM",
      "GiaBieu": "11",
      "DinhMuc": 380.0,
      "Mean_6M": 242.5,
      "Std_6M": 190.95,
      "Alert_Level": 2
    },
    {
      "DanhBa": "22063315091",
      "TenKH": "NGUYEN THANH HUAN",
      "GiaBieu": "11",
      "DinhMuc": 492.0,
      "Mean_6M": 240.5,
      "Std_6M": 189.15,
      "Alert_Level": 2
    },
    {
      "DanhBa": "22043307032",
      "TenKH": "HA MINH SON",
      "GiaBieu": "11",
      "DinhMuc": 0.0,
      "Mean_6M": 240.5,
      "Std_6M": 187.24,
      "Alert_Level": 2
    },
    {
      "DanhBa": "22063325398",
      "TenKH": "NGUYEN THI NGOC DUNG",
      "GiaBieu": "11",
      "DinhMuc": 556.0,
      "Mean_6M": 240.17,
      "Std_6M": 198.61,
      "Alert_Level": 2
    },
    {
      "DanhBa": "22063322567",
      "TenKH": "PHAN THE LUAN",
      "GiaBieu": "11",
      "DinhMuc": 348.0,
      "Mean_6M": 237.17,
      "Std_6M": 184.54,
      "Alert_Level": 2
    },
    {
      "DanhBa": "22093217000",
      "TenKH": "HA THI THUY",
      "GiaBieu": "11",
      "DinhMuc": 424.0,
      "Mean_6M": 237.0,
      "Std_6M": 186.18,
      "Alert_Level": 2
    },
    {
      "DanhBa": "15062135394",
      "TenKH": "TRUONG THI NAM",
      "GiaBieu": "11",
      "DinhMuc": 652.0,
      "Mean_6M": 236.67,
      "Std_6M": 198.56,
      "Alert_Level": 2
    },
    {
      "DanhBa": "15102721804",
      "TenKH": "TRAN CAO THANH",
      "GiaBieu": "11",
      "DinhMuc": 0.0,
      "Mean_6M": 235.33,
      "Std_6M": 471.92,
      "Alert_Level": 2
    },
    {
      "DanhBa": "22053323204",
      "TenKH": "NGUYEN THANH TAM",
      "GiaBieu": "11",
      "DinhMuc": 380.0,
      "Mean_6M": 232.5,
      "Std_6M": 187.13,
      "Alert_Level": 2
    },
    {
      "DanhBa": "22053329608",
      "TenKH": "PHAN TRUONG DUY",
      "GiaBieu": "11",
      "DinhMuc": 0.0,
      "Mean_6M": 232.33,
      "Std_6M": 188.09,
      "Alert_Level": 2
    },
    {
      "DanhBa": "15052167147",
      "TenKH": "NGUYEN THI LEN",
      "GiaBieu": "11",
      "DinhMuc": 0.0,
      "Mean_6M": 229.33,
      "Std_6M": 185.22,
      "Alert_Level": 2
    },
    {
      "DanhBa": "22063327361",
      "TenKH": "NGUYEN MINH CUONG",
      "GiaBieu": "11",
      "DinhMuc": 540.0,
      "Mean_6M": 229.33,
      "Std_6M": 193.9,
      "Alert_Level": 2
    },
    {
      "DanhBa": "15062138848",
      "TenKH": "NGUYEN VAN HANH",
      "GiaBieu": "11",
      "DinhMuc": 292.0,
      "Mean_6M": 227.5,
      "Std_6M": 182.79,
      "Alert_Level": 2
    },
    {
      "DanhBa": "15062141062",
      "TenKH": "NGUYEN MINH TRI",
      "GiaBieu": "11",
      "DinhMuc": 112.0,
      "Mean_6M": 227.0,
      "Std_6M": 188.33,
      "Alert_Level": 2
    },
    {
      "DanhBa": "15062130167",
      "TenKH": "DO MINH TIEN",
      "GiaBieu": "11",
      "DinhMuc": 0.0,
      "Mean_6M": 226.5,
      "Std_6M": 207.4,
      "Alert_Level": 2
    },
    {
      "DanhBa": "22063326465",
      "TenKH": "DINH VAN HOA",
      "GiaBieu": "11",
      "DinhMuc": 0.0,
      "Mean_6M": 225.67,
      "Std_6M": 225.07,
      "Alert_Level": 2
    },
    {
      "DanhBa": "15052167671",
      "TenKH": "LY KIM DU",
      "GiaBieu": "11",
      "DinhMuc": 240.0,
      "Mean_6M": 225.17,
      "Std_6M": 177.89,
      "Alert_Level": 2
    },
    {
      "DanhBa": "22043311233",
      "TenKH": "NGUYEN DUY LINH",
      "GiaBieu": "11",
      "DinhMuc": 0.0,
      "Mean_6M": 225.17,
      "Std_6M": 179.08,
      "Alert_Level": 2
    },
    {
      "DanhBa": "22043274452",
      "TenKH": "TRUONG THI NGOC THUONG",
      "GiaBieu": "11",
      "DinhMuc": 0.0,
      "Mean_6M": 223.5,
      "Std_6M": 543.06,
      "Alert_Level": 2
    },
    {
      "DanhBa": "15052166942",
      "TenKH": "VU QUANG VINH",
      "GiaBieu": "11",
      "DinhMuc": 664.0,
      "Mean_6M": 219.33,
      "Std_6M": 175.72,
      "Alert_Level": 2
    },
    {
      "DanhBa": "22053327077",
      "TenKH": "NGUYEN THANH TAM",
      "GiaBieu": "11",
      "DinhMuc": 392.0,
      "Mean_6M": 219.33,
      "Std_6M": 172.76,
      "Alert_Level": 2
    },
    {
      "DanhBa": "22063327972",
      "TenKH": "HỒ THẾ HUY",
      "GiaBieu": "11",
      "DinhMuc": 144.0,
      "Mean_6M": 219.17,
      "Std_6M": 174.74,
      "Alert_Level": 2
    },
    {
      "DanhBa": "22063325007",
      "TenKH": "BUI VAN DUC",
      "GiaBieu": "11",
      "DinhMuc": 252.0,
      "Mean_6M": 218.33,
      "Std_6M": 186.26,
      "Alert_Level": 2
    },
    {
      "DanhBa": "22053321233",
      "TenKH": "LE VAN CUONG",
      "GiaBieu": "11",
      "DinhMuc": 40.0,
      "Mean_6M": 217.83,
      "Std_6M": 235.08,
      "Alert_Level": 2
    },
    {
      "DanhBa": "15052162529",
      "TenKH": "HA THI THANH HUONG",
      "GiaBieu": "11",
      "DinhMuc": 0.0,
      "Mean_6M": 217.33,
      "Std_6M": 177.35,
      "Alert_Level": 2
    },
    {
      "DanhBa": "15052171331",
      "TenKH": "NGUYEN THI LUU LUYEN",
      "GiaBieu": "11",
      "DinhMuc": 0.0,
      "Mean_6M": 216.17,
      "Std_6M": 171.0,
      "Alert_Level": 2
    },
    {
      "DanhBa": "22093221130",
      "TenKH": "HUA NGOC MY",
      "GiaBieu": "11",
      "DinhMuc": 440.0,
      "Mean_6M": 215.33,
      "Std_6M": 172.08,
      "Alert_Level": 2
    },
    {
      "DanhBa": "22053303526",
      "TenKH": "LUONG THI NHO",
      "GiaBieu": "11",
      "DinhMuc": 420.0,
      "Mean_6M": 214.67,
      "Std_6M": 167.22,
      "Alert_Level": 2
    },
    {
      "DanhBa": "22043273095",
      "TenKH": "NGUYEN MINH TUAN",
      "GiaBieu": "11",
      "DinhMuc": 348.0,
      "Mean_6M": 214.67,
      "Std_6M": 181.88,
      "Alert_Level": 2
    },
    {
      "DanhBa": "22063317100",
      "TenKH": "NGUYEN VAN MOT",
      "GiaBieu": "11",
      "DinhMuc": 0.0,
      "Mean_6M": 213.5,
      "Std_6M": 172.49,
      "Alert_Level": 2
    },
    {
      "DanhBa": "22063328247",
      "TenKH": "NGUYỄN PHẠM HOÀNG HẢI",
      "GiaBieu": "11",
      "DinhMuc": 0.0,
      "Mean_6M": 212.5,
      "Std_6M": 167.67,
      "Alert_Level": 2
    },
    {
      "DanhBa": "22033279036",
      "TenKH": "NGUYEN VAN VANG",
      "GiaBieu": "11",
      "DinhMuc": 0.0,
      "Mean_6M": 211.67,
      "Std_6M": 518.48,
      "Alert_Level": 2
    },
    {
      "DanhBa": "15092650864",
      "TenKH": "NGUYEN HOANG LAC",
      "GiaBieu": "11",
      "DinhMuc": 92.0,
      "Mean_6M": 210.17,
      "Std_6M": 164.8,
      "Alert_Level": 2
    },
    {
      "DanhBa": "22063324682",
      "TenKH": "BUI VAN DUC",
      "GiaBieu": "11",
      "DinhMuc": 272.0,
      "Mean_6M": 209.33,
      "Std_6M": 177.45,
      "Alert_Level": 2
    },
    {
      "DanhBa": "22073342861",
      "TenKH": "VU ANH HOANG",
      "GiaBieu": "11",
      "DinhMuc": 0.0,
      "Mean_6M": 209.17,
      "Std_6M": 165.72,
      "Alert_Level": 2
    },
    {
      "DanhBa": "22063323366",
      "TenKH": "NGUYEN HUY CHUONG",
      "GiaBieu": "11",
      "DinhMuc": 400.0,
      "Mean_6M": 208.67,
      "Std_6M": 161.84,
      "Alert_Level": 2
    },
    {
      "DanhBa": "22063327511",
      "TenKH": "DO THI MY NGOC",
      "GiaBieu": "11",
      "DinhMuc": 272.0,
      "Mean_6M": 207.33,
      "Std_6M": 172.68,
      "Alert_Level": 2
    },
    {
      "DanhBa": "15052120923",
      "TenKH": "CHUNG NGUYEN",
      "GiaBieu": "11",
      "DinhMuc": 636.0,
      "Mean_6M": 207.0,
      "Std_6M": 214.41,
      "Alert_Level": 2
    },
    {
      "DanhBa": "15112825145",
      "TenKH": "VU THI THU NGA",
      "GiaBieu": "11",
      "DinhMuc": 4.0,
      "Mean_6M": 206.17,
      "Std_6M": 160.91,
      "Alert_Level": 2
    },
    {
      "DanhBa": "22063323576",
      "TenKH": "TRUONG THI TRON",
      "GiaBieu": "11",
      "DinhMuc": 0.0,
      "Mean_6M": 205.83,
      "Std_6M": 165.42,
      "Alert_Level": 2
    },
    {
      "DanhBa": "22063327903",
      "TenKH": "NGUYEN THI NHU ANH",
      "GiaBieu": "11",
      "DinhMuc": 416.0,
      "Mean_6M": 205.5,
      "Std_6M": 171.25,
      "Alert_Level": 2
    },
    {
      "DanhBa": "15062130190",
      "TenKH": "TRUONG TRI TU HUYNH",
      "GiaBieu": "11",
      "DinhMuc": 132.0,
      "Mean_6M": 205.17,
      "Std_6M": 282.86,
      "Alert_Level": 2
    },
    {
      "DanhBa": "22093370101",
      "TenKH": "TO THI THU HA",
      "GiaBieu": "11",
      "DinhMuc": 228.0,
      "Mean_6M": 204.5,
      "Std_6M": 216.61,
      "Alert_Level": 2
    },
    {
      "DanhBa": "15082510706",
      "TenKH": "DO VAN PHONG",
      "GiaBieu": "11",
      "DinhMuc": 324.0,
      "Mean_6M": 203.17,
      "Std_6M": 166.14,
      "Alert_Level": 2
    },
    {
      "DanhBa": "15052165310",
      "TenKH": "NGUYEN THANH KIM",
      "GiaBieu": "11",
      "DinhMuc": 464.0,
      "Mean_6M": 202.5,
      "Std_6M": 202.62,
      "Alert_Level": 2
    },
    {
      "DanhBa": "15062133585",
      "TenKH": "PHAM THI KIM PHUONG",
      "GiaBieu": "11",
      "DinhMuc": 380.0,
      "Mean_6M": 201.83,
      "Std_6M": 171.04,
      "Alert_Level": 2
    },
    {
      "DanhBa": "15052170718",
      "TenKH": "PHAM THI HIEN",
      "GiaBieu": "11",
      "DinhMuc": 260.0,
      "Mean_6M": 201.5,
      "Std_6M": 158.86,
      "Alert_Level": 2
    },
    {
      "DanhBa": "22053290643",
      "TenKH": "DANG MINH THAO",
      "GiaBieu": "11",
      "DinhMuc": 368.0,
      "Mean_6M": 200.5,
      "Std_6M": 159.82,
      "Alert_Level": 2
    },
    {
      "DanhBa": "22063322187",
      "TenKH": "NGUYEN DOAN ANH VI",
      "GiaBieu": "11",
      "DinhMuc": 0.0,
      "Mean_6M": 200.0,
      "Std_6M": 168.04,
      "Alert_Level": 2
    },
    {
      "DanhBa": "22043300822",
      "TenKH": "HUYNH THI KIM LIEN",
      "GiaBieu": "11",
      "DinhMuc": 16.0,
      "Mean_6M": 199.67,
      "Std_6M": 163.61,
      "Alert_Level": 2
    },
    {
      "DanhBa": "22053324332",
      "TenKH": "HO QUANG DIEU",
      "GiaBieu": "11",
      "DinhMuc": 340.0,
      "Mean_6M": 199.17,
      "Std_6M": 156.55,
      "Alert_Level": 2
    },
    {
      "DanhBa": "22053321658",
      "TenKH": "DOAN VAN KHOA",
      "GiaBieu": "11",
      "DinhMuc": 140.0,
      "Mean_6M": 198.17,
      "Std_6M": 156.27,
      "Alert_Level": 2
    },
    {
      "DanhBa": "22063325005",
      "TenKH": "VU THI NHAM",
      "GiaBieu": "11",
      "DinhMuc": 0.0,
      "Mean_6M": 198.0,
      "Std_6M": 156.92,
      "Alert_Level": 2
    },
    {
      "DanhBa": "22053291017",
      "TenKH": "TRAN THUC MINH",
      "GiaBieu": "11",
      "DinhMuc": 80.0,
      "Mean_6M": 196.5,
      "Std_6M": 179.89,
      "Alert_Level": 2
    },
    {
      "DanhBa": "22063327214",
      "TenKH": "MAI CONG TAM",
      "GiaBieu": "11",
      "DinhMuc": 360.0,
      "Mean_6M": 196.33,
      "Std_6M": 154.24,
      "Alert_Level": 2
    },
    {
      "DanhBa": "15082521526",
      "TenKH": "LE VY DAN",
      "GiaBieu": "11",
      "DinhMuc": 0.0,
      "Mean_6M": 196.33,
      "Std_6M": 257.27,
      "Alert_Level": 2
    },
    {
      "DanhBa": "15062140947",
      "TenKH": "LE THI NGOC HONG",
      "GiaBieu": "11",
      "DinhMuc": 96.0,
      "Mean_6M": 196.0,
      "Std_6M": 170.88,
      "Alert_Level": 2
    },
    {
      "DanhBa": "22053290590",
      "TenKH": "CHUNG HOANG NHAN",
      "GiaBieu": "11",
      "DinhMuc": 288.0,
      "Mean_6M": 195.83,
      "Std_6M": 158.87,
      "Alert_Level": 2
    },
    {
      "DanhBa": "22063327560",
      "TenKH": "DINH THANH TUNG",
      "GiaBieu": "11",
      "DinhMuc": 252.0,
      "Mean_6M": 195.33,
      "Std_6M": 152.74,
      "Alert_Level": 2
    },
    {
      "DanhBa": "22063325006",
      "TenKH": "BUI VAN DUC",
      "GiaBieu": "11",
      "DinhMuc": 300.0,
      "Mean_6M": 195.33,
      "Std_6M": 169.01,
      "Alert_Level": 2
    },
    {
      "DanhBa": "22063308212",
      "TenKH": "PHAN THI MY YEN",
      "GiaBieu": "11",
      "DinhMuc": 156.0,
      "Mean_6M": 195.17,
      "Std_6M": 162.83,
      "Alert_Level": 2
    },
    {
      "DanhBa": "22063322183",
      "TenKH": "DINH THI HONG LAM",
      "GiaBieu": "11",
      "DinhMuc": 72.0,
      "Mean_6M": 195.17,
      "Std_6M": 166.16,
      "Alert_Level": 2
    },
    {
      "DanhBa": "15052170850",
      "TenKH": "DO TAN THANH",
      "GiaBieu": "11",
      "DinhMuc": 356.0,
      "Mean_6M": 194.67,
      "Std_6M": 152.17,
      "Alert_Level": 2
    },
    {
      "DanhBa": "22063327512",
      "TenKH": "DO THI MY NGOC",
      "GiaBieu": "11",
      "DinhMuc": 168.0,
      "Mean_6M": 193.67,
      "Std_6M": 162.75,
      "Alert_Level": 2
    },
    {
      "DanhBa": "15052162516",
      "TenKH": "VO VAN VIET",
      "GiaBieu": "11",
      "DinhMuc": 156.0,
      "Mean_6M": 193.5,
      "Std_6M": 150.68,
      "Alert_Level": 2
    },
    {
      "DanhBa": "22023249838",
      "TenKH": "HOANG MINH TUNG",
      "GiaBieu": "11",
      "DinhMuc": 480.0,
      "Mean_6M": 193.0,
      "Std_6M": 153.59,
      "Alert_Level": 2
    },
    {
      "DanhBa": "15042008280",
      "TenKH": "NGUYEN THI TAM",
      "GiaBieu": "11",
      "DinhMuc": 152.0,
      "Mean_6M": 192.33,
      "Std_6M": 152.88,
      "Alert_Level": 2
    },
    {
      "DanhBa": "22063324995",
      "TenKH": "PHAM XUAN HUYEN",
      "GiaBieu": "11",
      "DinhMuc": 336.0,
      "Mean_6M": 191.33,
      "Std_6M": 162.92,
      "Alert_Level": 2
    },
    {
      "DanhBa": "22063327890",
      "TenKH": "TRAN DUC NGHIA",
      "GiaBieu": "11",
      "DinhMuc": 0.0,
      "Mean_6M": 191.17,
      "Std_6M": 185.84,
      "Alert_Level": 2
    },
    {
      "DanhBa": "15031743355",
      "TenKH": "TRAN T MINH TAN",
      "GiaBieu": "11",
      "DinhMuc": 0.0,
      "Mean_6M": 189.67,
      "Std_6M": 149.2,
      "Alert_Level": 2
    },
    {
      "DanhBa": "15052162320",
      "TenKH": "DO NGUYEN SINH",
      "GiaBieu": "11",
      "DinhMuc": 220.0,
      "Mean_6M": 189.33,
      "Std_6M": 147.86,
      "Alert_Level": 2
    },
    {
      "DanhBa": "15132028432",
      "TenKH": "TRAN TAN",
      "GiaBieu": "11",
      "DinhMuc": 72.0,
      "Mean_6M": 189.33,
      "Std_6M": 147.09,
      "Alert_Level": 2
    },
    {
      "DanhBa": "15052171457",
      "TenKH": "DAM LE TUYET NHUNG",
      "GiaBieu": "11",
      "DinhMuc": 232.0,
      "Mean_6M": 189.0,
      "Std_6M": 154.14,
      "Alert_Level": 2
    },
    {
      "DanhBa": "22063324955",
      "TenKH": "TRINH VAN KHANH",
      "GiaBieu": "11",
      "DinhMuc": 0.0,
      "Mean_6M": 189.0,
      "Std_6M": 271.46,
      "Alert_Level": 2
    },
    {
      "DanhBa": "15062141187",
      "TenKH": "TRUONG THI NGOC LIEN",
      "GiaBieu": "11",
      "DinhMuc": 0.0,
      "Mean_6M": 188.83,
      "Std_6M": 160.21,
      "Alert_Level": 2
    },
    {
      "DanhBa": "15062133596",
      "TenKH": "NGUYEN THU HANG",
      "GiaBieu": "11",
      "DinhMuc": 256.0,
      "Mean_6M": 188.0,
      "Std_6M": 149.74,
      "Alert_Level": 2
    },
    {
      "DanhBa": "22093220903",
      "TenKH": "PHAM TUAN",
      "GiaBieu": "11",
      "DinhMuc": 192.0,
      "Mean_6M": 188.0,
      "Std_6M": 146.9,
      "Alert_Level": 2
    },
    {
      "DanhBa": "15173424168",
      "TenKH": "NGUYEN TU",
      "GiaBieu": "11",
      "DinhMuc": 0.0,
      "Mean_6M": 188.0,
      "Std_6M": 452.2,
      "Alert_Level": 2
    },
    {
      "DanhBa": "22063310233",
      "TenKH": "NGUYEN VAN TUAN",
      "GiaBieu": "11",
      "DinhMuc": 284.0,
      "Mean_6M": 187.33,
      "Std_6M": 146.15,
      "Alert_Level": 2
    },
    {
      "DanhBa": "15052160617",
      "TenKH": "TRAN THANH NAM",
      "GiaBieu": "11",
      "DinhMuc": 16.0,
      "Mean_6M": 187.0,
      "Std_6M": 443.87,
      "Alert_Level": 2
    },
    {
      "DanhBa": "22063327754",
      "TenKH": "NGUYEN THI QUYEN",
      "GiaBieu": "11",
      "DinhMuc": 0.0,
      "Mean_6M": 185.5,
      "Std_6M": 157.9,
      "Alert_Level": 2
    },
    {
      "DanhBa": "22063310252",
      "TenKH": "NG VAN DIEP",
      "GiaBieu": "11",
      "DinhMuc": 360.0,
      "Mean_6M": 185.33,
      "Std_6M": 146.86,
      "Alert_Level": 2
    },
    {
      "DanhBa": "15031702427",
      "TenKH": "LE THI MY KIEU",
      "GiaBieu": "11",
      "DinhMuc": 84.0,
      "Mean_6M": 185.17,
      "Std_6M": 175.5,
      "Alert_Level": 2
    },
    {
      "DanhBa": "22063327516",
      "TenKH": "VU DUC TUAN",
      "GiaBieu": "11",
      "DinhMuc": 264.0,
      "Mean_6M": 184.83,
      "Std_6M": 159.5,
      "Alert_Level": 2
    },
    {
      "DanhBa": "15052167030",
      "TenKH": "NGUYEN TRINH PHI NGA",
      "GiaBieu": "11",
      "DinhMuc": 56.0,
      "Mean_6M": 184.5,
      "Std_6M": 222.45,
      "Alert_Level": 2
    },
    {
      "DanhBa": "22063327485",
      "TenKH": "NGUYEN DINH LUC",
      "GiaBieu": "11",
      "DinhMuc": 4.0,
      "Mean_6M": 184.17,
      "Std_6M": 145.94,
      "Alert_Level": 2
    },
    {
      "DanhBa": "15052169631",
      "TenKH": "TRAN ANH DUNG",
      "GiaBieu": "11",
      "DinhMuc": 180.0,
      "Mean_6M": 183.83,
      "Std_6M": 146.57,
      "Alert_Level": 2
    },
    {
      "DanhBa": "22063320581",
      "TenKH": "NGUYEN THI RANG",
      "GiaBieu": "11",
      "DinhMuc": 320.0,
      "Mean_6M": 183.83,
      "Std_6M": 145.24,
      "Alert_Level": 2
    },
    {
      "DanhBa": "15072440361",
      "TenKH": "LE MINH HIEP",
      "GiaBieu": "11",
      "DinhMuc": 228.0,
      "Mean_6M": 183.5,
      "Std_6M": 154.63,
      "Alert_Level": 2
    },
    {
      "DanhBa": "15041908561",
      "TenKH": "HOANG VAN BANG",
      "GiaBieu": "11",
      "DinhMuc": 168.0,
      "Mean_6M": 183.5,
      "Std_6M": 146.0,
      "Alert_Level": 2
    },
    {
      "DanhBa": "22103410512",
      "TenKH": "VU HOANG LONG",
      "GiaBieu": "11",
      "DinhMuc": 200.0,
      "Mean_6M": 183.17,
      "Std_6M": 145.22,
      "Alert_Level": 2
    },
    {
      "DanhBa": "22043276670",
      "TenKH": "NGUYEN VAN SAU",
      "GiaBieu": "11",
      "DinhMuc": 0.0,
      "Mean_6M": 183.0,
      "Std_6M": 143.49,
      "Alert_Level": 2
    },
    {
      "DanhBa": "22043290355",
      "TenKH": "VU VAN DAI",
      "GiaBieu": "11",
      "DinhMuc": 336.0,
      "Mean_6M": 182.17,
      "Std_6M": 158.31,
      "Alert_Level": 2
    },
    {
      "DanhBa": "15072421007",
      "TenKH": "BUI VAN LOC",
      "GiaBieu": "11",
      "DinhMuc": 84.0,
      "Mean_6M": 181.5,
      "Std_6M": 152.1,
      "Alert_Level": 2
    },
    {
      "DanhBa": "22053320591",
      "TenKH": "NGUYEN NGOC CUONG",
      "GiaBieu": "11",
      "DinhMuc": 0.0,
      "Mean_6M": 181.0,
      "Std_6M": 144.22,
      "Alert_Level": 2
    },
    {
      "DanhBa": "22073342777",
      "TenKH": "NGUYEN DUY DAI",
      "GiaBieu": "11",
      "DinhMuc": 304.0,
      "Mean_6M": 179.5,
      "Std_6M": 142.42,
      "Alert_Level": 2
    },
    {
      "DanhBa": "15052171032",
      "TenKH": "LE DUY TOI",
      "GiaBieu": "11",
      "DinhMuc": 0.0,
      "Mean_6M": 178.83,
      "Std_6M": 140.63,
      "Alert_Level": 2
    },
    {
      "DanhBa": "22103396344",
      "TenKH": "NGUYEN THI NGOC HA",
      "GiaBieu": "11",
      "DinhMuc": 236.0,
      "Mean_6M": 178.17,
      "Std_6M": 141.91,
      "Alert_Level": 2
    },
    {
      "DanhBa": "22063312430",
      "TenKH": "PHAN KHAC TU",
      "GiaBieu": "11",
      "DinhMuc": 224.0,
      "Mean_6M": 178.17,
      "Std_6M": 139.56,
      "Alert_Level": 2
    },
    {
      "DanhBa": "15141948889",
      "TenKH": "PHAM DUONG DOAN",
      "GiaBieu": "11",
      "DinhMuc": 0.0,
      "Mean_6M": 178.17,
      "Std_6M": 138.48,
      "Alert_Level": 2
    },
    {
      "DanhBa": "15112827004",
      "TenKH": "PHAN THI SUONG",
      "GiaBieu": "11",
      "DinhMuc": 0.0,
      "Mean_6M": 177.67,
      "Std_6M": 142.24,
      "Alert_Level": 2
    },
    {
      "DanhBa": "22053323205",
      "TenKH": "NGUYEN THANH TAM",
      "GiaBieu": "11",
      "DinhMuc": 364.0,
      "Mean_6M": 176.33,
      "Std_6M": 157.23,
      "Alert_Level": 2
    },
    {
      "DanhBa": "22063304725",
      "TenKH": "NGUYEN VAN TAI",
      "GiaBieu": "11",
      "DinhMuc": 28.0,
      "Mean_6M": 174.67,
      "Std_6M": 136.78,
      "Alert_Level": 2
    },
    {
      "DanhBa": "22113410372",
      "TenKH": "HO CHI TUYEN",
      "GiaBieu": "11",
      "DinhMuc": 20.0,
      "Mean_6M": 172.5,
      "Std_6M": 406.93,
      "Alert_Level": 2
    },
    {
      "DanhBa": "22063318542",
      "TenKH": "DAO NGOC HUNG",
      "GiaBieu": "11",
      "DinhMuc": 232.0,
      "Mean_6M": 172.5,
      "Std_6M": 156.03,
      "Alert_Level": 2
    },
    {
      "DanhBa": "22053322815",
      "TenKH": "TRAN THI XINH",
      "GiaBieu": "11",
      "DinhMuc": 0.0,
      "Mean_6M": 171.67,
      "Std_6M": 133.35,
      "Alert_Level": 2
    },
    {
      "DanhBa": "15052165529",
      "TenKH": "LE VAN DUNG",
      "GiaBieu": "11",
      "DinhMuc": 0.0,
      "Mean_6M": 170.33,
      "Std_6M": 297.65,
      "Alert_Level": 2
    },
    {
      "DanhBa": "15062141137",
      "TenKH": "NGUYEN THI TRUONG",
      "GiaBieu": "11",
      "DinhMuc": 88.0,
      "Mean_6M": 170.33,
      "Std_6M": 134.2,
      "Alert_Level": 2
    },
    {
      "DanhBa": "22093216120",
      "TenKH": "NGUYEN THI BICH LOAN",
      "GiaBieu": "11",
      "DinhMuc": 352.0,
      "Mean_6M": 170.17,
      "Std_6M": 135.61,
      "Alert_Level": 2
    },
    {
      "DanhBa": "22063320910",
      "TenKH": "NGUYEN TUAN LOC",
      "GiaBieu": "11",
      "DinhMuc": 276.0,
      "Mean_6M": 169.67,
      "Std_6M": 133.39,
      "Alert_Level": 2
    },
    {
      "DanhBa": "22043303913",
      "TenKH": "CHAU VAN VINH",
      "GiaBieu": "11",
      "DinhMuc": 256.0,
      "Mean_6M": 169.5,
      "Std_6M": 133.47,
      "Alert_Level": 2
    },
    {
      "DanhBa": "22073238437",
      "TenKH": "NGUYEN QUOC CHIEN",
      "GiaBieu": "11",
      "DinhMuc": 112.0,
      "Mean_6M": 169.33,
      "Std_6M": 135.56,
      "Alert_Level": 2
    },
    {
      "DanhBa": "15052164240",
      "TenKH": "LE THI ANH TUYET",
      "GiaBieu": "11",
      "DinhMuc": 0.0,
      "Mean_6M": 169.0,
      "Std_6M": 140.11,
      "Alert_Level": 2
    },
    {
      "DanhBa": "15062140367",
      "TenKH": "LE THI HUONG",
      "GiaBieu": "11",
      "DinhMuc": 156.0,
      "Mean_6M": 168.83,
      "Std_6M": 133.51,
      "Alert_Level": 2
    },
    {
      "DanhBa": "15052165430",
      "TenKH": "TRAN VAN KHOA",
      "GiaBieu": "11",
      "DinhMuc": 244.0,
      "Mean_6M": 168.67,
      "Std_6M": 131.93,
      "Alert_Level": 2
    },
    {
      "DanhBa": "22093381417",
      "TenKH": "TRAN VAN TOI",
      "GiaBieu": "11",
      "DinhMuc": 120.0,
      "Mean_6M": 168.0,
      "Std_6M": 142.01,
      "Alert_Level": 2
    },
    {
      "DanhBa": "15041906309",
      "TenKH": "NGUYEN THI HONG",
      "GiaBieu": "11",
      "DinhMuc": 0.0,
      "Mean_6M": 167.0,
      "Std_6M": 129.47,
      "Alert_Level": 2
    },
    {
      "DanhBa": "22063323368",
      "TenKH": "NGUYEN TRUNG TRUC",
      "GiaBieu": "11",
      "DinhMuc": 212.0,
      "Mean_6M": 166.17,
      "Std_6M": 130.82,
      "Alert_Level": 2
    },
    {
      "DanhBa": "22063305340",
      "TenKH": "DUONG THI HUU",
      "GiaBieu": "11",
      "DinhMuc": 252.0,
      "Mean_6M": 165.83,
      "Std_6M": 129.35,
      "Alert_Level": 2
    },
    {
      "DanhBa": "22063320785",
      "TenKH": "NGUYEN THI LAU",
      "GiaBieu": "11",
      "DinhMuc": 292.0,
      "Mean_6M": 165.17,
      "Std_6M": 128.54,
      "Alert_Level": 2
    },
    {
      "DanhBa": "22053327147",
      "TenKH": "NGUYEN QUOC ANH",
      "GiaBieu": "11",
      "DinhMuc": 44.0,
      "Mean_6M": 165.17,
      "Std_6M": 129.67,
      "Alert_Level": 2
    },
    {
      "DanhBa": "15112864181",
      "TenKH": "NGUYEN THI DOAN",
      "GiaBieu": "11",
      "DinhMuc": 288.0,
      "Mean_6M": 165.0,
      "Std_6M": 136.33,
      "Alert_Level": 2
    },
    {
      "DanhBa": "22053297107",
      "TenKH": "PHAM THI HOA",
      "GiaBieu": "11",
      "DinhMuc": 36.0,
      "Mean_6M": 164.33,
      "Std_6M": 129.87,
      "Alert_Level": 2
    },
    {
      "DanhBa": "15062132325",
      "TenKH": "NGUYEN THI HUONG",
      "GiaBieu": "11",
      "DinhMuc": 20.0,
      "Mean_6M": 163.83,
      "Std_6M": 127.61,
      "Alert_Level": 2
    },
    {
      "DanhBa": "22043305564",
      "TenKH": "BUI THI KIM NGAN",
      "GiaBieu": "11",
      "DinhMuc": 68.0,
      "Mean_6M": 163.67,
      "Std_6M": 126.91,
      "Alert_Level": 2
    },
    {
      "DanhBa": "22103406200",
      "TenKH": "PHAN VAN THO",
      "GiaBieu": "11",
      "DinhMuc": 228.0,
      "Mean_6M": 163.5,
      "Std_6M": 129.42,
      "Alert_Level": 2
    },
    {
      "DanhBa": "22063310731",
      "TenKH": "NGUYEN VAN MINH",
      "GiaBieu": "11",
      "DinhMuc": 128.0,
      "Mean_6M": 163.33,
      "Std_6M": 128.43,
      "Alert_Level": 2
    },
    {
      "DanhBa": "15031700214",
      "TenKH": "DUONG HAI HA",
      "GiaBieu": "11",
      "DinhMuc": 12.0,
      "Mean_6M": 163.17,
      "Std_6M": 359.79,
      "Alert_Level": 2
    },
    {
      "DanhBa": "22053298574",
      "TenKH": "NGUYEN NGOC TU",
      "GiaBieu": "11",
      "DinhMuc": 0.0,
      "Mean_6M": 162.67,
      "Std_6M": 141.54,
      "Alert_Level": 2
    },
    {
      "DanhBa": "15062140644",
      "TenKH": "PHAN THI KIM CHUNG",
      "GiaBieu": "11",
      "DinhMuc": 172.0,
      "Mean_6M": 162.5,
      "Std_6M": 127.12,
      "Alert_Level": 2
    },
    {
      "DanhBa": "22043304538",
      "TenKH": "DINH KIM QUI",
      "GiaBieu": "11",
      "DinhMuc": 16.0,
      "Mean_6M": 161.67,
      "Std_6M": 126.31,
      "Alert_Level": 2
    },
    {
      "DanhBa": "22053308237",
      "TenKH": "NGUYEN THI HA",
      "GiaBieu": "11",
      "DinhMuc": 0.0,
      "Mean_6M": 160.5,
      "Std_6M": 129.8,
      "Alert_Level": 2
    },
    {
      "DanhBa": "15082510051",
      "TenKH": "NGUYEN THI SANG",
      "GiaBieu": "11",
      "DinhMuc": 0.0,
      "Mean_6M": 159.83,
      "Std_6M": 268.47,
      "Alert_Level": 2
    },
    {
      "DanhBa": "15072468269",
      "TenKH": "LÝ LÊ MỸ HOÀNG ",
      "GiaBieu": "11",
      "DinhMuc": 0.0,
      "Mean_6M": 159.83,
      "Std_6M": 184.23,
      "Alert_Level": 2
    },
    {
      "DanhBa": "15112829086",
      "TenKH": "HUYNH VAN TAN",
      "GiaBieu": "11",
      "DinhMuc": 228.0,
      "Mean_6M": 159.83,
      "Std_6M": 133.88,
      "Alert_Level": 2
    },
    {
      "DanhBa": "22093379280",
      "TenKH": "NGUYEN THI THUY LINH",
      "GiaBieu": "11",
      "DinhMuc": 4.0,
      "Mean_6M": 159.33,
      "Std_6M": 123.97,
      "Alert_Level": 2
    },
    {
      "DanhBa": "22063325963",
      "TenKH": "NGUYEN NGOC CHUONG",
      "GiaBieu": "11",
      "DinhMuc": 0.0,
      "Mean_6M": 158.67,
      "Std_6M": 237.32,
      "Alert_Level": 2
    },
    {
      "DanhBa": "15161970369",
      "TenKH": "NGUYEN HA PHUONG",
      "GiaBieu": "11",
      "DinhMuc": 236.0,
      "Mean_6M": 158.5,
      "Std_6M": 138.85,
      "Alert_Level": 2
    },
    {
      "DanhBa": "22063320446",
      "TenKH": "NGUYEN TUAN PHONG",
      "GiaBieu": "11",
      "DinhMuc": 216.0,
      "Mean_6M": 158.5,
      "Std_6M": 124.15,
      "Alert_Level": 2
    },
    {
      "DanhBa": "22063320137",
      "TenKH": "TRAN THI CAM TU",
      "GiaBieu": "11",
      "DinhMuc": 276.0,
      "Mean_6M": 157.67,
      "Std_6M": 123.14,
      "Alert_Level": 2
    },
    {
      "DanhBa": "22053290980",
      "TenKH": "TRINH THI HOA",
      "GiaBieu": "11",
      "DinhMuc": 108.0,
      "Mean_6M": 156.83,
      "Std_6M": 142.09,
      "Alert_Level": 2
    },
    {
      "DanhBa": "22043272170",
      "TenKH": "NGUYEN DUC DAO",
      "GiaBieu": "11",
      "DinhMuc": 4.0,
      "Mean_6M": 156.67,
      "Std_6M": 159.03,
      "Alert_Level": 2
    },
    {
      "DanhBa": "15041908555",
      "TenKH": "PHAN SI LIEU",
      "GiaBieu": "11",
      "DinhMuc": 128.0,
      "Mean_6M": 155.83,
      "Std_6M": 126.6,
      "Alert_Level": 2
    },
    {
      "DanhBa": "22053290845",
      "TenKH": "PHAN KIM NHI",
      "GiaBieu": "11",
      "DinhMuc": 236.0,
      "Mean_6M": 155.5,
      "Std_6M": 141.86,
      "Alert_Level": 2
    },
    {
      "DanhBa": "22063318354",
      "TenKH": "PHAM HUNG DUNG",
      "GiaBieu": "11",
      "DinhMuc": 0.0,
      "Mean_6M": 154.67,
      "Std_6M": 170.94,
      "Alert_Level": 2
    },
    {
      "DanhBa": "22063312703",
      "TenKH": "NGUYEN THI HAT",
      "GiaBieu": "11",
      "DinhMuc": 0.0,
      "Mean_6M": 154.0,
      "Std_6M": 129.51,
      "Alert_Level": 2
    },
    {
      "DanhBa": "22073343380",
      "TenKH": "PHẠM NHẬT PHUONG7",
      "GiaBieu": "11",
      "DinhMuc": 0.0,
      "Mean_6M": 153.33,
      "Std_6M": 135.43,
      "Alert_Level": 2
    },
    {
      "DanhBa": "22063327714",
      "TenKH": "NGO TRUONG THI",
      "GiaBieu": "11",
      "DinhMuc": 232.0,
      "Mean_6M": 153.0,
      "Std_6M": 141.11,
      "Alert_Level": 2
    },
    {
      "DanhBa": "22063327575",
      "TenKH": "DO KIM ANH",
      "GiaBieu": "11",
      "DinhMuc": 0.0,
      "Mean_6M": 152.67,
      "Std_6M": 130.44,
      "Alert_Level": 2
    },
    {
      "DanhBa": "22073230425",
      "TenKH": "LAI VAN NGA",
      "GiaBieu": "11",
      "DinhMuc": 0.0,
      "Mean_6M": 150.5,
      "Std_6M": 173.28,
      "Alert_Level": 2
    },
    {
      "DanhBa": "22053298210",
      "TenKH": "CHUNG HOANG QUAN",
      "GiaBieu": "11",
      "DinhMuc": 16.0,
      "Mean_6M": 148.33,
      "Std_6M": 134.56,
      "Alert_Level": 2
    },
    {
      "DanhBa": "15092650035",
      "TenKH": "NGUYEN DUC HOA",
      "GiaBieu": "11",
      "DinhMuc": 0.0,
      "Mean_6M": 147.33,
      "Std_6M": 293.79,
      "Alert_Level": 2
    },
    {
      "DanhBa": "22053329425",
      "TenKH": "VU THI HUE",
      "GiaBieu": "11",
      "DinhMuc": 4.0,
      "Mean_6M": 147.0,
      "Std_6M": 171.28,
      "Alert_Level": 2
    },
    {
      "DanhBa": "22053323911",
      "TenKH": "NGUYEN CHIN",
      "GiaBieu": "11",
      "DinhMuc": 156.0,
      "Mean_6M": 146.83,
      "Std_6M": 139.79,
      "Alert_Level": 2
    },
    {
      "DanhBa": "15052171488",
      "TenKH": "LE CONG QUOC TUAN",
      "GiaBieu": "11",
      "DinhMuc": 60.0,
      "Mean_6M": 141.67,
      "Std_6M": 173.47,
      "Alert_Level": 2
    },
    {
      "DanhBa": "22063322839",
      "TenKH": "NGUYEN VAN GIOI",
      "GiaBieu": "11",
      "DinhMuc": 0.0,
      "Mean_6M": 141.33,
      "Std_6M": 176.98,
      "Alert_Level": 2
    },
    {
      "DanhBa": "15052171605",
      "TenKH": "TRẦN ĐỨC LONG",
      "GiaBieu": "11",
      "DinhMuc": 204.0,
      "Mean_6M": 140.67,
      "Std_6M": 153.73,
      "Alert_Level": 2
    },
    {
      "DanhBa": "22023240719",
      "TenKH": "HOANG HUU VAN",
      "GiaBieu": "11",
      "DinhMuc": 20.0,
      "Mean_6M": 138.0,
      "Std_6M": 310.74,
      "Alert_Level": 2
    },
    {
      "DanhBa": "22063324632",
      "TenKH": "VU HOANG LOAN",
      "GiaBieu": "11",
      "DinhMuc": 504.0,
      "Mean_6M": 137.17,
      "Std_6M": 156.66,
      "Alert_Level": 2
    },
    {
      "DanhBa": "22053322116",
      "TenKH": "PHAM THANH HOA",
      "GiaBieu": "11",
      "DinhMuc": 60.0,
      "Mean_6M": 135.0,
      "Std_6M": 196.44,
      "Alert_Level": 2
    },
    {
      "DanhBa": "15092647974",
      "TenKH": "NGUYEN VAN NAM",
      "GiaBieu": "11",
      "DinhMuc": 0.0,
      "Mean_6M": 133.5,
      "Std_6M": 262.18,
      "Alert_Level": 2
    },
    {
      "DanhBa": "15052171623",
      "TenKH": "LÊ DUY TỚI",
      "GiaBieu": "11",
      "DinhMuc": 0.0,
      "Mean_6M": 132.83,
      "Std_6M": 217.37,
      "Alert_Level": 2
    },
    {
      "DanhBa": "15052166522",
      "TenKH": "PHAN THIEN",
      "GiaBieu": "11",
      "DinhMuc": 0.0,
      "Mean_6M": 132.67,
      "Std_6M": 154.13,
      "Alert_Level": 2
    },
    {
      "DanhBa": "15102722241",
      "TenKH": "BUI SON BA",
      "GiaBieu": "11",
      "DinhMuc": 72.0,
      "Mean_6M": 129.33,
      "Std_6M": 173.87,
      "Alert_Level": 2
    },
    {
      "DanhBa": "15062139358",
      "TenKH": "NGUYEN TRI HUONG (DD 2 HO)",
      "GiaBieu": "11",
      "DinhMuc": 0.0,
      "Mean_6M": 128.0,
      "Std_6M": 284.31,
      "Alert_Level": 2
    },
    {
      "DanhBa": "22063325138",
      "TenKH": "TRAN QUANG LUAN",
      "GiaBieu": "11",
      "DinhMuc": 0.0,
      "Mean_6M": 127.0,
      "Std_6M": 159.75,
      "Alert_Level": 2
    },
    {
      "DanhBa": "22083350885",
      "TenKH": "TRAN THI NGOC NGA",
      "GiaBieu": "11",
      "DinhMuc": 0.0,
      "Mean_6M": 125.17,
      "Std_6M": 184.11,
      "Alert_Level": 2
    },
    {
      "DanhBa": "15042000630",
      "TenKH": "DO THI MINH HOA",
      "GiaBieu": "11",
      "DinhMuc": 0.0,
      "Mean_6M": 123.33,
      "Std_6M": 282.1,
      "Alert_Level": 2
    },
    {
      "DanhBa": "22033275303",
      "TenKH": "TRAN VAN LAM",
      "GiaBieu": "11",
      "DinhMuc": 16.0,
      "Mean_6M": 120.83,
      "Std_6M": 274.53,
      "Alert_Level": 2
    },
    {
      "DanhBa": "15052171489",
      "TenKH": "HUYNH XUAN NGA",
      "GiaBieu": "11",
      "DinhMuc": 0.0,
      "Mean_6M": 118.5,
      "Std_6M": 166.96,
      "Alert_Level": 2
    },
    {
      "DanhBa": "22083360972",
      "TenKH": "DO MANH SAU",
      "GiaBieu": "11",
      "DinhMuc": 16.0,
      "Mean_6M": 117.5,
      "Std_6M": 263.94,
      "Alert_Level": 2
    },
    {
      "DanhBa": "22113420276",
      "TenKH": "NGUYEN XOT",
      "GiaBieu": "11",
      "DinhMuc": 0.0,
      "Mean_6M": 109.83,
      "Std_6M": 267.08,
      "Alert_Level": 2
    },
    {
      "DanhBa": "15122888764",
      "TenKH": "NGUYEN XUAN BINH",
      "GiaBieu": "11",
      "DinhMuc": 24.0,
      "Mean_6M": 109.17,
      "Std_6M": 178.47,
      "Alert_Level": 2
    },
    {
      "DanhBa": "15141943901",
      "TenKH": "LE NGOC PHUONG",
      "GiaBieu": "11",
      "DinhMuc": 4.0,
      "Mean_6M": 107.5,
      "Std_6M": 221.45,
      "Alert_Level": 2
    },
    {
      "DanhBa": "15052161494",
      "TenKH": "DO THI KIM DUNG",
      "GiaBieu": "11",
      "DinhMuc": 132.0,
      "Mean_6M": 105.83,
      "Std_6M": 183.2,
      "Alert_Level": 2
    },
    {
      "DanhBa": "22043301936",
      "TenKH": "HUỲNH CÔNG THÀNH",
      "GiaBieu": "11",
      "DinhMuc": 0.0,
      "Mean_6M": 98.33,
      "Std_6M": 232.58,
      "Alert_Level": 2
    },
    {
      "DanhBa": "22063320692",
      "TenKH": "NGUYEN THI BE EM",
      "GiaBieu": "11",
      "DinhMuc": 0.0,
      "Mean_6M": 89.83,
      "Std_6M": 194.31,
      "Alert_Level": 2
    },
    {
      "DanhBa": "22083350386",
      "TenKH": "TRAN THI MY HOA",
      "GiaBieu": "11",
      "DinhMuc": 0.0,
      "Mean_6M": 87.67,
      "Std_6M": 206.48,
      "Alert_Level": 2
    },
    {
      "DanhBa": "15052171382",
      "TenKH": "LE THI ANH LINH",
      "GiaBieu": "11",
      "DinhMuc": 4.0,
      "Mean_6M": 148.5,
      "Std_6M": 124.82,
      "Alert_Level": 3
    },
    {
      "DanhBa": "22063325533",
      "TenKH": "LE NGUYEN MINH TUAN",
      "GiaBieu": "11",
      "DinhMuc": 4.0,
      "Mean_6M": 147.83,
      "Std_6M": 118.61,
      "Alert_Level": 3
    },
    {
      "DanhBa": "15062132424",
      "TenKH": "TRAN HUU TUAN",
      "GiaBieu": "11",
      "DinhMuc": 4.0,
      "Mean_6M": 146.83,
      "Std_6M": 117.56,
      "Alert_Level": 3
    },
    {
      "DanhBa": "15052170787",
      "TenKH": "NGUYEN THI THU",
      "GiaBieu": "11",
      "DinhMuc": 4.0,
      "Mean_6M": 135.33,
      "Std_6M": 125.16,
      "Alert_Level": 3
    },
    {
      "DanhBa": "22043320130",
      "TenKH": "NGUYEN THI HONG NHUNG",
      "GiaBieu": "11",
      "DinhMuc": 4.0,
      "Mean_6M": 127.5,
      "Std_6M": 129.2,
      "Alert_Level": 3
    },
    {
      "DanhBa": "15062138209",
      "TenKH": "NGUYEN THANH DUY",
      "GiaBieu": "11",
      "DinhMuc": 4.0,
      "Mean_6M": 125.33,
      "Std_6M": 103.77,
      "Alert_Level": 3
    },
    {
      "DanhBa": "15052171302",
      "TenKH": "NGUYEN CONG THAT",
      "GiaBieu": "11",
      "DinhMuc": 4.0,
      "Mean_6M": 125.0,
      "Std_6M": 98.31,
      "Alert_Level": 3
    },
    {
      "DanhBa": "22063319575",
      "TenKH": "TRAN THI THANH BINH",
      "GiaBieu": "11",
      "DinhMuc": 4.0,
      "Mean_6M": 120.17,
      "Std_6M": 93.33,
      "Alert_Level": 3
    },
    {
      "DanhBa": "22063324524",
      "TenKH": "NGUYEN CONG LE",
      "GiaBieu": "11",
      "DinhMuc": 4.0,
      "Mean_6M": 115.83,
      "Std_6M": 106.52,
      "Alert_Level": 3
    },
    {
      "DanhBa": "22043313316",
      "TenKH": "TRAN HUU PHI HUNG",
      "GiaBieu": "11",
      "DinhMuc": 4.0,
      "Mean_6M": 114.33,
      "Std_6M": 94.39,
      "Alert_Level": 3
    },
    {
      "DanhBa": "22063321998",
      "TenKH": "LUU HUYNH",
      "GiaBieu": "11",
      "DinhMuc": 4.0,
      "Mean_6M": 112.83,
      "Std_6M": 95.27,
      "Alert_Level": 3
    },
    {
      "DanhBa": "15052163110",
      "TenKH": "VAN CUONG",
      "GiaBieu": "11",
      "DinhMuc": 4.0,
      "Mean_6M": 111.5,
      "Std_6M": 87.55,
      "Alert_Level": 3
    },
    {
      "DanhBa": "22013221568",
      "TenKH": "DOAN HONG",
      "GiaBieu": "11",
      "DinhMuc": 4.0,
      "Mean_6M": 110.33,
      "Std_6M": 89.68,
      "Alert_Level": 3
    },
    {
      "DanhBa": "15141949210",
      "TenKH": "NGUYEN CONG HOAN",
      "GiaBieu": "11",
      "DinhMuc": 4.0,
      "Mean_6M": 105.0,
      "Std_6M": 82.59,
      "Alert_Level": 3
    },
    {
      "DanhBa": "22063314110",
      "TenKH": "VU TRONG QUY",
      "GiaBieu": "11",
      "DinhMuc": 4.0,
      "Mean_6M": 100.17,
      "Std_6M": 79.82,
      "Alert_Level": 3
    },
    {
      "DanhBa": "22053325796",
      "TenKH": "HUYNH TAN HUAN",
      "GiaBieu": "11",
      "DinhMuc": 4.0,
      "Mean_6M": 95.67,
      "Std_6M": 74.5,
      "Alert_Level": 3
    },
    {
      "DanhBa": "22043304402",
      "TenKH": "NGUYEN THI BAY",
      "GiaBieu": "11",
      "DinhMuc": 4.0,
      "Mean_6M": 93.17,
      "Std_6M": 73.01,
      "Alert_Level": 3
    },
    {
      "DanhBa": "22053326570",
      "TenKH": "NGUYEN VAN NHAN",
      "GiaBieu": "11",
      "DinhMuc": 4.0,
      "Mean_6M": 91.83,
      "Std_6M": 76.72,
      "Alert_Level": 3
    },
    {
      "DanhBa": "15031702419",
      "TenKH": "TA THI KIM DAN",
      "GiaBieu": "11",
      "DinhMuc": 4.0,
      "Mean_6M": 87.67,
      "Std_6M": 69.81,
      "Alert_Level": 3
    },
    {
      "DanhBa": "22103408736",
      "TenKH": "NGUYEN VAN HUONG",
      "GiaBieu": "11",
      "DinhMuc": 4.0,
      "Mean_6M": 87.17,
      "Std_6M": 69.12,
      "Alert_Level": 3
    },
    {
      "DanhBa": "15082510984",
      "TenKH": "DOAN THI CUC",
      "GiaBieu": "11",
      "DinhMuc": 4.0,
      "Mean_6M": 86.0,
      "Std_6M": 69.39,
      "Alert_Level": 3
    },
    {
      "DanhBa": "22063328390",
      "TenKH": "ĐINH CÔNG LUẬN",
      "GiaBieu": "11",
      "DinhMuc": 4.0,
      "Mean_6M": 86.0,
      "Std_6M": 91.68,
      "Alert_Level": 3
    },
    {
      "DanhBa": "22053292627",
      "TenKH": "TRAN THI LIEN",
      "GiaBieu": "11",
      "DinhMuc": 4.0,
      "Mean_6M": 84.83,
      "Std_6M": 122.72,
      "Alert_Level": 3
    },
    {
      "DanhBa": "15072428792",
      "TenKH": "LU QUOC TRUNG",
      "GiaBieu": "11",
      "DinhMuc": 4.0,
      "Mean_6M": 82.67,
      "Std_6M": 67.17,
      "Alert_Level": 3
    },
    {
      "DanhBa": "22063320103",
      "TenKH": "NGUYEN THI MONG DUYEN",
      "GiaBieu": "11",
      "DinhMuc": 4.0,
      "Mean_6M": 81.17,
      "Std_6M": 64.14,
      "Alert_Level": 3
    },
    {
      "DanhBa": "15082507310",
      "TenKH": "NGUYEN QUANG HUONG",
      "GiaBieu": "11",
      "DinhMuc": 4.0,
      "Mean_6M": 79.67,
      "Std_6M": 66.38,
      "Alert_Level": 3
    },
    {
      "DanhBa": "22063314603",
      "TenKH": "PHAM MINH PHUONG",
      "GiaBieu": "11",
      "DinhMuc": 4.0,
      "Mean_6M": 77.83,
      "Std_6M": 61.5,
      "Alert_Level": 3
    },
    {
      "DanhBa": "22063310700",
      "TenKH": "NGUYEN THI BE",
      "GiaBieu": "11",
      "DinhMuc": 4.0,
      "Mean_6M": 77.67,
      "Std_6M": 63.24,
      "Alert_Level": 3
    },
    {
      "DanhBa": "22063326343",
      "TenKH": "LE THIEN CUONG",
      "GiaBieu": "11",
      "DinhMuc": 4.0,
      "Mean_6M": 77.17,
      "Std_6M": 65.1,
      "Alert_Level": 3
    },
    {
      "DanhBa": "15062140993",
      "TenKH": "NGUYEN TRAN KHUONG",
      "GiaBieu": "11",
      "DinhMuc": 4.0,
      "Mean_6M": 75.17,
      "Std_6M": 62.59,
      "Alert_Level": 3
    },
    {
      "DanhBa": "15122845383",
      "TenKH": "DAO NGOC ANH",
      "GiaBieu": "11",
      "DinhMuc": 4.0,
      "Mean_6M": 74.5,
      "Std_6M": 66.1,
      "Alert_Level": 3
    },
    {
      "DanhBa": "22063327667",
      "TenKH": "TRAN VAN TUAN",
      "GiaBieu": "11",
      "DinhMuc": 4.0,
      "Mean_6M": 72.33,
      "Std_6M": 56.59,
      "Alert_Level": 3
    },
    {
      "DanhBa": "15161967017",
      "TenKH": "NGUYE QUANG THONG",
      "GiaBieu": "11",
      "DinhMuc": 4.0,
      "Mean_6M": 68.67,
      "Std_6M": 57.88,
      "Alert_Level": 3
    },
    {
      "DanhBa": "22043313218",
      "TenKH": "NGUYEN THANH THANH",
      "GiaBieu": "11",
      "DinhMuc": 4.0,
      "Mean_6M": 68.5,
      "Std_6M": 64.93,
      "Alert_Level": 3
    },
    {
      "DanhBa": "22063315713",
      "TenKH": "LE VAN GIAU",
      "GiaBieu": "11",
      "DinhMuc": 4.0,
      "Mean_6M": 68.33,
      "Std_6M": 53.11,
      "Alert_Level": 3
    },
    {
      "DanhBa": "22063324733",
      "TenKH": "LUU THI HOA",
      "GiaBieu": "11",
      "DinhMuc": 4.0,
      "Mean_6M": 67.67,
      "Std_6M": 54.84,
      "Alert_Level": 3
    },
    {
      "DanhBa": "15031720129",
      "TenKH": "NGUYEN KHAC THUONG THIEN AN",
      "GiaBieu": "11",
      "DinhMuc": 4.0,
      "Mean_6M": 66.67,
      "Std_6M": 59.8,
      "Alert_Level": 3
    },
    {
      "DanhBa": "22053328772",
      "TenKH": "NGO XUAN CANH",
      "GiaBieu": "11",
      "DinhMuc": 4.0,
      "Mean_6M": 65.67,
      "Std_6M": 54.5,
      "Alert_Level": 3
    },
    {
      "DanhBa": "22073341334",
      "TenKH": "TRAN THE HUY",
      "GiaBieu": "11",
      "DinhMuc": 4.0,
      "Mean_6M": 63.67,
      "Std_6M": 51.16,
      "Alert_Level": 3
    },
    {
      "DanhBa": "15031707389",
      "TenKH": "PHAN T THANH VAN",
      "GiaBieu": "11",
      "DinhMuc": 4.0,
      "Mean_6M": 63.33,
      "Std_6M": 49.16,
      "Alert_Level": 3
    },
    {
      "DanhBa": "15102728961",
      "TenKH": "TRAN QUANG NGUYEN",
      "GiaBieu": "11",
      "DinhMuc": 4.0,
      "Mean_6M": 63.0,
      "Std_6M": 49.72,
      "Alert_Level": 3
    },
    {
      "DanhBa": "22053329052",
      "TenKH": "VU MANH HUNG",
      "GiaBieu": "11",
      "DinhMuc": 4.0,
      "Mean_6M": 62.5,
      "Std_6M": 146.27,
      "Alert_Level": 3
    },
    {
      "DanhBa": "15072440795",
      "TenKH": "LE THI LE THU",
      "GiaBieu": "11",
      "DinhMuc": 4.0,
      "Mean_6M": 62.0,
      "Std_6M": 51.36,
      "Alert_Level": 3
    },
    {
      "DanhBa": "22063313356",
      "TenKH": "PHUNG VIET THUYET",
      "GiaBieu": "11",
      "DinhMuc": 4.0,
      "Mean_6M": 61.5,
      "Std_6M": 51.3,
      "Alert_Level": 3
    },
    {
      "DanhBa": "15031700868",
      "TenKH": "NGUYEN THI HOANG BIEN",
      "GiaBieu": "11",
      "DinhMuc": 4.0,
      "Mean_6M": 61.0,
      "Std_6M": 47.78,
      "Alert_Level": 3
    },
    {
      "DanhBa": "15042005280",
      "TenKH": "HOANG NU MINH SUONG",
      "GiaBieu": "11",
      "DinhMuc": 4.0,
      "Mean_6M": 61.0,
      "Std_6M": 48.29,
      "Alert_Level": 3
    },
    {
      "DanhBa": "22103398659",
      "TenKH": "LE DIEM PHUONG",
      "GiaBieu": "11",
      "DinhMuc": 4.0,
      "Mean_6M": 61.0,
      "Std_6M": 48.25,
      "Alert_Level": 3
    },
    {
      "DanhBa": "22093220201",
      "TenKH": "NGUYEN THI THU",
      "GiaBieu": "11",
      "DinhMuc": 4.0,
      "Mean_6M": 60.5,
      "Std_6M": 47.11,
      "Alert_Level": 3
    },
    {
      "DanhBa": "15072440572",
      "TenKH": "NGO THI HONG THAM",
      "GiaBieu": "11",
      "DinhMuc": 4.0,
      "Mean_6M": 59.5,
      "Std_6M": 50.07,
      "Alert_Level": 3
    },
    {
      "DanhBa": "15072460200",
      "TenKH": "NGUYEN VAN LIEM",
      "GiaBieu": "11",
      "DinhMuc": 4.0,
      "Mean_6M": 59.5,
      "Std_6M": 47.06,
      "Alert_Level": 3
    },
    {
      "DanhBa": "15052169725",
      "TenKH": "NGUYEN ANH TUAN",
      "GiaBieu": "11",
      "DinhMuc": 4.0,
      "Mean_6M": 59.17,
      "Std_6M": 51.61,
      "Alert_Level": 3
    },
    {
      "DanhBa": "15041908166",
      "TenKH": "NG HUYNH DANG",
      "GiaBieu": "11",
      "DinhMuc": 4.0,
      "Mean_6M": 58.83,
      "Std_6M": 49.35,
      "Alert_Level": 3
    },
    {
      "DanhBa": "15072426890",
      "TenKH": "PHAM HUU HOC",
      "GiaBieu": "11",
      "DinhMuc": 4.0,
      "Mean_6M": 58.5,
      "Std_6M": 47.14,
      "Alert_Level": 3
    },
    {
      "DanhBa": "22093375765",
      "TenKH": "VAN CONG AN",
      "GiaBieu": "11",
      "DinhMuc": 4.0,
      "Mean_6M": 58.17,
      "Std_6M": 48.93,
      "Alert_Level": 3
    },
    {
      "DanhBa": "22033271965",
      "TenKH": "HUYNH THI KIM HOANG",
      "GiaBieu": "11",
      "DinhMuc": 4.0,
      "Mean_6M": 57.33,
      "Std_6M": 44.83,
      "Alert_Level": 3
    },
    {
      "DanhBa": "22063327457",
      "TenKH": "DAO NGUYEN THUY ANH",
      "GiaBieu": "11",
      "DinhMuc": 4.0,
      "Mean_6M": 57.33,
      "Std_6M": 46.41,
      "Alert_Level": 3
    },
    {
      "DanhBa": "22023239221",
      "TenKH": "LE THANH LY",
      "GiaBieu": "11",
      "DinhMuc": 4.0,
      "Mean_6M": 56.67,
      "Std_6M": 44.26,
      "Alert_Level": 3
    },
    {
      "DanhBa": "22063327636",
      "TenKH": "NGUYEN NGOC NAM DAN",
      "GiaBieu": "11",
      "DinhMuc": 4.0,
      "Mean_6M": 56.0,
      "Std_6M": 44.63,
      "Alert_Level": 3
    },
    {
      "DanhBa": "15031710426",
      "TenKH": "PHAM NGOC PHUONG THAO",
      "GiaBieu": "11",
      "DinhMuc": 4.0,
      "Mean_6M": 55.67,
      "Std_6M": 43.41,
      "Alert_Level": 3
    },
    {
      "DanhBa": "15173430078",
      "TenKH": "TRAN NGUYEN HOANG VU",
      "GiaBieu": "11",
      "DinhMuc": 4.0,
      "Mean_6M": 55.0,
      "Std_6M": 43.03,
      "Alert_Level": 3
    },
    {
      "DanhBa": "22053324756",
      "TenKH": "NGUYEN THI DUNG",
      "GiaBieu": "11",
      "DinhMuc": 4.0,
      "Mean_6M": 54.5,
      "Std_6M": 42.76,
      "Alert_Level": 3
    },
    {
      "DanhBa": "22013222887",
      "TenKH": "HUYNH NGOC QUA",
      "GiaBieu": "11",
      "DinhMuc": 4.0,
      "Mean_6M": 54.33,
      "Std_6M": 64.87,
      "Alert_Level": 3
    },
    {
      "DanhBa": "22073343282",
      "TenKH": "HO THI NHAN",
      "GiaBieu": "11",
      "DinhMuc": 4.0,
      "Mean_6M": 54.0,
      "Std_6M": 57.99,
      "Alert_Level": 3
    },
    {
      "DanhBa": "15062141156",
      "TenKH": "NGUYEN QUANG THAO",
      "GiaBieu": "11",
      "DinhMuc": 4.0,
      "Mean_6M": 53.67,
      "Std_6M": 49.94,
      "Alert_Level": 3
    },
    {
      "DanhBa": "22063326032",
      "TenKH": "DANG VIET SANG",
      "GiaBieu": "11",
      "DinhMuc": 4.0,
      "Mean_6M": 53.5,
      "Std_6M": 48.32,
      "Alert_Level": 3
    },
    {
      "DanhBa": "22083365781",
      "TenKH": "NGUYEN THI THANH TUYEN",
      "GiaBieu": "11",
      "DinhMuc": 4.0,
      "Mean_6M": 53.17,
      "Std_6M": 45.09,
      "Alert_Level": 3
    },
    {
      "DanhBa": "22103390457",
      "TenKH": "LE THI MY LE",
      "GiaBieu": "11",
      "DinhMuc": 4.0,
      "Mean_6M": 53.0,
      "Std_6M": 41.76,
      "Alert_Level": 3
    },
    {
      "DanhBa": "15052121876",
      "TenKH": "PHAN THI THU LIEN",
      "GiaBieu": "11",
      "DinhMuc": 4.0,
      "Mean_6M": 51.83,
      "Std_6M": 41.33,
      "Alert_Level": 3
    },
    {
      "DanhBa": "15173422170",
      "TenKH": "NG QUANG NGOC (DD 5 HO)",
      "GiaBieu": "11",
      "DinhMuc": 4.0,
      "Mean_6M": 51.5,
      "Std_6M": 44.13,
      "Alert_Level": 3
    },
    {
      "DanhBa": "22043290253",
      "TenKH": "LE HAI DANG",
      "GiaBieu": "11",
      "DinhMuc": 4.0,
      "Mean_6M": 51.5,
      "Std_6M": 45.01,
      "Alert_Level": 3
    },
    {
      "DanhBa": "22053294122",
      "TenKH": "LE NGUYEN HUYNH TRANG",
      "GiaBieu": "11",
      "DinhMuc": 4.0,
      "Mean_6M": 50.17,
      "Std_6M": 39.66,
      "Alert_Level": 3
    }
  ]
};