// Auto-generated by fetch_tang_giam.js
const TAWACO_BIENDONG = {
  "lastUpdated": "08:32:13 20/4/2026",
  "nam": 2026,
  "ky": "04",
  "tongGieng": {
    "soKhachHangTang": 96927,
    "khoiLuongTang": 778652,
    "soKhachHangGiam": 85782,
    "khoiLuongGiam": 437702,
    "netChange": 340950
  },
  "chiTiet": [
    {
      "loai": "Sản xuất",
      "khachHangTang": 1458,
      "khoiLuongTang": 80167,
      "khachHangGiam": 650,
      "khoiLuongGiam": 26891
    },
    {
      "loai": "Hành chính",
      "khachHangTang": 5,
      "khoiLuongTang": 43,
      "khachHangGiam": 3,
      "khoiLuongGiam": 236
    },
    {
      "loai": "Dịch vụ",
      "khachHangTang": 123,
      "khoiLuongTang": 49598,
      "khachHangGiam": 31,
      "khoiLuongGiam": 13232
    },
    {
      "loai": "Sinh hoạt",
      "khachHangTang": 95341,
      "khoiLuongTang": 648844,
      "khachHangGiam": 85098,
      "khoiLuongGiam": 397343
    }
  ]
};
