// Auto-generated by fetch_tang_giam.js
const TAWACO_BIENDONG = {
  "lastUpdated": "11:00:41 7/4/2026",
  "nam": 2026,
  "ky": "04",
  "tongGieng": {
    "soKhachHangTang": 30617,
    "khoiLuongTang": 231237,
    "soKhachHangGiam": 26164,
    "khoiLuongGiam": 135168,
    "netChange": 96069
  },
  "chiTiet": [
    {
      "loai": "Sản xuất",
      "khachHangTang": 483,
      "khoiLuongTang": 21731,
      "khachHangGiam": 173,
      "khoiLuongGiam": 10213
    },
    {
      "loai": "Hành chính",
      "khachHangTang": 1,
      "khoiLuongTang": 6,
      "khachHangGiam": 0,
      "khoiLuongGiam": 0
    },
    {
      "loai": "Dịch vụ",
      "khachHangTang": 47,
      "khoiLuongTang": 18030,
      "khachHangGiam": 7,
      "khoiLuongGiam": 7580
    },
    {
      "loai": "Sinh hoạt",
      "khachHangTang": 30086,
      "khoiLuongTang": 191470,
      "khachHangGiam": 25984,
      "khoiLuongGiam": 117375
    }
  ]
};
