// Auto-generated by fetch_abnormal_data.js – 11:20:13 4/9/2026
// Nguồn: SANLUONGDONGHOKHACHHANG SQL Server 192.168.17.19
const TAWACO_BATTHUONG = {
  "lastUpdated": "11:20:13 4/9/2026",
  "nguonDuLieu": "SANLUONGDONGHOKHACHHANG – Kỳ 9 / Năm 2026",
  "nam": 2026,
  "ky": "9",
  "tongSoKH": 3,
  "leakCount": 0,
  "stuckCount": 0,
  "leakTop": [],
  "stuckTop": [],
  "nguong": {
    "roRiPct": ">300%",
    "roRiM3": ">15m³",
    "ketCoPct": ">75%",
    "ketCoM3": ">15m³"
  },
  "tienDo": {
    "tongDH": 246859,
    "daDoc": 3,
    "chuaDoc": 246856,
    "pct": 0
  }
};
