// Auto-generated by fetch_tang_giam.js
const TAWACO_BIENDONG = {
  "lastUpdated": "11:01:17 10/4/2026",
  "nam": 2026,
  "ky": "04",
  "tongGieng": {
    "soKhachHangTang": 47349,
    "khoiLuongTang": 354871,
    "soKhachHangGiam": 37534,
    "khoiLuongGiam": 185867,
    "netChange": 169004
  },
  "chiTiet": [
    {
      "loai": "Sản xuất",
      "khachHangTang": 707,
      "khoiLuongTang": 31386,
      "khachHangGiam": 265,
      "khoiLuongGiam": 13291
    },
    {
      "loai": "Hành chính",
      "khachHangTang": 1,
      "khoiLuongTang": 6,
      "khachHangGiam": 0,
      "khoiLuongGiam": 0
    },
    {
      "loai": "Dịch vụ",
      "khachHangTang": 82,
      "khoiLuongTang": 33877,
      "khachHangGiam": 16,
      "khoiLuongGiam": 9146
    },
    {
      "loai": "Sinh hoạt",
      "khachHangTang": 46559,
      "khoiLuongTang": 289602,
      "khachHangGiam": 37253,
      "khoiLuongGiam": 163430
    }
  ]
};
