// Auto-generated by fetch_abnormal_data.js – 11:20:13 10/9/2026
// Nguồn: SANLUONGDONGHOKHACHHANG SQL Server 192.168.17.19
const TAWACO_BATTHUONG = {
  "lastUpdated": "11:20:13 10/9/2026",
  "nguonDuLieu": "SANLUONGDONGHOKHACHHANG – Kỳ 9 / Năm 2026",
  "nam": 2026,
  "ky": "9",
  "tongSoKH": 86699,
  "leakCount": 311,
  "stuckCount": 349,
  "leakTop": [
    {
      "Danhba": "15112823314",
      "KyTruoc": 10,
      "KyHienTai": 1180,
      "KhoiLuongTang": 1170,
      "PhanTramTang": 11700
    },
    {
      "Danhba": "15062133721",
      "KyTruoc": 5,
      "KyHienTai": 663,
      "KhoiLuongTang": 658,
      "PhanTramTang": 13160
    },
    {
      "Danhba": "22103414165",
      "KyTruoc": 20,
      "KyHienTai": 434,
      "KhoiLuongTang": 414,
      "PhanTramTang": 2070
    },
    {
      "Danhba": "22073330738",
      "KyTruoc": 61,
      "KyHienTai": 412,
      "KhoiLuongTang": 351,
      "PhanTramTang": 575.4
    },
    {
      "Danhba": "15062137781",
      "KyTruoc": 78,
      "KyHienTai": 363,
      "KhoiLuongTang": 285,
      "PhanTramTang": 365.4
    },
    {
      "Danhba": "22033279852",
      "KyTruoc": 38,
      "KyHienTai": 275,
      "KhoiLuongTang": 237,
      "PhanTramTang": 623.7
    },
    {
      "Danhba": "15122886871",
      "KyTruoc": 61,
      "KyHienTai": 264,
      "KhoiLuongTang": 203,
      "PhanTramTang": 332.8
    },
    {
      "Danhba": "15072448355",
      "KyTruoc": 4,
      "KyHienTai": 205,
      "KhoiLuongTang": 201,
      "PhanTramTang": 5025
    },
    {
      "Danhba": "22103410449",
      "KyTruoc": 15,
      "KyHienTai": 208,
      "KhoiLuongTang": 193,
      "PhanTramTang": 1286.7
    },
    {
      "Danhba": "22073341859",
      "KyTruoc": 26,
      "KyHienTai": 217,
      "KhoiLuongTang": 191,
      "PhanTramTang": 734.6
    },
    {
      "Danhba": "22103413647",
      "KyTruoc": 37,
      "KyHienTai": 223,
      "KhoiLuongTang": 186,
      "PhanTramTang": 502.7
    },
    {
      "Danhba": "22043311402",
      "KyTruoc": 37,
      "KyHienTai": 212,
      "KhoiLuongTang": 175,
      "PhanTramTang": 473
    },
    {
      "Danhba": "22073230247",
      "KyTruoc": 1,
      "KyHienTai": 174,
      "KhoiLuongTang": 173,
      "PhanTramTang": 17300
    },
    {
      "Danhba": "22073239868",
      "KyTruoc": 20,
      "KyHienTai": 192,
      "KhoiLuongTang": 172,
      "PhanTramTang": 860
    },
    {
      "Danhba": "22073343455",
      "KyTruoc": 52,
      "KyHienTai": 219,
      "KhoiLuongTang": 167,
      "PhanTramTang": 321.2
    },
    {
      "Danhba": "22043290049",
      "KyTruoc": 16,
      "KyHienTai": 181,
      "KhoiLuongTang": 165,
      "PhanTramTang": 1031.3
    },
    {
      "Danhba": "15072425862",
      "KyTruoc": 42,
      "KyHienTai": 203,
      "KhoiLuongTang": 161,
      "PhanTramTang": 383.3
    },
    {
      "Danhba": "15062140674",
      "KyTruoc": 19,
      "KyHienTai": 173,
      "KhoiLuongTang": 154,
      "PhanTramTang": 810.5
    },
    {
      "Danhba": "15062136097",
      "KyTruoc": 14,
      "KyHienTai": 167,
      "KhoiLuongTang": 153,
      "PhanTramTang": 1092.9
    },
    {
      "Danhba": "15122891003",
      "KyTruoc": 13,
      "KyHienTai": 160,
      "KhoiLuongTang": 147,
      "PhanTramTang": 1130.8
    },
    {
      "Danhba": "22033278705",
      "KyTruoc": 23,
      "KyHienTai": 170,
      "KhoiLuongTang": 147,
      "PhanTramTang": 639.1
    },
    {
      "Danhba": "15122882415",
      "KyTruoc": 14,
      "KyHienTai": 159,
      "KhoiLuongTang": 145,
      "PhanTramTang": 1035.7
    },
    {
      "Danhba": "15112846132",
      "KyTruoc": 7,
      "KyHienTai": 148,
      "KhoiLuongTang": 141,
      "PhanTramTang": 2014.3
    },
    {
      "Danhba": "15122840224",
      "KyTruoc": 7,
      "KyHienTai": 144,
      "KhoiLuongTang": 137,
      "PhanTramTang": 1957.1
    },
    {
      "Danhba": "22073242049",
      "KyTruoc": 28,
      "KyHienTai": 164,
      "KhoiLuongTang": 136,
      "PhanTramTang": 485.7
    },
    {
      "Danhba": "22033276045",
      "KyTruoc": 34,
      "KyHienTai": 162,
      "KhoiLuongTang": 128,
      "PhanTramTang": 376.5
    },
    {
      "Danhba": "22043302633",
      "KyTruoc": 10,
      "KyHienTai": 138,
      "KhoiLuongTang": 128,
      "PhanTramTang": 1280
    },
    {
      "Danhba": "22043311370",
      "KyTruoc": 1,
      "KyHienTai": 128,
      "KhoiLuongTang": 127,
      "PhanTramTang": 12700
    },
    {
      "Danhba": "22033276408",
      "KyTruoc": 9,
      "KyHienTai": 135,
      "KhoiLuongTang": 126,
      "PhanTramTang": 1400
    },
    {
      "Danhba": "15102728450",
      "KyTruoc": 28,
      "KyHienTai": 154,
      "KhoiLuongTang": 126,
      "PhanTramTang": 450
    },
    {
      "Danhba": "15062134520",
      "KyTruoc": 16,
      "KyHienTai": 139,
      "KhoiLuongTang": 123,
      "PhanTramTang": 768.8
    },
    {
      "Danhba": "22043302000",
      "KyTruoc": 31,
      "KyHienTai": 152,
      "KhoiLuongTang": 121,
      "PhanTramTang": 390.3
    },
    {
      "Danhba": "22043278444",
      "KyTruoc": 22,
      "KyHienTai": 125,
      "KhoiLuongTang": 103,
      "PhanTramTang": 468.2
    },
    {
      "Danhba": "15112869005",
      "KyTruoc": 9,
      "KyHienTai": 111,
      "KhoiLuongTang": 102,
      "PhanTramTang": 1133.3
    },
    {
      "Danhba": "15112860919",
      "KyTruoc": 7,
      "KyHienTai": 104,
      "KhoiLuongTang": 97,
      "PhanTramTang": 1385.7
    },
    {
      "Danhba": "15112846341",
      "KyTruoc": 30,
      "KyHienTai": 124,
      "KhoiLuongTang": 94,
      "PhanTramTang": 313.3
    },
    {
      "Danhba": "22073343353",
      "KyTruoc": 21,
      "KyHienTai": 112,
      "KhoiLuongTang": 91,
      "PhanTramTang": 433.3
    },
    {
      "Danhba": "22033279678",
      "KyTruoc": 8,
      "KyHienTai": 95,
      "KhoiLuongTang": 87,
      "PhanTramTang": 1087.5
    },
    {
      "Danhba": "15112820988",
      "KyTruoc": 6,
      "KyHienTai": 93,
      "KhoiLuongTang": 87,
      "PhanTramTang": 1450
    },
    {
      "Danhba": "15042006723",
      "KyTruoc": 7,
      "KyHienTai": 90,
      "KhoiLuongTang": 83,
      "PhanTramTang": 1185.7
    },
    {
      "Danhba": "15141933100",
      "KyTruoc": 14,
      "KyHienTai": 91,
      "KhoiLuongTang": 77,
      "PhanTramTang": 550
    },
    {
      "Danhba": "15062137955",
      "KyTruoc": 6,
      "KyHienTai": 81,
      "KhoiLuongTang": 75,
      "PhanTramTang": 1250
    },
    {
      "Danhba": "22033273838",
      "KyTruoc": 2,
      "KyHienTai": 75,
      "KhoiLuongTang": 73,
      "PhanTramTang": 3650
    },
    {
      "Danhba": "22043301637",
      "KyTruoc": 9,
      "KyHienTai": 82,
      "KhoiLuongTang": 73,
      "PhanTramTang": 811.1
    },
    {
      "Danhba": "15112860061",
      "KyTruoc": 9,
      "KyHienTai": 80,
      "KhoiLuongTang": 71,
      "PhanTramTang": 788.9
    },
    {
      "Danhba": "22103395006",
      "KyTruoc": 16,
      "KyHienTai": 86,
      "KhoiLuongTang": 70,
      "PhanTramTang": 437.5
    },
    {
      "Danhba": "22033278978",
      "KyTruoc": 22,
      "KyHienTai": 91,
      "KhoiLuongTang": 69,
      "PhanTramTang": 313.6
    },
    {
      "Danhba": "22043314239",
      "KyTruoc": 1,
      "KyHienTai": 69,
      "KhoiLuongTang": 68,
      "PhanTramTang": 6800
    },
    {
      "Danhba": "22033332979",
      "KyTruoc": 21,
      "KyHienTai": 87,
      "KhoiLuongTang": 66,
      "PhanTramTang": 314.3
    },
    {
      "Danhba": "22073343238",
      "KyTruoc": 11,
      "KyHienTai": 75,
      "KhoiLuongTang": 64,
      "PhanTramTang": 581.8
    },
    {
      "Danhba": "15112829207",
      "KyTruoc": 17,
      "KyHienTai": 81,
      "KhoiLuongTang": 64,
      "PhanTramTang": 376.5
    },
    {
      "Danhba": "22103413127",
      "KyTruoc": 3,
      "KyHienTai": 66,
      "KhoiLuongTang": 63,
      "PhanTramTang": 2100
    },
    {
      "Danhba": "22103413852",
      "KyTruoc": 19,
      "KyHienTai": 80,
      "KhoiLuongTang": 61,
      "PhanTramTang": 321.1
    },
    {
      "Danhba": "15112860623",
      "KyTruoc": 10,
      "KyHienTai": 71,
      "KhoiLuongTang": 61,
      "PhanTramTang": 610
    },
    {
      "Danhba": "22043334359",
      "KyTruoc": 3,
      "KyHienTai": 64,
      "KhoiLuongTang": 61,
      "PhanTramTang": 2033.3
    },
    {
      "Danhba": "22033333355",
      "KyTruoc": 2,
      "KyHienTai": 62,
      "KhoiLuongTang": 60,
      "PhanTramTang": 3000
    },
    {
      "Danhba": "22033276990",
      "KyTruoc": 2,
      "KyHienTai": 61,
      "KhoiLuongTang": 59,
      "PhanTramTang": 2950
    },
    {
      "Danhba": "22043313151",
      "KyTruoc": 14,
      "KyHienTai": 73,
      "KhoiLuongTang": 59,
      "PhanTramTang": 421.4
    },
    {
      "Danhba": "15122841105",
      "KyTruoc": 6,
      "KyHienTai": 65,
      "KhoiLuongTang": 59,
      "PhanTramTang": 983.3
    },
    {
      "Danhba": "22033273079",
      "KyTruoc": 10,
      "KyHienTai": 67,
      "KhoiLuongTang": 57,
      "PhanTramTang": 570
    },
    {
      "Danhba": "15141939763",
      "KyTruoc": 16,
      "KyHienTai": 73,
      "KhoiLuongTang": 57,
      "PhanTramTang": 356.3
    },
    {
      "Danhba": "15141931440",
      "KyTruoc": 11,
      "KyHienTai": 68,
      "KhoiLuongTang": 57,
      "PhanTramTang": 518.2
    },
    {
      "Danhba": "22073238604",
      "KyTruoc": 5,
      "KyHienTai": 62,
      "KhoiLuongTang": 57,
      "PhanTramTang": 1140
    },
    {
      "Danhba": "22033333694",
      "KyTruoc": 17,
      "KyHienTai": 73,
      "KhoiLuongTang": 56,
      "PhanTramTang": 329.4
    },
    {
      "Danhba": "22033273894",
      "KyTruoc": 5,
      "KyHienTai": 61,
      "KhoiLuongTang": 56,
      "PhanTramTang": 1120
    },
    {
      "Danhba": "22033274830",
      "KyTruoc": 12,
      "KyHienTai": 67,
      "KhoiLuongTang": 55,
      "PhanTramTang": 458.3
    },
    {
      "Danhba": "15072428622",
      "KyTruoc": 11,
      "KyHienTai": 65,
      "KhoiLuongTang": 54,
      "PhanTramTang": 490.9
    },
    {
      "Danhba": "22043309606",
      "KyTruoc": 7,
      "KyHienTai": 61,
      "KhoiLuongTang": 54,
      "PhanTramTang": 771.4
    },
    {
      "Danhba": "22043313762",
      "KyTruoc": 12,
      "KyHienTai": 66,
      "KhoiLuongTang": 54,
      "PhanTramTang": 450
    },
    {
      "Danhba": "22033273967",
      "KyTruoc": 4,
      "KyHienTai": 57,
      "KhoiLuongTang": 53,
      "PhanTramTang": 1325
    },
    {
      "Danhba": "22103390731",
      "KyTruoc": 15,
      "KyHienTai": 67,
      "KhoiLuongTang": 52,
      "PhanTramTang": 346.7
    },
    {
      "Danhba": "22073342177",
      "KyTruoc": 1,
      "KyHienTai": 52,
      "KhoiLuongTang": 51,
      "PhanTramTang": 5100
    },
    {
      "Danhba": "15122881125",
      "KyTruoc": 8,
      "KyHienTai": 58,
      "KhoiLuongTang": 50,
      "PhanTramTang": 625
    },
    {
      "Danhba": "15102723584",
      "KyTruoc": 15,
      "KyHienTai": 65,
      "KhoiLuongTang": 50,
      "PhanTramTang": 333.3
    },
    {
      "Danhba": "15112821380",
      "KyTruoc": 6,
      "KyHienTai": 56,
      "KhoiLuongTang": 50,
      "PhanTramTang": 833.3
    },
    {
      "Danhba": "15122882488",
      "KyTruoc": 8,
      "KyHienTai": 57,
      "KhoiLuongTang": 49,
      "PhanTramTang": 612.5
    },
    {
      "Danhba": "15112823643",
      "KyTruoc": 4,
      "KyHienTai": 52,
      "KhoiLuongTang": 48,
      "PhanTramTang": 1200
    },
    {
      "Danhba": "22103400287",
      "KyTruoc": 3,
      "KyHienTai": 51,
      "KhoiLuongTang": 48,
      "PhanTramTang": 1600
    },
    {
      "Danhba": "15062138977",
      "KyTruoc": 1,
      "KyHienTai": 48,
      "KhoiLuongTang": 47,
      "PhanTramTang": 4700
    },
    {
      "Danhba": "22043290113",
      "KyTruoc": 9,
      "KyHienTai": 55,
      "KhoiLuongTang": 46,
      "PhanTramTang": 511.1
    },
    {
      "Danhba": "22033278709",
      "KyTruoc": 2,
      "KyHienTai": 48,
      "KhoiLuongTang": 46,
      "PhanTramTang": 2300
    },
    {
      "Danhba": "22103408658",
      "KyTruoc": 13,
      "KyHienTai": 58,
      "KhoiLuongTang": 45,
      "PhanTramTang": 346.2
    },
    {
      "Danhba": "22073239775",
      "KyTruoc": 5,
      "KyHienTai": 50,
      "KhoiLuongTang": 45,
      "PhanTramTang": 900
    },
    {
      "Danhba": "22073240187",
      "KyTruoc": 9,
      "KyHienTai": 54,
      "KhoiLuongTang": 45,
      "PhanTramTang": 500
    },
    {
      "Danhba": "15112846527",
      "KyTruoc": 1,
      "KyHienTai": 46,
      "KhoiLuongTang": 45,
      "PhanTramTang": 4500
    },
    {
      "Danhba": "15062131734",
      "KyTruoc": 9,
      "KyHienTai": 53,
      "KhoiLuongTang": 44,
      "PhanTramTang": 488.9
    },
    {
      "Danhba": "22033271177",
      "KyTruoc": 10,
      "KyHienTai": 54,
      "KhoiLuongTang": 44,
      "PhanTramTang": 440
    },
    {
      "Danhba": "22043334450",
      "KyTruoc": 7,
      "KyHienTai": 51,
      "KhoiLuongTang": 44,
      "PhanTramTang": 628.6
    },
    {
      "Danhba": "22043307650",
      "KyTruoc": 5,
      "KyHienTai": 48,
      "KhoiLuongTang": 43,
      "PhanTramTang": 860
    },
    {
      "Danhba": "15122844535",
      "KyTruoc": 1,
      "KyHienTai": 44,
      "KhoiLuongTang": 43,
      "PhanTramTang": 4300
    },
    {
      "Danhba": "15112869164",
      "KyTruoc": 1,
      "KyHienTai": 44,
      "KhoiLuongTang": 43,
      "PhanTramTang": 4300
    },
    {
      "Danhba": "15112829224",
      "KyTruoc": 1,
      "KyHienTai": 44,
      "KhoiLuongTang": 43,
      "PhanTramTang": 4300
    },
    {
      "Danhba": "22033275778",
      "KyTruoc": 7,
      "KyHienTai": 48,
      "KhoiLuongTang": 41,
      "PhanTramTang": 585.7
    },
    {
      "Danhba": "15122886680",
      "KyTruoc": 8,
      "KyHienTai": 48,
      "KhoiLuongTang": 40,
      "PhanTramTang": 500
    },
    {
      "Danhba": "15173420266",
      "KyTruoc": 7,
      "KyHienTai": 47,
      "KhoiLuongTang": 40,
      "PhanTramTang": 571.4
    },
    {
      "Danhba": "22103410116",
      "KyTruoc": 10,
      "KyHienTai": 50,
      "KhoiLuongTang": 40,
      "PhanTramTang": 400
    },
    {
      "Danhba": "15031746415",
      "KyTruoc": 12,
      "KyHienTai": 51,
      "KhoiLuongTang": 39,
      "PhanTramTang": 325
    },
    {
      "Danhba": "15062139999",
      "KyTruoc": 12,
      "KyHienTai": 49,
      "KhoiLuongTang": 37,
      "PhanTramTang": 308.3
    },
    {
      "Danhba": "15141939450",
      "KyTruoc": 12,
      "KyHienTai": 49,
      "KhoiLuongTang": 37,
      "PhanTramTang": 308.3
    },
    {
      "Danhba": "22043305288",
      "KyTruoc": 10,
      "KyHienTai": 47,
      "KhoiLuongTang": 37,
      "PhanTramTang": 370
    },
    {
      "Danhba": "22033275685",
      "KyTruoc": 9,
      "KyHienTai": 45,
      "KhoiLuongTang": 36,
      "PhanTramTang": 400
    },
    {
      "Danhba": "22033329703",
      "KyTruoc": 2,
      "KyHienTai": 38,
      "KhoiLuongTang": 36,
      "PhanTramTang": 1800
    },
    {
      "Danhba": "22043314549",
      "KyTruoc": 3,
      "KyHienTai": 39,
      "KhoiLuongTang": 36,
      "PhanTramTang": 1200
    },
    {
      "Danhba": "22103393399",
      "KyTruoc": 3,
      "KyHienTai": 39,
      "KhoiLuongTang": 36,
      "PhanTramTang": 1200
    },
    {
      "Danhba": "22043313490",
      "KyTruoc": 5,
      "KyHienTai": 40,
      "KhoiLuongTang": 35,
      "PhanTramTang": 700
    },
    {
      "Danhba": "22043305949",
      "KyTruoc": 1,
      "KyHienTai": 36,
      "KhoiLuongTang": 35,
      "PhanTramTang": 3500
    },
    {
      "Danhba": "15122890812",
      "KyTruoc": 7,
      "KyHienTai": 42,
      "KhoiLuongTang": 35,
      "PhanTramTang": 500
    },
    {
      "Danhba": "15122841511",
      "KyTruoc": 4,
      "KyHienTai": 39,
      "KhoiLuongTang": 35,
      "PhanTramTang": 875
    },
    {
      "Danhba": "15122861931",
      "KyTruoc": 4,
      "KyHienTai": 39,
      "KhoiLuongTang": 35,
      "PhanTramTang": 875
    },
    {
      "Danhba": "15112846555",
      "KyTruoc": 7,
      "KyHienTai": 42,
      "KhoiLuongTang": 35,
      "PhanTramTang": 500
    },
    {
      "Danhba": "15122885681",
      "KyTruoc": 5,
      "KyHienTai": 39,
      "KhoiLuongTang": 34,
      "PhanTramTang": 680
    },
    {
      "Danhba": "15122890853",
      "KyTruoc": 10,
      "KyHienTai": 44,
      "KhoiLuongTang": 34,
      "PhanTramTang": 340
    },
    {
      "Danhba": "22033332485",
      "KyTruoc": 10,
      "KyHienTai": 44,
      "KhoiLuongTang": 34,
      "PhanTramTang": 340
    },
    {
      "Danhba": "22033279707",
      "KyTruoc": 8,
      "KyHienTai": 42,
      "KhoiLuongTang": 34,
      "PhanTramTang": 425
    },
    {
      "Danhba": "22073241161",
      "KyTruoc": 3,
      "KyHienTai": 36,
      "KhoiLuongTang": 33,
      "PhanTramTang": 1100
    },
    {
      "Danhba": "22073343497",
      "KyTruoc": 4,
      "KyHienTai": 37,
      "KhoiLuongTang": 33,
      "PhanTramTang": 825
    },
    {
      "Danhba": "15112822047",
      "KyTruoc": 5,
      "KyHienTai": 38,
      "KhoiLuongTang": 33,
      "PhanTramTang": 660
    },
    {
      "Danhba": "15062135040",
      "KyTruoc": 2,
      "KyHienTai": 35,
      "KhoiLuongTang": 33,
      "PhanTramTang": 1650
    },
    {
      "Danhba": "15062136682",
      "KyTruoc": 1,
      "KyHienTai": 34,
      "KhoiLuongTang": 33,
      "PhanTramTang": 3300
    },
    {
      "Danhba": "15062140658",
      "KyTruoc": 10,
      "KyHienTai": 42,
      "KhoiLuongTang": 32,
      "PhanTramTang": 320
    },
    {
      "Danhba": "15041921445",
      "KyTruoc": 1,
      "KyHienTai": 33,
      "KhoiLuongTang": 32,
      "PhanTramTang": 3200
    },
    {
      "Danhba": "15112822705",
      "KyTruoc": 1,
      "KyHienTai": 33,
      "KhoiLuongTang": 32,
      "PhanTramTang": 3200
    },
    {
      "Danhba": "22073242269",
      "KyTruoc": 4,
      "KyHienTai": 36,
      "KhoiLuongTang": 32,
      "PhanTramTang": 800
    },
    {
      "Danhba": "22033276035",
      "KyTruoc": 1,
      "KyHienTai": 33,
      "KhoiLuongTang": 32,
      "PhanTramTang": 3200
    },
    {
      "Danhba": "22043311439",
      "KyTruoc": 8,
      "KyHienTai": 40,
      "KhoiLuongTang": 32,
      "PhanTramTang": 400
    },
    {
      "Danhba": "22043300516",
      "KyTruoc": 10,
      "KyHienTai": 42,
      "KhoiLuongTang": 32,
      "PhanTramTang": 320
    },
    {
      "Danhba": "22043314434",
      "KyTruoc": 5,
      "KyHienTai": 36,
      "KhoiLuongTang": 31,
      "PhanTramTang": 620
    },
    {
      "Danhba": "15072440609",
      "KyTruoc": 9,
      "KyHienTai": 40,
      "KhoiLuongTang": 31,
      "PhanTramTang": 344.4
    },
    {
      "Danhba": "22033250618",
      "KyTruoc": 2,
      "KyHienTai": 33,
      "KhoiLuongTang": 31,
      "PhanTramTang": 1550
    },
    {
      "Danhba": "15122860754",
      "KyTruoc": 4,
      "KyHienTai": 34,
      "KhoiLuongTang": 30,
      "PhanTramTang": 750
    },
    {
      "Danhba": "15122887812",
      "KyTruoc": 4,
      "KyHienTai": 33,
      "KhoiLuongTang": 29,
      "PhanTramTang": 725
    },
    {
      "Danhba": "15112829167",
      "KyTruoc": 6,
      "KyHienTai": 35,
      "KhoiLuongTang": 29,
      "PhanTramTang": 483.3
    },
    {
      "Danhba": "22073330018",
      "KyTruoc": 7,
      "KyHienTai": 36,
      "KhoiLuongTang": 29,
      "PhanTramTang": 414.3
    },
    {
      "Danhba": "22073342798",
      "KyTruoc": 2,
      "KyHienTai": 31,
      "KhoiLuongTang": 29,
      "PhanTramTang": 1450
    },
    {
      "Danhba": "22103390421",
      "KyTruoc": 4,
      "KyHienTai": 33,
      "KhoiLuongTang": 29,
      "PhanTramTang": 725
    },
    {
      "Danhba": "22073343494",
      "KyTruoc": 4,
      "KyHienTai": 33,
      "KhoiLuongTang": 29,
      "PhanTramTang": 725
    },
    {
      "Danhba": "22043314302",
      "KyTruoc": 3,
      "KyHienTai": 31,
      "KhoiLuongTang": 28,
      "PhanTramTang": 933.3
    },
    {
      "Danhba": "22073230257",
      "KyTruoc": 8,
      "KyHienTai": 36,
      "KhoiLuongTang": 28,
      "PhanTramTang": 350
    },
    {
      "Danhba": "22073231132",
      "KyTruoc": 2,
      "KyHienTai": 30,
      "KhoiLuongTang": 28,
      "PhanTramTang": 1400
    },
    {
      "Danhba": "22033328205",
      "KyTruoc": 2,
      "KyHienTai": 30,
      "KhoiLuongTang": 28,
      "PhanTramTang": 1400
    },
    {
      "Danhba": "15102723302",
      "KyTruoc": 6,
      "KyHienTai": 34,
      "KhoiLuongTang": 28,
      "PhanTramTang": 466.7
    },
    {
      "Danhba": "15072420024",
      "KyTruoc": 1,
      "KyHienTai": 29,
      "KhoiLuongTang": 28,
      "PhanTramTang": 2800
    },
    {
      "Danhba": "15122888294",
      "KyTruoc": 1,
      "KyHienTai": 29,
      "KhoiLuongTang": 28,
      "PhanTramTang": 2800
    },
    {
      "Danhba": "22033270393",
      "KyTruoc": 1,
      "KyHienTai": 29,
      "KhoiLuongTang": 28,
      "PhanTramTang": 2800
    },
    {
      "Danhba": "22033275129",
      "KyTruoc": 9,
      "KyHienTai": 37,
      "KhoiLuongTang": 28,
      "PhanTramTang": 311.1
    },
    {
      "Danhba": "22033272577",
      "KyTruoc": 5,
      "KyHienTai": 32,
      "KhoiLuongTang": 27,
      "PhanTramTang": 540
    },
    {
      "Danhba": "15122883549",
      "KyTruoc": 8,
      "KyHienTai": 35,
      "KhoiLuongTang": 27,
      "PhanTramTang": 337.5
    },
    {
      "Danhba": "22033331769",
      "KyTruoc": 6,
      "KyHienTai": 33,
      "KhoiLuongTang": 27,
      "PhanTramTang": 450
    },
    {
      "Danhba": "22043310624",
      "KyTruoc": 2,
      "KyHienTai": 29,
      "KhoiLuongTang": 27,
      "PhanTramTang": 1350
    },
    {
      "Danhba": "22043308868",
      "KyTruoc": 6,
      "KyHienTai": 33,
      "KhoiLuongTang": 27,
      "PhanTramTang": 450
    },
    {
      "Danhba": "22073241264",
      "KyTruoc": 1,
      "KyHienTai": 28,
      "KhoiLuongTang": 27,
      "PhanTramTang": 2700
    },
    {
      "Danhba": "22073239925",
      "KyTruoc": 6,
      "KyHienTai": 33,
      "KhoiLuongTang": 27,
      "PhanTramTang": 450
    },
    {
      "Danhba": "22043320171",
      "KyTruoc": 8,
      "KyHienTai": 35,
      "KhoiLuongTang": 27,
      "PhanTramTang": 337.5
    },
    {
      "Danhba": "22103390869",
      "KyTruoc": 2,
      "KyHienTai": 29,
      "KhoiLuongTang": 27,
      "PhanTramTang": 1350
    },
    {
      "Danhba": "22073330321",
      "KyTruoc": 1,
      "KyHienTai": 28,
      "KhoiLuongTang": 27,
      "PhanTramTang": 2700
    },
    {
      "Danhba": "22103413509",
      "KyTruoc": 2,
      "KyHienTai": 29,
      "KhoiLuongTang": 27,
      "PhanTramTang": 1350
    },
    {
      "Danhba": "22103414150",
      "KyTruoc": 6,
      "KyHienTai": 32,
      "KhoiLuongTang": 26,
      "PhanTramTang": 433.3
    },
    {
      "Danhba": "22103408451",
      "KyTruoc": 6,
      "KyHienTai": 32,
      "KhoiLuongTang": 26,
      "PhanTramTang": 433.3
    },
    {
      "Danhba": "22033276881",
      "KyTruoc": 1,
      "KyHienTai": 27,
      "KhoiLuongTang": 26,
      "PhanTramTang": 2600
    },
    {
      "Danhba": "22033279173",
      "KyTruoc": 4,
      "KyHienTai": 30,
      "KhoiLuongTang": 26,
      "PhanTramTang": 650
    },
    {
      "Danhba": "15122884704",
      "KyTruoc": 4,
      "KyHienTai": 30,
      "KhoiLuongTang": 26,
      "PhanTramTang": 650
    },
    {
      "Danhba": "22033270157",
      "KyTruoc": 1,
      "KyHienTai": 27,
      "KhoiLuongTang": 26,
      "PhanTramTang": 2600
    },
    {
      "Danhba": "15141932464",
      "KyTruoc": 8,
      "KyHienTai": 34,
      "KhoiLuongTang": 26,
      "PhanTramTang": 325
    },
    {
      "Danhba": "15062140931",
      "KyTruoc": 7,
      "KyHienTai": 33,
      "KhoiLuongTang": 26,
      "PhanTramTang": 371.4
    },
    {
      "Danhba": "15072468217",
      "KyTruoc": 5,
      "KyHienTai": 31,
      "KhoiLuongTang": 26,
      "PhanTramTang": 520
    },
    {
      "Danhba": "15062135348",
      "KyTruoc": 1,
      "KyHienTai": 27,
      "KhoiLuongTang": 26,
      "PhanTramTang": 2600
    },
    {
      "Danhba": "15072441292",
      "KyTruoc": 1,
      "KyHienTai": 26,
      "KhoiLuongTang": 25,
      "PhanTramTang": 2500
    },
    {
      "Danhba": "15112822851",
      "KyTruoc": 5,
      "KyHienTai": 30,
      "KhoiLuongTang": 25,
      "PhanTramTang": 500
    },
    {
      "Danhba": "15112823663",
      "KyTruoc": 8,
      "KyHienTai": 33,
      "KhoiLuongTang": 25,
      "PhanTramTang": 312.5
    },
    {
      "Danhba": "15141931962",
      "KyTruoc": 6,
      "KyHienTai": 31,
      "KhoiLuongTang": 25,
      "PhanTramTang": 416.7
    },
    {
      "Danhba": "22033274303",
      "KyTruoc": 4,
      "KyHienTai": 29,
      "KhoiLuongTang": 25,
      "PhanTramTang": 625
    },
    {
      "Danhba": "15122862685",
      "KyTruoc": 5,
      "KyHienTai": 30,
      "KhoiLuongTang": 25,
      "PhanTramTang": 500
    },
    {
      "Danhba": "22033333063",
      "KyTruoc": 5,
      "KyHienTai": 30,
      "KhoiLuongTang": 25,
      "PhanTramTang": 500
    },
    {
      "Danhba": "22043307303",
      "KyTruoc": 2,
      "KyHienTai": 27,
      "KhoiLuongTang": 25,
      "PhanTramTang": 1250
    },
    {
      "Danhba": "22043314498",
      "KyTruoc": 2,
      "KyHienTai": 27,
      "KhoiLuongTang": 25,
      "PhanTramTang": 1250
    },
    {
      "Danhba": "22073241455",
      "KyTruoc": 6,
      "KyHienTai": 31,
      "KhoiLuongTang": 25,
      "PhanTramTang": 416.7
    },
    {
      "Danhba": "22073240290",
      "KyTruoc": 4,
      "KyHienTai": 28,
      "KhoiLuongTang": 24,
      "PhanTramTang": 600
    },
    {
      "Danhba": "22073340905",
      "KyTruoc": 1,
      "KyHienTai": 25,
      "KhoiLuongTang": 24,
      "PhanTramTang": 2400
    },
    {
      "Danhba": "22043303747",
      "KyTruoc": 4,
      "KyHienTai": 28,
      "KhoiLuongTang": 24,
      "PhanTramTang": 600
    },
    {
      "Danhba": "22043304803",
      "KyTruoc": 2,
      "KyHienTai": 26,
      "KhoiLuongTang": 24,
      "PhanTramTang": 1200
    },
    {
      "Danhba": "22033276407",
      "KyTruoc": 2,
      "KyHienTai": 26,
      "KhoiLuongTang": 24,
      "PhanTramTang": 1200
    },
    {
      "Danhba": "15122884819",
      "KyTruoc": 1,
      "KyHienTai": 25,
      "KhoiLuongTang": 24,
      "PhanTramTang": 2400
    },
    {
      "Danhba": "15141931650",
      "KyTruoc": 5,
      "KyHienTai": 29,
      "KhoiLuongTang": 24,
      "PhanTramTang": 480
    },
    {
      "Danhba": "15092621831",
      "KyTruoc": 4,
      "KyHienTai": 28,
      "KhoiLuongTang": 24,
      "PhanTramTang": 600
    },
    {
      "Danhba": "22103412978",
      "KyTruoc": 3,
      "KyHienTai": 27,
      "KhoiLuongTang": 24,
      "PhanTramTang": 800
    },
    {
      "Danhba": "22103411294",
      "KyTruoc": 3,
      "KyHienTai": 26,
      "KhoiLuongTang": 23,
      "PhanTramTang": 766.7
    },
    {
      "Danhba": "15112825144",
      "KyTruoc": 4,
      "KyHienTai": 27,
      "KhoiLuongTang": 23,
      "PhanTramTang": 575
    },
    {
      "Danhba": "15112828870",
      "KyTruoc": 5,
      "KyHienTai": 28,
      "KhoiLuongTang": 23,
      "PhanTramTang": 460
    },
    {
      "Danhba": "15122883067",
      "KyTruoc": 7,
      "KyHienTai": 30,
      "KhoiLuongTang": 23,
      "PhanTramTang": 328.6
    },
    {
      "Danhba": "22033279043",
      "KyTruoc": 6,
      "KyHienTai": 29,
      "KhoiLuongTang": 23,
      "PhanTramTang": 383.3
    },
    {
      "Danhba": "22033333163",
      "KyTruoc": 3,
      "KyHienTai": 26,
      "KhoiLuongTang": 23,
      "PhanTramTang": 766.7
    },
    {
      "Danhba": "22043306278",
      "KyTruoc": 2,
      "KyHienTai": 25,
      "KhoiLuongTang": 23,
      "PhanTramTang": 1150
    },
    {
      "Danhba": "22073342605",
      "KyTruoc": 6,
      "KyHienTai": 29,
      "KhoiLuongTang": 23,
      "PhanTramTang": 383.3
    },
    {
      "Danhba": "22103390963",
      "KyTruoc": 2,
      "KyHienTai": 24,
      "KhoiLuongTang": 22,
      "PhanTramTang": 1100
    },
    {
      "Danhba": "22043278209",
      "KyTruoc": 5,
      "KyHienTai": 27,
      "KhoiLuongTang": 22,
      "PhanTramTang": 440
    },
    {
      "Danhba": "22033278959",
      "KyTruoc": 5,
      "KyHienTai": 27,
      "KhoiLuongTang": 22,
      "PhanTramTang": 440
    },
    {
      "Danhba": "22033272831",
      "KyTruoc": 6,
      "KyHienTai": 28,
      "KhoiLuongTang": 22,
      "PhanTramTang": 366.7
    },
    {
      "Danhba": "22033258551",
      "KyTruoc": 3,
      "KyHienTai": 25,
      "KhoiLuongTang": 22,
      "PhanTramTang": 733.3
    },
    {
      "Danhba": "15112840280",
      "KyTruoc": 3,
      "KyHienTai": 25,
      "KhoiLuongTang": 22,
      "PhanTramTang": 733.3
    },
    {
      "Danhba": "15102721177",
      "KyTruoc": 1,
      "KyHienTai": 23,
      "KhoiLuongTang": 22,
      "PhanTramTang": 2200
    },
    {
      "Danhba": "15062138174",
      "KyTruoc": 3,
      "KyHienTai": 25,
      "KhoiLuongTang": 22,
      "PhanTramTang": 733.3
    },
    {
      "Danhba": "15062140549",
      "KyTruoc": 3,
      "KyHienTai": 24,
      "KhoiLuongTang": 21,
      "PhanTramTang": 700
    },
    {
      "Danhba": "22033252480",
      "KyTruoc": 6,
      "KyHienTai": 27,
      "KhoiLuongTang": 21,
      "PhanTramTang": 350
    },
    {
      "Danhba": "15141932746",
      "KyTruoc": 1,
      "KyHienTai": 22,
      "KhoiLuongTang": 21,
      "PhanTramTang": 2100
    },
    {
      "Danhba": "15122880672",
      "KyTruoc": 3,
      "KyHienTai": 24,
      "KhoiLuongTang": 21,
      "PhanTramTang": 700
    },
    {
      "Danhba": "15122890470",
      "KyTruoc": 5,
      "KyHienTai": 26,
      "KhoiLuongTang": 21,
      "PhanTramTang": 420
    },
    {
      "Danhba": "22033279240",
      "KyTruoc": 4,
      "KyHienTai": 25,
      "KhoiLuongTang": 21,
      "PhanTramTang": 525
    },
    {
      "Danhba": "22043306941",
      "KyTruoc": 3,
      "KyHienTai": 24,
      "KhoiLuongTang": 21,
      "PhanTramTang": 700
    },
    {
      "Danhba": "22043305528",
      "KyTruoc": 2,
      "KyHienTai": 23,
      "KhoiLuongTang": 21,
      "PhanTramTang": 1050
    },
    {
      "Danhba": "22103401043",
      "KyTruoc": 5,
      "KyHienTai": 26,
      "KhoiLuongTang": 21,
      "PhanTramTang": 420
    },
    {
      "Danhba": "22073240083",
      "KyTruoc": 1,
      "KyHienTai": 22,
      "KhoiLuongTang": 21,
      "PhanTramTang": 2100
    },
    {
      "Danhba": "22073330741",
      "KyTruoc": 3,
      "KyHienTai": 24,
      "KhoiLuongTang": 21,
      "PhanTramTang": 700
    },
    {
      "Danhba": "22043334396",
      "KyTruoc": 5,
      "KyHienTai": 26,
      "KhoiLuongTang": 21,
      "PhanTramTang": 420
    },
    {
      "Danhba": "22043314227",
      "KyTruoc": 1,
      "KyHienTai": 22,
      "KhoiLuongTang": 21,
      "PhanTramTang": 2100
    },
    {
      "Danhba": "22073342645",
      "KyTruoc": 1,
      "KyHienTai": 21,
      "KhoiLuongTang": 20,
      "PhanTramTang": 2000
    },
    {
      "Danhba": "22073342251",
      "KyTruoc": 2,
      "KyHienTai": 22,
      "KhoiLuongTang": 20,
      "PhanTramTang": 1000
    },
    {
      "Danhba": "22103399852",
      "KyTruoc": 4,
      "KyHienTai": 24,
      "KhoiLuongTang": 20,
      "PhanTramTang": 500
    },
    {
      "Danhba": "22043305810",
      "KyTruoc": 3,
      "KyHienTai": 23,
      "KhoiLuongTang": 20,
      "PhanTramTang": 666.7
    },
    {
      "Danhba": "22043301854",
      "KyTruoc": 5,
      "KyHienTai": 25,
      "KhoiLuongTang": 20,
      "PhanTramTang": 400
    },
    {
      "Danhba": "22033332157",
      "KyTruoc": 5,
      "KyHienTai": 25,
      "KhoiLuongTang": 20,
      "PhanTramTang": 400
    },
    {
      "Danhba": "22033279951",
      "KyTruoc": 4,
      "KyHienTai": 24,
      "KhoiLuongTang": 20,
      "PhanTramTang": 500
    },
    {
      "Danhba": "22033330228",
      "KyTruoc": 4,
      "KyHienTai": 24,
      "KhoiLuongTang": 20,
      "PhanTramTang": 500
    },
    {
      "Danhba": "15122890836",
      "KyTruoc": 4,
      "KyHienTai": 24,
      "KhoiLuongTang": 20,
      "PhanTramTang": 500
    },
    {
      "Danhba": "15141930626",
      "KyTruoc": 1,
      "KyHienTai": 21,
      "KhoiLuongTang": 20,
      "PhanTramTang": 2000
    },
    {
      "Danhba": "22033270476",
      "KyTruoc": 2,
      "KyHienTai": 22,
      "KhoiLuongTang": 20,
      "PhanTramTang": 1000
    },
    {
      "Danhba": "22033260850",
      "KyTruoc": 5,
      "KyHienTai": 25,
      "KhoiLuongTang": 20,
      "PhanTramTang": 400
    },
    {
      "Danhba": "15062138203",
      "KyTruoc": 1,
      "KyHienTai": 21,
      "KhoiLuongTang": 20,
      "PhanTramTang": 2000
    },
    {
      "Danhba": "15062136184",
      "KyTruoc": 1,
      "KyHienTai": 21,
      "KhoiLuongTang": 20,
      "PhanTramTang": 2000
    },
    {
      "Danhba": "15062135412",
      "KyTruoc": 1,
      "KyHienTai": 21,
      "KhoiLuongTang": 20,
      "PhanTramTang": 2000
    },
    {
      "Danhba": "15112828751",
      "KyTruoc": 1,
      "KyHienTai": 21,
      "KhoiLuongTang": 20,
      "PhanTramTang": 2000
    },
    {
      "Danhba": "22103413497",
      "KyTruoc": 3,
      "KyHienTai": 23,
      "KhoiLuongTang": 20,
      "PhanTramTang": 666.7
    },
    {
      "Danhba": "22103413556",
      "KyTruoc": 2,
      "KyHienTai": 21,
      "KhoiLuongTang": 19,
      "PhanTramTang": 950
    },
    {
      "Danhba": "22103412296",
      "KyTruoc": 3,
      "KyHienTai": 22,
      "KhoiLuongTang": 19,
      "PhanTramTang": 633.3
    },
    {
      "Danhba": "15112828744",
      "KyTruoc": 3,
      "KyHienTai": 22,
      "KhoiLuongTang": 19,
      "PhanTramTang": 633.3
    },
    {
      "Danhba": "15112865554",
      "KyTruoc": 6,
      "KyHienTai": 25,
      "KhoiLuongTang": 19,
      "PhanTramTang": 316.7
    },
    {
      "Danhba": "15102723317",
      "KyTruoc": 6,
      "KyHienTai": 25,
      "KhoiLuongTang": 19,
      "PhanTramTang": 316.7
    },
    {
      "Danhba": "15072481072",
      "KyTruoc": 3,
      "KyHienTai": 22,
      "KhoiLuongTang": 19,
      "PhanTramTang": 633.3
    },
    {
      "Danhba": "15173422121",
      "KyTruoc": 5,
      "KyHienTai": 24,
      "KhoiLuongTang": 19,
      "PhanTramTang": 380
    },
    {
      "Danhba": "15122890477",
      "KyTruoc": 3,
      "KyHienTai": 22,
      "KhoiLuongTang": 19,
      "PhanTramTang": 633.3
    },
    {
      "Danhba": "15122890075",
      "KyTruoc": 3,
      "KyHienTai": 22,
      "KhoiLuongTang": 19,
      "PhanTramTang": 633.3
    },
    {
      "Danhba": "15122844996",
      "KyTruoc": 3,
      "KyHienTai": 22,
      "KhoiLuongTang": 19,
      "PhanTramTang": 633.3
    },
    {
      "Danhba": "22033330337",
      "KyTruoc": 3,
      "KyHienTai": 22,
      "KhoiLuongTang": 19,
      "PhanTramTang": 633.3
    },
    {
      "Danhba": "22043300982",
      "KyTruoc": 1,
      "KyHienTai": 20,
      "KhoiLuongTang": 19,
      "PhanTramTang": 1900
    },
    {
      "Danhba": "22043306176",
      "KyTruoc": 4,
      "KyHienTai": 23,
      "KhoiLuongTang": 19,
      "PhanTramTang": 475
    },
    {
      "Danhba": "22043308560",
      "KyTruoc": 1,
      "KyHienTai": 20,
      "KhoiLuongTang": 19,
      "PhanTramTang": 1900
    },
    {
      "Danhba": "22043334364",
      "KyTruoc": 6,
      "KyHienTai": 25,
      "KhoiLuongTang": 19,
      "PhanTramTang": 316.7
    },
    {
      "Danhba": "22043334346",
      "KyTruoc": 5,
      "KyHienTai": 23,
      "KhoiLuongTang": 18,
      "PhanTramTang": 360
    },
    {
      "Danhba": "22043314310",
      "KyTruoc": 1,
      "KyHienTai": 19,
      "KhoiLuongTang": 18,
      "PhanTramTang": 1800
    },
    {
      "Danhba": "22103398858",
      "KyTruoc": 5,
      "KyHienTai": 23,
      "KhoiLuongTang": 18,
      "PhanTramTang": 360
    },
    {
      "Danhba": "22103410002",
      "KyTruoc": 5,
      "KyHienTai": 23,
      "KhoiLuongTang": 18,
      "PhanTramTang": 360
    },
    {
      "Danhba": "22073340143",
      "KyTruoc": 2,
      "KyHienTai": 20,
      "KhoiLuongTang": 18,
      "PhanTramTang": 900
    },
    {
      "Danhba": "22043308958",
      "KyTruoc": 2,
      "KyHienTai": 20,
      "KhoiLuongTang": 18,
      "PhanTramTang": 900
    },
    {
      "Danhba": "22043270637",
      "KyTruoc": 5,
      "KyHienTai": 23,
      "KhoiLuongTang": 18,
      "PhanTramTang": 360
    },
    {
      "Danhba": "15122890672",
      "KyTruoc": 1,
      "KyHienTai": 19,
      "KhoiLuongTang": 18,
      "PhanTramTang": 1800
    },
    {
      "Danhba": "15141930115",
      "KyTruoc": 1,
      "KyHienTai": 19,
      "KhoiLuongTang": 18,
      "PhanTramTang": 1800
    },
    {
      "Danhba": "15141930135",
      "KyTruoc": 4,
      "KyHienTai": 22,
      "KhoiLuongTang": 18,
      "PhanTramTang": 450
    },
    {
      "Danhba": "15141931283",
      "KyTruoc": 5,
      "KyHienTai": 23,
      "KhoiLuongTang": 18,
      "PhanTramTang": 360
    },
    {
      "Danhba": "22033258650",
      "KyTruoc": 3,
      "KyHienTai": 21,
      "KhoiLuongTang": 18,
      "PhanTramTang": 600
    },
    {
      "Danhba": "22033272176",
      "KyTruoc": 1,
      "KyHienTai": 19,
      "KhoiLuongTang": 18,
      "PhanTramTang": 1800
    },
    {
      "Danhba": "22033274400",
      "KyTruoc": 4,
      "KyHienTai": 22,
      "KhoiLuongTang": 18,
      "PhanTramTang": 450
    },
    {
      "Danhba": "15062135768",
      "KyTruoc": 5,
      "KyHienTai": 23,
      "KhoiLuongTang": 18,
      "PhanTramTang": 360
    },
    {
      "Danhba": "15122840731",
      "KyTruoc": 1,
      "KyHienTai": 19,
      "KhoiLuongTang": 18,
      "PhanTramTang": 1800
    },
    {
      "Danhba": "15102729182",
      "KyTruoc": 4,
      "KyHienTai": 22,
      "KhoiLuongTang": 18,
      "PhanTramTang": 450
    },
    {
      "Danhba": "22103410543",
      "KyTruoc": 4,
      "KyHienTai": 22,
      "KhoiLuongTang": 18,
      "PhanTramTang": 450
    },
    {
      "Danhba": "22103410986",
      "KyTruoc": 5,
      "KyHienTai": 22,
      "KhoiLuongTang": 17,
      "PhanTramTang": 340
    },
    {
      "Danhba": "15112829299",
      "KyTruoc": 1,
      "KyHienTai": 18,
      "KhoiLuongTang": 17,
      "PhanTramTang": 1700
    },
    {
      "Danhba": "15112826971",
      "KyTruoc": 2,
      "KyHienTai": 19,
      "KhoiLuongTang": 17,
      "PhanTramTang": 850
    },
    {
      "Danhba": "15122841142",
      "KyTruoc": 2,
      "KyHienTai": 19,
      "KhoiLuongTang": 17,
      "PhanTramTang": 850
    },
    {
      "Danhba": "15112860913",
      "KyTruoc": 4,
      "KyHienTai": 21,
      "KhoiLuongTang": 17,
      "PhanTramTang": 425
    },
    {
      "Danhba": "15062132306",
      "KyTruoc": 3,
      "KyHienTai": 20,
      "KhoiLuongTang": 17,
      "PhanTramTang": 566.7
    },
    {
      "Danhba": "15062137994",
      "KyTruoc": 2,
      "KyHienTai": 19,
      "KhoiLuongTang": 17,
      "PhanTramTang": 850
    },
    {
      "Danhba": "15072425576",
      "KyTruoc": 3,
      "KyHienTai": 20,
      "KhoiLuongTang": 17,
      "PhanTramTang": 566.7
    },
    {
      "Danhba": "15072428670",
      "KyTruoc": 1,
      "KyHienTai": 18,
      "KhoiLuongTang": 17,
      "PhanTramTang": 1700
    },
    {
      "Danhba": "22033270137",
      "KyTruoc": 3,
      "KyHienTai": 20,
      "KhoiLuongTang": 17,
      "PhanTramTang": 566.7
    },
    {
      "Danhba": "15141930647",
      "KyTruoc": 3,
      "KyHienTai": 20,
      "KhoiLuongTang": 17,
      "PhanTramTang": 566.7
    },
    {
      "Danhba": "22043278253",
      "KyTruoc": 2,
      "KyHienTai": 19,
      "KhoiLuongTang": 17,
      "PhanTramTang": 850
    },
    {
      "Danhba": "22043298575",
      "KyTruoc": 4,
      "KyHienTai": 21,
      "KhoiLuongTang": 17,
      "PhanTramTang": 425
    },
    {
      "Danhba": "22043301066",
      "KyTruoc": 2,
      "KyHienTai": 19,
      "KhoiLuongTang": 17,
      "PhanTramTang": 850
    },
    {
      "Danhba": "22043307158",
      "KyTruoc": 5,
      "KyHienTai": 22,
      "KhoiLuongTang": 17,
      "PhanTramTang": 340
    },
    {
      "Danhba": "22033331322",
      "KyTruoc": 4,
      "KyHienTai": 21,
      "KhoiLuongTang": 17,
      "PhanTramTang": 425
    },
    {
      "Danhba": "22033279967",
      "KyTruoc": 5,
      "KyHienTai": 22,
      "KhoiLuongTang": 17,
      "PhanTramTang": 340
    },
    {
      "Danhba": "22033329275",
      "KyTruoc": 2,
      "KyHienTai": 19,
      "KhoiLuongTang": 17,
      "PhanTramTang": 850
    },
    {
      "Danhba": "22033277194",
      "KyTruoc": 2,
      "KyHienTai": 19,
      "KhoiLuongTang": 17,
      "PhanTramTang": 850
    },
    {
      "Danhba": "22103401530",
      "KyTruoc": 1,
      "KyHienTai": 18,
      "KhoiLuongTang": 17,
      "PhanTramTang": 1700
    },
    {
      "Danhba": "22103398729",
      "KyTruoc": 3,
      "KyHienTai": 20,
      "KhoiLuongTang": 17,
      "PhanTramTang": 566.7
    },
    {
      "Danhba": "22073240781",
      "KyTruoc": 5,
      "KyHienTai": 22,
      "KhoiLuongTang": 17,
      "PhanTramTang": 340
    },
    {
      "Danhba": "22073238532",
      "KyTruoc": 1,
      "KyHienTai": 18,
      "KhoiLuongTang": 17,
      "PhanTramTang": 1700
    },
    {
      "Danhba": "22073233097",
      "KyTruoc": 4,
      "KyHienTai": 20,
      "KhoiLuongTang": 16,
      "PhanTramTang": 400
    },
    {
      "Danhba": "22073240057",
      "KyTruoc": 5,
      "KyHienTai": 21,
      "KhoiLuongTang": 16,
      "PhanTramTang": 320
    },
    {
      "Danhba": "22073241693",
      "KyTruoc": 4,
      "KyHienTai": 20,
      "KhoiLuongTang": 16,
      "PhanTramTang": 400
    },
    {
      "Danhba": "22043314258",
      "KyTruoc": 2,
      "KyHienTai": 18,
      "KhoiLuongTang": 16,
      "PhanTramTang": 800
    },
    {
      "Danhba": "22103397268",
      "KyTruoc": 1,
      "KyHienTai": 17,
      "KhoiLuongTang": 16,
      "PhanTramTang": 1600
    },
    {
      "Danhba": "22103397321",
      "KyTruoc": 5,
      "KyHienTai": 21,
      "KhoiLuongTang": 16,
      "PhanTramTang": 320
    },
    {
      "Danhba": "22073340996",
      "KyTruoc": 2,
      "KyHienTai": 18,
      "KhoiLuongTang": 16,
      "PhanTramTang": 800
    },
    {
      "Danhba": "22033279539",
      "KyTruoc": 1,
      "KyHienTai": 17,
      "KhoiLuongTang": 16,
      "PhanTramTang": 1600
    },
    {
      "Danhba": "22033331567",
      "KyTruoc": 3,
      "KyHienTai": 19,
      "KhoiLuongTang": 16,
      "PhanTramTang": 533.3
    },
    {
      "Danhba": "22033334078",
      "KyTruoc": 3,
      "KyHienTai": 19,
      "KhoiLuongTang": 16,
      "PhanTramTang": 533.3
    },
    {
      "Danhba": "22043304823",
      "KyTruoc": 4,
      "KyHienTai": 20,
      "KhoiLuongTang": 16,
      "PhanTramTang": 400
    },
    {
      "Danhba": "22043300917",
      "KyTruoc": 2,
      "KyHienTai": 18,
      "KhoiLuongTang": 16,
      "PhanTramTang": 800
    },
    {
      "Danhba": "15122843513",
      "KyTruoc": 3,
      "KyHienTai": 19,
      "KhoiLuongTang": 16,
      "PhanTramTang": 533.3
    },
    {
      "Danhba": "15122880528",
      "KyTruoc": 4,
      "KyHienTai": 20,
      "KhoiLuongTang": 16,
      "PhanTramTang": 400
    },
    {
      "Danhba": "15122880537",
      "KyTruoc": 5,
      "KyHienTai": 21,
      "KhoiLuongTang": 16,
      "PhanTramTang": 320
    },
    {
      "Danhba": "22033256042",
      "KyTruoc": 1,
      "KyHienTai": 17,
      "KhoiLuongTang": 16,
      "PhanTramTang": 1600
    },
    {
      "Danhba": "15141932959",
      "KyTruoc": 2,
      "KyHienTai": 18,
      "KhoiLuongTang": 16,
      "PhanTramTang": 800
    },
    {
      "Danhba": "22033273311",
      "KyTruoc": 4,
      "KyHienTai": 20,
      "KhoiLuongTang": 16,
      "PhanTramTang": 400
    },
    {
      "Danhba": "22033271452",
      "KyTruoc": 3,
      "KyHienTai": 19,
      "KhoiLuongTang": 16,
      "PhanTramTang": 533.3
    },
    {
      "Danhba": "22033271901",
      "KyTruoc": 1,
      "KyHienTai": 17,
      "KhoiLuongTang": 16,
      "PhanTramTang": 1600
    },
    {
      "Danhba": "22033272146",
      "KyTruoc": 5,
      "KyHienTai": 21,
      "KhoiLuongTang": 16,
      "PhanTramTang": 320
    },
    {
      "Danhba": "15112868689",
      "KyTruoc": 2,
      "KyHienTai": 18,
      "KhoiLuongTang": 16,
      "PhanTramTang": 800
    },
    {
      "Danhba": "22103411060",
      "KyTruoc": 5,
      "KyHienTai": 21,
      "KhoiLuongTang": 16,
      "PhanTramTang": 320
    },
    {
      "Danhba": "22103414140",
      "KyTruoc": 4,
      "KyHienTai": 20,
      "KhoiLuongTang": 16,
      "PhanTramTang": 400
    }
  ],
  "stuckTop": [
    {
      "Danhba": "22033279036",
      "KyTruoc": 1270,
      "KyHienTai": 2,
      "KhoiLuongGiam": 1268,
      "PhanTramGiam": 99.8
    },
    {
      "Danhba": "15062139358",
      "KyTruoc": 708,
      "KyHienTai": 26,
      "KhoiLuongGiam": 682,
      "PhanTramGiam": 96.3
    },
    {
      "Danhba": "15102742690",
      "KyTruoc": 756,
      "KyHienTai": 139,
      "KhoiLuongGiam": 617,
      "PhanTramGiam": 81.6
    },
    {
      "Danhba": "15072448530",
      "KyTruoc": 577,
      "KyHienTai": 103,
      "KhoiLuongGiam": 474,
      "PhanTramGiam": 82.1
    },
    {
      "Danhba": "22073335180",
      "KyTruoc": 402,
      "KyHienTai": 0,
      "KhoiLuongGiam": 402,
      "PhanTramGiam": 100
    },
    {
      "Danhba": "15112823581",
      "KyTruoc": 409,
      "KyHienTai": 38,
      "KhoiLuongGiam": 371,
      "PhanTramGiam": 90.7
    },
    {
      "Danhba": "22103402024",
      "KyTruoc": 345,
      "KyHienTai": 14,
      "KhoiLuongGiam": 331,
      "PhanTramGiam": 95.9
    },
    {
      "Danhba": "15112867378",
      "KyTruoc": 333,
      "KyHienTai": 7,
      "KhoiLuongGiam": 326,
      "PhanTramGiam": 97.9
    },
    {
      "Danhba": "22043300760",
      "KyTruoc": 324,
      "KyHienTai": 21,
      "KhoiLuongGiam": 303,
      "PhanTramGiam": 93.5
    },
    {
      "Danhba": "15112840391",
      "KyTruoc": 271,
      "KyHienTai": 0,
      "KhoiLuongGiam": 271,
      "PhanTramGiam": 100
    },
    {
      "Danhba": "15173420295",
      "KyTruoc": 264,
      "KyHienTai": 0,
      "KhoiLuongGiam": 264,
      "PhanTramGiam": 100
    },
    {
      "Danhba": "22043309800",
      "KyTruoc": 265,
      "KyHienTai": 3,
      "KhoiLuongGiam": 262,
      "PhanTramGiam": 98.9
    },
    {
      "Danhba": "22103413394",
      "KyTruoc": 322,
      "KyHienTai": 74,
      "KhoiLuongGiam": 248,
      "PhanTramGiam": 77
    },
    {
      "Danhba": "22033272422",
      "KyTruoc": 248,
      "KyHienTai": 2,
      "KhoiLuongGiam": 246,
      "PhanTramGiam": 99.2
    },
    {
      "Danhba": "15072468269",
      "KyTruoc": 293,
      "KyHienTai": 48,
      "KhoiLuongGiam": 245,
      "PhanTramGiam": 83.6
    },
    {
      "Danhba": "15062131307",
      "KyTruoc": 231,
      "KyHienTai": 1,
      "KhoiLuongGiam": 230,
      "PhanTramGiam": 99.6
    },
    {
      "Danhba": "22043308362",
      "KyTruoc": 242,
      "KyHienTai": 21,
      "KhoiLuongGiam": 221,
      "PhanTramGiam": 91.3
    },
    {
      "Danhba": "22103412364",
      "KyTruoc": 191,
      "KyHienTai": 0,
      "KhoiLuongGiam": 191,
      "PhanTramGiam": 100
    },
    {
      "Danhba": "15072468212",
      "KyTruoc": 178,
      "KyHienTai": 6,
      "KhoiLuongGiam": 172,
      "PhanTramGiam": 96.6
    },
    {
      "Danhba": "22043300313",
      "KyTruoc": 190,
      "KyHienTai": 19,
      "KhoiLuongGiam": 171,
      "PhanTramGiam": 90
    },
    {
      "Danhba": "22033278969",
      "KyTruoc": 183,
      "KyHienTai": 16,
      "KhoiLuongGiam": 167,
      "PhanTramGiam": 91.3
    },
    {
      "Danhba": "15122891299",
      "KyTruoc": 168,
      "KyHienTai": 2,
      "KhoiLuongGiam": 166,
      "PhanTramGiam": 98.8
    },
    {
      "Danhba": "22033271595",
      "KyTruoc": 171,
      "KyHienTai": 12,
      "KhoiLuongGiam": 159,
      "PhanTramGiam": 93
    },
    {
      "Danhba": "22073341143",
      "KyTruoc": 175,
      "KyHienTai": 20,
      "KhoiLuongGiam": 155,
      "PhanTramGiam": 88.6
    },
    {
      "Danhba": "22103410316",
      "KyTruoc": 153,
      "KyHienTai": 3,
      "KhoiLuongGiam": 150,
      "PhanTramGiam": 98
    },
    {
      "Danhba": "22033279448",
      "KyTruoc": 176,
      "KyHienTai": 34,
      "KhoiLuongGiam": 142,
      "PhanTramGiam": 80.7
    },
    {
      "Danhba": "15062141133",
      "KyTruoc": 161,
      "KyHienTai": 24,
      "KhoiLuongGiam": 137,
      "PhanTramGiam": 85.1
    },
    {
      "Danhba": "15141939447",
      "KyTruoc": 136,
      "KyHienTai": 0,
      "KhoiLuongGiam": 136,
      "PhanTramGiam": 100
    },
    {
      "Danhba": "15102723218",
      "KyTruoc": 133,
      "KyHienTai": 0,
      "KhoiLuongGiam": 133,
      "PhanTramGiam": 100
    },
    {
      "Danhba": "15122891178",
      "KyTruoc": 126,
      "KyHienTai": 2,
      "KhoiLuongGiam": 124,
      "PhanTramGiam": 98.4
    },
    {
      "Danhba": "15102720922",
      "KyTruoc": 133,
      "KyHienTai": 13,
      "KhoiLuongGiam": 120,
      "PhanTramGiam": 90.2
    },
    {
      "Danhba": "15072425885",
      "KyTruoc": 147,
      "KyHienTai": 29,
      "KhoiLuongGiam": 118,
      "PhanTramGiam": 80.3
    },
    {
      "Danhba": "15112826554",
      "KyTruoc": 135,
      "KyHienTai": 20,
      "KhoiLuongGiam": 115,
      "PhanTramGiam": 85.2
    },
    {
      "Danhba": "15072443129",
      "KyTruoc": 138,
      "KyHienTai": 33,
      "KhoiLuongGiam": 105,
      "PhanTramGiam": 76.1
    },
    {
      "Danhba": "22043314647",
      "KyTruoc": 112,
      "KyHienTai": 7,
      "KhoiLuongGiam": 105,
      "PhanTramGiam": 93.8
    },
    {
      "Danhba": "15112848021",
      "KyTruoc": 101,
      "KyHienTai": 0,
      "KhoiLuongGiam": 101,
      "PhanTramGiam": 100
    },
    {
      "Danhba": "22103399026",
      "KyTruoc": 125,
      "KyHienTai": 24,
      "KhoiLuongGiam": 101,
      "PhanTramGiam": 80.8
    },
    {
      "Danhba": "22073342208",
      "KyTruoc": 111,
      "KyHienTai": 11,
      "KhoiLuongGiam": 100,
      "PhanTramGiam": 90.1
    },
    {
      "Danhba": "22033271265",
      "KyTruoc": 112,
      "KyHienTai": 15,
      "KhoiLuongGiam": 97,
      "PhanTramGiam": 86.6
    },
    {
      "Danhba": "15112841487",
      "KyTruoc": 126,
      "KyHienTai": 30,
      "KhoiLuongGiam": 96,
      "PhanTramGiam": 76.2
    },
    {
      "Danhba": "22103413683",
      "KyTruoc": 117,
      "KyHienTai": 25,
      "KhoiLuongGiam": 92,
      "PhanTramGiam": 78.6
    },
    {
      "Danhba": "22103393090",
      "KyTruoc": 94,
      "KyHienTai": 3,
      "KhoiLuongGiam": 91,
      "PhanTramGiam": 96.8
    },
    {
      "Danhba": "22043309502",
      "KyTruoc": 90,
      "KyHienTai": 0,
      "KhoiLuongGiam": 90,
      "PhanTramGiam": 100
    },
    {
      "Danhba": "22073342697",
      "KyTruoc": 114,
      "KyHienTai": 25,
      "KhoiLuongGiam": 89,
      "PhanTramGiam": 78.1
    },
    {
      "Danhba": "15102720248",
      "KyTruoc": 104,
      "KyHienTai": 15,
      "KhoiLuongGiam": 89,
      "PhanTramGiam": 85.6
    },
    {
      "Danhba": "15112827437",
      "KyTruoc": 93,
      "KyHienTai": 4,
      "KhoiLuongGiam": 89,
      "PhanTramGiam": 95.7
    },
    {
      "Danhba": "15122889517",
      "KyTruoc": 91,
      "KyHienTai": 3,
      "KhoiLuongGiam": 88,
      "PhanTramGiam": 96.7
    },
    {
      "Danhba": "22043314438",
      "KyTruoc": 95,
      "KyHienTai": 8,
      "KhoiLuongGiam": 87,
      "PhanTramGiam": 91.6
    },
    {
      "Danhba": "15122885952",
      "KyTruoc": 96,
      "KyHienTai": 11,
      "KhoiLuongGiam": 85,
      "PhanTramGiam": 88.5
    },
    {
      "Danhba": "22103411752",
      "KyTruoc": 87,
      "KyHienTai": 3,
      "KhoiLuongGiam": 84,
      "PhanTramGiam": 96.6
    },
    {
      "Danhba": "15112866564",
      "KyTruoc": 100,
      "KyHienTai": 17,
      "KhoiLuongGiam": 83,
      "PhanTramGiam": 83
    },
    {
      "Danhba": "15122891346",
      "KyTruoc": 84,
      "KyHienTai": 2,
      "KhoiLuongGiam": 82,
      "PhanTramGiam": 97.6
    },
    {
      "Danhba": "22033277130",
      "KyTruoc": 82,
      "KyHienTai": 0,
      "KhoiLuongGiam": 82,
      "PhanTramGiam": 100
    },
    {
      "Danhba": "15072448352",
      "KyTruoc": 105,
      "KyHienTai": 24,
      "KhoiLuongGiam": 81,
      "PhanTramGiam": 77.1
    },
    {
      "Danhba": "22103400959",
      "KyTruoc": 77,
      "KyHienTai": 0,
      "KhoiLuongGiam": 77,
      "PhanTramGiam": 100
    },
    {
      "Danhba": "15122882080",
      "KyTruoc": 90,
      "KyHienTai": 14,
      "KhoiLuongGiam": 76,
      "PhanTramGiam": 84.4
    },
    {
      "Danhba": "15112868306",
      "KyTruoc": 97,
      "KyHienTai": 21,
      "KhoiLuongGiam": 76,
      "PhanTramGiam": 78.4
    },
    {
      "Danhba": "15112869036",
      "KyTruoc": 91,
      "KyHienTai": 15,
      "KhoiLuongGiam": 76,
      "PhanTramGiam": 83.5
    },
    {
      "Danhba": "22033331625",
      "KyTruoc": 88,
      "KyHienTai": 12,
      "KhoiLuongGiam": 76,
      "PhanTramGiam": 86.4
    },
    {
      "Danhba": "15072428809",
      "KyTruoc": 89,
      "KyHienTai": 15,
      "KhoiLuongGiam": 74,
      "PhanTramGiam": 83.1
    },
    {
      "Danhba": "15062130200",
      "KyTruoc": 79,
      "KyHienTai": 5,
      "KhoiLuongGiam": 74,
      "PhanTramGiam": 93.7
    },
    {
      "Danhba": "15122889346",
      "KyTruoc": 97,
      "KyHienTai": 24,
      "KhoiLuongGiam": 73,
      "PhanTramGiam": 75.3
    },
    {
      "Danhba": "15173420194",
      "KyTruoc": 88,
      "KyHienTai": 15,
      "KhoiLuongGiam": 73,
      "PhanTramGiam": 83
    },
    {
      "Danhba": "22033275232",
      "KyTruoc": 80,
      "KyHienTai": 9,
      "KhoiLuongGiam": 71,
      "PhanTramGiam": 88.8
    },
    {
      "Danhba": "15112842601",
      "KyTruoc": 87,
      "KyHienTai": 18,
      "KhoiLuongGiam": 69,
      "PhanTramGiam": 79.3
    },
    {
      "Danhba": "15072428739",
      "KyTruoc": 88,
      "KyHienTai": 21,
      "KhoiLuongGiam": 67,
      "PhanTramGiam": 76.1
    },
    {
      "Danhba": "22033332842",
      "KyTruoc": 82,
      "KyHienTai": 15,
      "KhoiLuongGiam": 67,
      "PhanTramGiam": 81.7
    },
    {
      "Danhba": "22033333897",
      "KyTruoc": 80,
      "KyHienTai": 13,
      "KhoiLuongGiam": 67,
      "PhanTramGiam": 83.8
    },
    {
      "Danhba": "22103413880",
      "KyTruoc": 89,
      "KyHienTai": 22,
      "KhoiLuongGiam": 67,
      "PhanTramGiam": 75.3
    },
    {
      "Danhba": "22103410238",
      "KyTruoc": 77,
      "KyHienTai": 10,
      "KhoiLuongGiam": 67,
      "PhanTramGiam": 87
    },
    {
      "Danhba": "22103408754",
      "KyTruoc": 81,
      "KyHienTai": 15,
      "KhoiLuongGiam": 66,
      "PhanTramGiam": 81.5
    },
    {
      "Danhba": "22043309807",
      "KyTruoc": 76,
      "KyHienTai": 10,
      "KhoiLuongGiam": 66,
      "PhanTramGiam": 86.8
    },
    {
      "Danhba": "22033279954",
      "KyTruoc": 76,
      "KyHienTai": 11,
      "KhoiLuongGiam": 65,
      "PhanTramGiam": 85.5
    },
    {
      "Danhba": "15112883165",
      "KyTruoc": 74,
      "KyHienTai": 9,
      "KhoiLuongGiam": 65,
      "PhanTramGiam": 87.8
    },
    {
      "Danhba": "15062139237",
      "KyTruoc": 79,
      "KyHienTai": 15,
      "KhoiLuongGiam": 64,
      "PhanTramGiam": 81
    },
    {
      "Danhba": "15072481260",
      "KyTruoc": 83,
      "KyHienTai": 20,
      "KhoiLuongGiam": 63,
      "PhanTramGiam": 75.9
    },
    {
      "Danhba": "22043290747",
      "KyTruoc": 75,
      "KyHienTai": 12,
      "KhoiLuongGiam": 63,
      "PhanTramGiam": 84
    },
    {
      "Danhba": "15072426432",
      "KyTruoc": 77,
      "KyHienTai": 15,
      "KhoiLuongGiam": 62,
      "PhanTramGiam": 80.5
    },
    {
      "Danhba": "15072428840",
      "KyTruoc": 61,
      "KyHienTai": 0,
      "KhoiLuongGiam": 61,
      "PhanTramGiam": 100
    },
    {
      "Danhba": "22043303384",
      "KyTruoc": 77,
      "KyHienTai": 16,
      "KhoiLuongGiam": 61,
      "PhanTramGiam": 79.2
    },
    {
      "Danhba": "15112844309",
      "KyTruoc": 63,
      "KyHienTai": 4,
      "KhoiLuongGiam": 59,
      "PhanTramGiam": 93.7
    },
    {
      "Danhba": "15072420522",
      "KyTruoc": 70,
      "KyHienTai": 13,
      "KhoiLuongGiam": 57,
      "PhanTramGiam": 81.4
    },
    {
      "Danhba": "15062134426",
      "KyTruoc": 57,
      "KyHienTai": 0,
      "KhoiLuongGiam": 57,
      "PhanTramGiam": 100
    },
    {
      "Danhba": "22073341761",
      "KyTruoc": 57,
      "KyHienTai": 0,
      "KhoiLuongGiam": 57,
      "PhanTramGiam": 100
    },
    {
      "Danhba": "22073230641",
      "KyTruoc": 70,
      "KyHienTai": 14,
      "KhoiLuongGiam": 56,
      "PhanTramGiam": 80
    },
    {
      "Danhba": "22043314611",
      "KyTruoc": 73,
      "KyHienTai": 17,
      "KhoiLuongGiam": 56,
      "PhanTramGiam": 76.7
    },
    {
      "Danhba": "22103408661",
      "KyTruoc": 56,
      "KyHienTai": 1,
      "KhoiLuongGiam": 55,
      "PhanTramGiam": 98.2
    },
    {
      "Danhba": "22073343277",
      "KyTruoc": 54,
      "KyHienTai": 0,
      "KhoiLuongGiam": 54,
      "PhanTramGiam": 100
    },
    {
      "Danhba": "22103412823",
      "KyTruoc": 64,
      "KyHienTai": 10,
      "KhoiLuongGiam": 54,
      "PhanTramGiam": 84.4
    },
    {
      "Danhba": "15062138538",
      "KyTruoc": 65,
      "KyHienTai": 11,
      "KhoiLuongGiam": 54,
      "PhanTramGiam": 83.1
    },
    {
      "Danhba": "15062136629",
      "KyTruoc": 63,
      "KyHienTai": 9,
      "KhoiLuongGiam": 54,
      "PhanTramGiam": 85.7
    },
    {
      "Danhba": "22033278021",
      "KyTruoc": 54,
      "KyHienTai": 1,
      "KhoiLuongGiam": 53,
      "PhanTramGiam": 98.1
    },
    {
      "Danhba": "15173422077",
      "KyTruoc": 53,
      "KyHienTai": 0,
      "KhoiLuongGiam": 53,
      "PhanTramGiam": 100
    },
    {
      "Danhba": "22073334929",
      "KyTruoc": 52,
      "KyHienTai": 1,
      "KhoiLuongGiam": 51,
      "PhanTramGiam": 98.1
    },
    {
      "Danhba": "22073340416",
      "KyTruoc": 64,
      "KyHienTai": 13,
      "KhoiLuongGiam": 51,
      "PhanTramGiam": 79.7
    },
    {
      "Danhba": "15062137078",
      "KyTruoc": 51,
      "KyHienTai": 0,
      "KhoiLuongGiam": 51,
      "PhanTramGiam": 100
    },
    {
      "Danhba": "15062140238",
      "KyTruoc": 64,
      "KyHienTai": 13,
      "KhoiLuongGiam": 51,
      "PhanTramGiam": 79.7
    },
    {
      "Danhba": "22073342795",
      "KyTruoc": 58,
      "KyHienTai": 7,
      "KhoiLuongGiam": 51,
      "PhanTramGiam": 87.9
    },
    {
      "Danhba": "22043307659",
      "KyTruoc": 62,
      "KyHienTai": 12,
      "KhoiLuongGiam": 50,
      "PhanTramGiam": 80.6
    },
    {
      "Danhba": "22033274083",
      "KyTruoc": 59,
      "KyHienTai": 9,
      "KhoiLuongGiam": 50,
      "PhanTramGiam": 84.7
    },
    {
      "Danhba": "22073238737",
      "KyTruoc": 54,
      "KyHienTai": 5,
      "KhoiLuongGiam": 49,
      "PhanTramGiam": 90.7
    },
    {
      "Danhba": "15062141132",
      "KyTruoc": 53,
      "KyHienTai": 5,
      "KhoiLuongGiam": 48,
      "PhanTramGiam": 90.6
    },
    {
      "Danhba": "22073342780",
      "KyTruoc": 62,
      "KyHienTai": 15,
      "KhoiLuongGiam": 47,
      "PhanTramGiam": 75.8
    },
    {
      "Danhba": "22043334353",
      "KyTruoc": 50,
      "KyHienTai": 3,
      "KhoiLuongGiam": 47,
      "PhanTramGiam": 94
    },
    {
      "Danhba": "22073239852",
      "KyTruoc": 46,
      "KyHienTai": 0,
      "KhoiLuongGiam": 46,
      "PhanTramGiam": 100
    },
    {
      "Danhba": "22033276033",
      "KyTruoc": 54,
      "KyHienTai": 9,
      "KhoiLuongGiam": 45,
      "PhanTramGiam": 83.3
    },
    {
      "Danhba": "22103396694",
      "KyTruoc": 46,
      "KyHienTai": 1,
      "KhoiLuongGiam": 45,
      "PhanTramGiam": 97.8
    },
    {
      "Danhba": "22103401028",
      "KyTruoc": 56,
      "KyHienTai": 11,
      "KhoiLuongGiam": 45,
      "PhanTramGiam": 80.4
    },
    {
      "Danhba": "22103413348",
      "KyTruoc": 45,
      "KyHienTai": 1,
      "KhoiLuongGiam": 44,
      "PhanTramGiam": 97.8
    },
    {
      "Danhba": "15072460359",
      "KyTruoc": 48,
      "KyHienTai": 4,
      "KhoiLuongGiam": 44,
      "PhanTramGiam": 91.7
    },
    {
      "Danhba": "15122845233",
      "KyTruoc": 48,
      "KyHienTai": 4,
      "KhoiLuongGiam": 44,
      "PhanTramGiam": 91.7
    },
    {
      "Danhba": "15122845159",
      "KyTruoc": 49,
      "KyHienTai": 6,
      "KhoiLuongGiam": 43,
      "PhanTramGiam": 87.8
    },
    {
      "Danhba": "15141934181",
      "KyTruoc": 54,
      "KyHienTai": 11,
      "KhoiLuongGiam": 43,
      "PhanTramGiam": 79.6
    },
    {
      "Danhba": "22073239967",
      "KyTruoc": 47,
      "KyHienTai": 4,
      "KhoiLuongGiam": 43,
      "PhanTramGiam": 91.5
    },
    {
      "Danhba": "22043302832",
      "KyTruoc": 55,
      "KyHienTai": 12,
      "KhoiLuongGiam": 43,
      "PhanTramGiam": 78.2
    },
    {
      "Danhba": "22073342143",
      "KyTruoc": 46,
      "KyHienTai": 3,
      "KhoiLuongGiam": 43,
      "PhanTramGiam": 93.5
    },
    {
      "Danhba": "22043313730",
      "KyTruoc": 44,
      "KyHienTai": 2,
      "KhoiLuongGiam": 42,
      "PhanTramGiam": 95.5
    },
    {
      "Danhba": "22043300602",
      "KyTruoc": 42,
      "KyHienTai": 0,
      "KhoiLuongGiam": 42,
      "PhanTramGiam": 100
    },
    {
      "Danhba": "22043304780",
      "KyTruoc": 41,
      "KyHienTai": 0,
      "KhoiLuongGiam": 41,
      "PhanTramGiam": 100
    },
    {
      "Danhba": "22033272158",
      "KyTruoc": 52,
      "KyHienTai": 11,
      "KhoiLuongGiam": 41,
      "PhanTramGiam": 78.8
    },
    {
      "Danhba": "22073232390",
      "KyTruoc": 41,
      "KyHienTai": 0,
      "KhoiLuongGiam": 41,
      "PhanTramGiam": 100
    },
    {
      "Danhba": "22033274426",
      "KyTruoc": 49,
      "KyHienTai": 9,
      "KhoiLuongGiam": 40,
      "PhanTramGiam": 81.6
    },
    {
      "Danhba": "22033278778",
      "KyTruoc": 40,
      "KyHienTai": 0,
      "KhoiLuongGiam": 40,
      "PhanTramGiam": 100
    },
    {
      "Danhba": "15062137656",
      "KyTruoc": 41,
      "KyHienTai": 1,
      "KhoiLuongGiam": 40,
      "PhanTramGiam": 97.6
    },
    {
      "Danhba": "15122890774",
      "KyTruoc": 39,
      "KyHienTai": 0,
      "KhoiLuongGiam": 39,
      "PhanTramGiam": 100
    },
    {
      "Danhba": "15112865827",
      "KyTruoc": 43,
      "KyHienTai": 4,
      "KhoiLuongGiam": 39,
      "PhanTramGiam": 90.7
    },
    {
      "Danhba": "22033274571",
      "KyTruoc": 49,
      "KyHienTai": 10,
      "KhoiLuongGiam": 39,
      "PhanTramGiam": 79.6
    },
    {
      "Danhba": "22103396321",
      "KyTruoc": 39,
      "KyHienTai": 0,
      "KhoiLuongGiam": 39,
      "PhanTramGiam": 100
    },
    {
      "Danhba": "22103412402",
      "KyTruoc": 39,
      "KyHienTai": 0,
      "KhoiLuongGiam": 39,
      "PhanTramGiam": 100
    },
    {
      "Danhba": "15173422138",
      "KyTruoc": 50,
      "KyHienTai": 12,
      "KhoiLuongGiam": 38,
      "PhanTramGiam": 76
    },
    {
      "Danhba": "15141950383",
      "KyTruoc": 50,
      "KyHienTai": 12,
      "KhoiLuongGiam": 38,
      "PhanTramGiam": 76
    },
    {
      "Danhba": "15112829140",
      "KyTruoc": 40,
      "KyHienTai": 2,
      "KhoiLuongGiam": 38,
      "PhanTramGiam": 95
    },
    {
      "Danhba": "15122843993",
      "KyTruoc": 46,
      "KyHienTai": 9,
      "KhoiLuongGiam": 37,
      "PhanTramGiam": 80.4
    },
    {
      "Danhba": "15141950220",
      "KyTruoc": 48,
      "KyHienTai": 11,
      "KhoiLuongGiam": 37,
      "PhanTramGiam": 77.1
    },
    {
      "Danhba": "15102728593",
      "KyTruoc": 43,
      "KyHienTai": 6,
      "KhoiLuongGiam": 37,
      "PhanTramGiam": 86
    },
    {
      "Danhba": "22043334464",
      "KyTruoc": 41,
      "KyHienTai": 4,
      "KhoiLuongGiam": 37,
      "PhanTramGiam": 90.2
    },
    {
      "Danhba": "22103410537",
      "KyTruoc": 38,
      "KyHienTai": 1,
      "KhoiLuongGiam": 37,
      "PhanTramGiam": 97.4
    },
    {
      "Danhba": "22103414104",
      "KyTruoc": 44,
      "KyHienTai": 7,
      "KhoiLuongGiam": 37,
      "PhanTramGiam": 84.1
    },
    {
      "Danhba": "22033277771",
      "KyTruoc": 36,
      "KyHienTai": 0,
      "KhoiLuongGiam": 36,
      "PhanTramGiam": 100
    },
    {
      "Danhba": "22033276825",
      "KyTruoc": 38,
      "KyHienTai": 2,
      "KhoiLuongGiam": 36,
      "PhanTramGiam": 94.7
    },
    {
      "Danhba": "15062135119",
      "KyTruoc": 43,
      "KyHienTai": 7,
      "KhoiLuongGiam": 36,
      "PhanTramGiam": 83.7
    },
    {
      "Danhba": "15122881278",
      "KyTruoc": 37,
      "KyHienTai": 1,
      "KhoiLuongGiam": 36,
      "PhanTramGiam": 97.3
    },
    {
      "Danhba": "15122880296",
      "KyTruoc": 36,
      "KyHienTai": 0,
      "KhoiLuongGiam": 36,
      "PhanTramGiam": 100
    },
    {
      "Danhba": "15122842879",
      "KyTruoc": 36,
      "KyHienTai": 1,
      "KhoiLuongGiam": 35,
      "PhanTramGiam": 97.2
    },
    {
      "Danhba": "15062130086",
      "KyTruoc": 44,
      "KyHienTai": 10,
      "KhoiLuongGiam": 34,
      "PhanTramGiam": 77.3
    },
    {
      "Danhba": "22033328296",
      "KyTruoc": 34,
      "KyHienTai": 0,
      "KhoiLuongGiam": 34,
      "PhanTramGiam": 100
    },
    {
      "Danhba": "22043310815",
      "KyTruoc": 38,
      "KyHienTai": 4,
      "KhoiLuongGiam": 34,
      "PhanTramGiam": 89.5
    },
    {
      "Danhba": "22043310727",
      "KyTruoc": 33,
      "KyHienTai": 0,
      "KhoiLuongGiam": 33,
      "PhanTramGiam": 100
    },
    {
      "Danhba": "22043312990",
      "KyTruoc": 35,
      "KyHienTai": 2,
      "KhoiLuongGiam": 33,
      "PhanTramGiam": 94.3
    },
    {
      "Danhba": "22033268233",
      "KyTruoc": 41,
      "KyHienTai": 8,
      "KhoiLuongGiam": 33,
      "PhanTramGiam": 80.5
    },
    {
      "Danhba": "22033272644",
      "KyTruoc": 42,
      "KyHienTai": 9,
      "KhoiLuongGiam": 33,
      "PhanTramGiam": 78.6
    },
    {
      "Danhba": "15092621943",
      "KyTruoc": 32,
      "KyHienTai": 0,
      "KhoiLuongGiam": 32,
      "PhanTramGiam": 100
    },
    {
      "Danhba": "15112869033",
      "KyTruoc": 33,
      "KyHienTai": 1,
      "KhoiLuongGiam": 32,
      "PhanTramGiam": 97
    },
    {
      "Danhba": "22103414119",
      "KyTruoc": 32,
      "KyHienTai": 0,
      "KhoiLuongGiam": 32,
      "PhanTramGiam": 100
    },
    {
      "Danhba": "22073342883",
      "KyTruoc": 32,
      "KyHienTai": 1,
      "KhoiLuongGiam": 31,
      "PhanTramGiam": 96.9
    },
    {
      "Danhba": "15112841610",
      "KyTruoc": 31,
      "KyHienTai": 0,
      "KhoiLuongGiam": 31,
      "PhanTramGiam": 100
    },
    {
      "Danhba": "15122866332",
      "KyTruoc": 32,
      "KyHienTai": 1,
      "KhoiLuongGiam": 31,
      "PhanTramGiam": 96.9
    },
    {
      "Danhba": "15072480802",
      "KyTruoc": 32,
      "KyHienTai": 1,
      "KhoiLuongGiam": 31,
      "PhanTramGiam": 96.9
    },
    {
      "Danhba": "15072420534",
      "KyTruoc": 36,
      "KyHienTai": 5,
      "KhoiLuongGiam": 31,
      "PhanTramGiam": 86.1
    },
    {
      "Danhba": "15062130175",
      "KyTruoc": 30,
      "KyHienTai": 0,
      "KhoiLuongGiam": 30,
      "PhanTramGiam": 100
    },
    {
      "Danhba": "15031705226",
      "KyTruoc": 30,
      "KyHienTai": 0,
      "KhoiLuongGiam": 30,
      "PhanTramGiam": 100
    },
    {
      "Danhba": "15173420318",
      "KyTruoc": 30,
      "KyHienTai": 0,
      "KhoiLuongGiam": 30,
      "PhanTramGiam": 100
    },
    {
      "Danhba": "22043314554",
      "KyTruoc": 32,
      "KyHienTai": 2,
      "KhoiLuongGiam": 30,
      "PhanTramGiam": 93.8
    },
    {
      "Danhba": "22073341745",
      "KyTruoc": 33,
      "KyHienTai": 3,
      "KhoiLuongGiam": 30,
      "PhanTramGiam": 90.9
    },
    {
      "Danhba": "22073340449",
      "KyTruoc": 31,
      "KyHienTai": 2,
      "KhoiLuongGiam": 29,
      "PhanTramGiam": 93.5
    },
    {
      "Danhba": "22043314578",
      "KyTruoc": 32,
      "KyHienTai": 3,
      "KhoiLuongGiam": 29,
      "PhanTramGiam": 90.6
    },
    {
      "Danhba": "22033275989",
      "KyTruoc": 35,
      "KyHienTai": 6,
      "KhoiLuongGiam": 29,
      "PhanTramGiam": 82.9
    },
    {
      "Danhba": "22043270111",
      "KyTruoc": 32,
      "KyHienTai": 3,
      "KhoiLuongGiam": 29,
      "PhanTramGiam": 90.6
    },
    {
      "Danhba": "22033332697",
      "KyTruoc": 32,
      "KyHienTai": 3,
      "KhoiLuongGiam": 29,
      "PhanTramGiam": 90.6
    },
    {
      "Danhba": "15102742521",
      "KyTruoc": 36,
      "KyHienTai": 7,
      "KhoiLuongGiam": 29,
      "PhanTramGiam": 80.6
    },
    {
      "Danhba": "22103410162",
      "KyTruoc": 36,
      "KyHienTai": 7,
      "KhoiLuongGiam": 29,
      "PhanTramGiam": 80.6
    },
    {
      "Danhba": "22103413305",
      "KyTruoc": 35,
      "KyHienTai": 6,
      "KhoiLuongGiam": 29,
      "PhanTramGiam": 82.9
    },
    {
      "Danhba": "15112822823",
      "KyTruoc": 28,
      "KyHienTai": 0,
      "KhoiLuongGiam": 28,
      "PhanTramGiam": 100
    },
    {
      "Danhba": "15062139142",
      "KyTruoc": 28,
      "KyHienTai": 0,
      "KhoiLuongGiam": 28,
      "PhanTramGiam": 100
    },
    {
      "Danhba": "15122880968",
      "KyTruoc": 36,
      "KyHienTai": 8,
      "KhoiLuongGiam": 28,
      "PhanTramGiam": 77.8
    },
    {
      "Danhba": "15122885899",
      "KyTruoc": 30,
      "KyHienTai": 2,
      "KhoiLuongGiam": 28,
      "PhanTramGiam": 93.3
    },
    {
      "Danhba": "15122848425",
      "KyTruoc": 36,
      "KyHienTai": 8,
      "KhoiLuongGiam": 28,
      "PhanTramGiam": 77.8
    },
    {
      "Danhba": "22043305472",
      "KyTruoc": 33,
      "KyHienTai": 5,
      "KhoiLuongGiam": 28,
      "PhanTramGiam": 84.8
    },
    {
      "Danhba": "22073230971",
      "KyTruoc": 29,
      "KyHienTai": 2,
      "KhoiLuongGiam": 27,
      "PhanTramGiam": 93.1
    },
    {
      "Danhba": "22073232375",
      "KyTruoc": 27,
      "KyHienTai": 0,
      "KhoiLuongGiam": 27,
      "PhanTramGiam": 100
    },
    {
      "Danhba": "15062139378",
      "KyTruoc": 31,
      "KyHienTai": 4,
      "KhoiLuongGiam": 27,
      "PhanTramGiam": 87.1
    },
    {
      "Danhba": "15062135755",
      "KyTruoc": 30,
      "KyHienTai": 3,
      "KhoiLuongGiam": 27,
      "PhanTramGiam": 90
    },
    {
      "Danhba": "15102723272",
      "KyTruoc": 27,
      "KyHienTai": 0,
      "KhoiLuongGiam": 27,
      "PhanTramGiam": 100
    },
    {
      "Danhba": "22073343404",
      "KyTruoc": 27,
      "KyHienTai": 0,
      "KhoiLuongGiam": 27,
      "PhanTramGiam": 100
    },
    {
      "Danhba": "22073342911",
      "KyTruoc": 26,
      "KyHienTai": 0,
      "KhoiLuongGiam": 26,
      "PhanTramGiam": 100
    },
    {
      "Danhba": "22103398317",
      "KyTruoc": 26,
      "KyHienTai": 0,
      "KhoiLuongGiam": 26,
      "PhanTramGiam": 100
    },
    {
      "Danhba": "15062135044",
      "KyTruoc": 26,
      "KyHienTai": 0,
      "KhoiLuongGiam": 26,
      "PhanTramGiam": 100
    },
    {
      "Danhba": "22073230130",
      "KyTruoc": 32,
      "KyHienTai": 6,
      "KhoiLuongGiam": 26,
      "PhanTramGiam": 81.3
    },
    {
      "Danhba": "22043307579",
      "KyTruoc": 30,
      "KyHienTai": 4,
      "KhoiLuongGiam": 26,
      "PhanTramGiam": 86.7
    },
    {
      "Danhba": "22043311342",
      "KyTruoc": 27,
      "KyHienTai": 1,
      "KhoiLuongGiam": 26,
      "PhanTramGiam": 96.3
    },
    {
      "Danhba": "22033279454",
      "KyTruoc": 26,
      "KyHienTai": 0,
      "KhoiLuongGiam": 26,
      "PhanTramGiam": 100
    },
    {
      "Danhba": "22033329646",
      "KyTruoc": 28,
      "KyHienTai": 2,
      "KhoiLuongGiam": 26,
      "PhanTramGiam": 92.9
    },
    {
      "Danhba": "22033275950",
      "KyTruoc": 26,
      "KyHienTai": 0,
      "KhoiLuongGiam": 26,
      "PhanTramGiam": 100
    },
    {
      "Danhba": "15122887892",
      "KyTruoc": 25,
      "KyHienTai": 0,
      "KhoiLuongGiam": 25,
      "PhanTramGiam": 100
    },
    {
      "Danhba": "15141950376",
      "KyTruoc": 31,
      "KyHienTai": 6,
      "KhoiLuongGiam": 25,
      "PhanTramGiam": 80.6
    },
    {
      "Danhba": "15122889953",
      "KyTruoc": 28,
      "KyHienTai": 3,
      "KhoiLuongGiam": 25,
      "PhanTramGiam": 89.3
    },
    {
      "Danhba": "22073343075",
      "KyTruoc": 30,
      "KyHienTai": 5,
      "KhoiLuongGiam": 25,
      "PhanTramGiam": 83.3
    },
    {
      "Danhba": "22103398259",
      "KyTruoc": 25,
      "KyHienTai": 0,
      "KhoiLuongGiam": 25,
      "PhanTramGiam": 100
    },
    {
      "Danhba": "22103399072",
      "KyTruoc": 25,
      "KyHienTai": 1,
      "KhoiLuongGiam": 24,
      "PhanTramGiam": 96
    },
    {
      "Danhba": "22103405571",
      "KyTruoc": 24,
      "KyHienTai": 0,
      "KhoiLuongGiam": 24,
      "PhanTramGiam": 100
    },
    {
      "Danhba": "15122862992",
      "KyTruoc": 24,
      "KyHienTai": 0,
      "KhoiLuongGiam": 24,
      "PhanTramGiam": 100
    },
    {
      "Danhba": "15122861170",
      "KyTruoc": 24,
      "KyHienTai": 0,
      "KhoiLuongGiam": 24,
      "PhanTramGiam": 100
    },
    {
      "Danhba": "15112843831",
      "KyTruoc": 29,
      "KyHienTai": 5,
      "KhoiLuongGiam": 24,
      "PhanTramGiam": 82.8
    },
    {
      "Danhba": "22033273804",
      "KyTruoc": 28,
      "KyHienTai": 4,
      "KhoiLuongGiam": 24,
      "PhanTramGiam": 85.7
    },
    {
      "Danhba": "15173421315",
      "KyTruoc": 30,
      "KyHienTai": 6,
      "KhoiLuongGiam": 24,
      "PhanTramGiam": 80
    },
    {
      "Danhba": "15141936479",
      "KyTruoc": 28,
      "KyHienTai": 4,
      "KhoiLuongGiam": 24,
      "PhanTramGiam": 85.7
    },
    {
      "Danhba": "22043298605",
      "KyTruoc": 25,
      "KyHienTai": 1,
      "KhoiLuongGiam": 24,
      "PhanTramGiam": 96
    },
    {
      "Danhba": "22043334490",
      "KyTruoc": 25,
      "KyHienTai": 1,
      "KhoiLuongGiam": 24,
      "PhanTramGiam": 96
    },
    {
      "Danhba": "22043307383",
      "KyTruoc": 31,
      "KyHienTai": 7,
      "KhoiLuongGiam": 24,
      "PhanTramGiam": 77.4
    },
    {
      "Danhba": "22073340619",
      "KyTruoc": 23,
      "KyHienTai": 0,
      "KhoiLuongGiam": 23,
      "PhanTramGiam": 100
    },
    {
      "Danhba": "22073341599",
      "KyTruoc": 25,
      "KyHienTai": 2,
      "KhoiLuongGiam": 23,
      "PhanTramGiam": 92
    },
    {
      "Danhba": "22073341932",
      "KyTruoc": 27,
      "KyHienTai": 4,
      "KhoiLuongGiam": 23,
      "PhanTramGiam": 85.2
    },
    {
      "Danhba": "22073342784",
      "KyTruoc": 26,
      "KyHienTai": 3,
      "KhoiLuongGiam": 23,
      "PhanTramGiam": 88.5
    },
    {
      "Danhba": "15122885328",
      "KyTruoc": 29,
      "KyHienTai": 6,
      "KhoiLuongGiam": 23,
      "PhanTramGiam": 79.3
    },
    {
      "Danhba": "15062138955",
      "KyTruoc": 23,
      "KyHienTai": 0,
      "KhoiLuongGiam": 23,
      "PhanTramGiam": 100
    },
    {
      "Danhba": "15062140056",
      "KyTruoc": 23,
      "KyHienTai": 0,
      "KhoiLuongGiam": 23,
      "PhanTramGiam": 100
    },
    {
      "Danhba": "15112827322",
      "KyTruoc": 23,
      "KyHienTai": 0,
      "KhoiLuongGiam": 23,
      "PhanTramGiam": 100
    },
    {
      "Danhba": "22103413370",
      "KyTruoc": 23,
      "KyHienTai": 0,
      "KhoiLuongGiam": 23,
      "PhanTramGiam": 100
    },
    {
      "Danhba": "22103410450",
      "KyTruoc": 22,
      "KyHienTai": 0,
      "KhoiLuongGiam": 22,
      "PhanTramGiam": 100
    },
    {
      "Danhba": "15112821346",
      "KyTruoc": 25,
      "KyHienTai": 3,
      "KhoiLuongGiam": 22,
      "PhanTramGiam": 88
    },
    {
      "Danhba": "15072461156",
      "KyTruoc": 22,
      "KyHienTai": 0,
      "KhoiLuongGiam": 22,
      "PhanTramGiam": 100
    },
    {
      "Danhba": "15122888180",
      "KyTruoc": 22,
      "KyHienTai": 0,
      "KhoiLuongGiam": 22,
      "PhanTramGiam": 100
    },
    {
      "Danhba": "15112846390",
      "KyTruoc": 22,
      "KyHienTai": 0,
      "KhoiLuongGiam": 22,
      "PhanTramGiam": 100
    },
    {
      "Danhba": "15122862732",
      "KyTruoc": 22,
      "KyHienTai": 0,
      "KhoiLuongGiam": 22,
      "PhanTramGiam": 100
    },
    {
      "Danhba": "15122861132",
      "KyTruoc": 22,
      "KyHienTai": 0,
      "KhoiLuongGiam": 22,
      "PhanTramGiam": 100
    },
    {
      "Danhba": "15112868621",
      "KyTruoc": 22,
      "KyHienTai": 0,
      "KhoiLuongGiam": 22,
      "PhanTramGiam": 100
    },
    {
      "Danhba": "22073342526",
      "KyTruoc": 27,
      "KyHienTai": 5,
      "KhoiLuongGiam": 22,
      "PhanTramGiam": 81.5
    },
    {
      "Danhba": "22073239567",
      "KyTruoc": 22,
      "KyHienTai": 0,
      "KhoiLuongGiam": 22,
      "PhanTramGiam": 100
    },
    {
      "Danhba": "22033279353",
      "KyTruoc": 27,
      "KyHienTai": 5,
      "KhoiLuongGiam": 22,
      "PhanTramGiam": 81.5
    },
    {
      "Danhba": "22033272834",
      "KyTruoc": 27,
      "KyHienTai": 6,
      "KhoiLuongGiam": 21,
      "PhanTramGiam": 77.8
    },
    {
      "Danhba": "22033330532",
      "KyTruoc": 21,
      "KyHienTai": 0,
      "KhoiLuongGiam": 21,
      "PhanTramGiam": 100
    },
    {
      "Danhba": "22033332638",
      "KyTruoc": 25,
      "KyHienTai": 4,
      "KhoiLuongGiam": 21,
      "PhanTramGiam": 84
    },
    {
      "Danhba": "22073340114",
      "KyTruoc": 21,
      "KyHienTai": 0,
      "KhoiLuongGiam": 21,
      "PhanTramGiam": 100
    },
    {
      "Danhba": "22073230950",
      "KyTruoc": 21,
      "KyHienTai": 0,
      "KhoiLuongGiam": 21,
      "PhanTramGiam": 100
    },
    {
      "Danhba": "15122890752",
      "KyTruoc": 25,
      "KyHienTai": 4,
      "KhoiLuongGiam": 21,
      "PhanTramGiam": 84
    },
    {
      "Danhba": "15122891185",
      "KyTruoc": 25,
      "KyHienTai": 4,
      "KhoiLuongGiam": 21,
      "PhanTramGiam": 84
    },
    {
      "Danhba": "22103408000",
      "KyTruoc": 22,
      "KyHienTai": 1,
      "KhoiLuongGiam": 21,
      "PhanTramGiam": 95.5
    },
    {
      "Danhba": "22103399306",
      "KyTruoc": 21,
      "KyHienTai": 1,
      "KhoiLuongGiam": 20,
      "PhanTramGiam": 95.2
    },
    {
      "Danhba": "22103390489",
      "KyTruoc": 22,
      "KyHienTai": 2,
      "KhoiLuongGiam": 20,
      "PhanTramGiam": 90.9
    },
    {
      "Danhba": "15122885060",
      "KyTruoc": 24,
      "KyHienTai": 4,
      "KhoiLuongGiam": 20,
      "PhanTramGiam": 83.3
    },
    {
      "Danhba": "15112868615",
      "KyTruoc": 20,
      "KyHienTai": 0,
      "KhoiLuongGiam": 20,
      "PhanTramGiam": 100
    },
    {
      "Danhba": "15112828234",
      "KyTruoc": 25,
      "KyHienTai": 5,
      "KhoiLuongGiam": 20,
      "PhanTramGiam": 80
    },
    {
      "Danhba": "15072427901",
      "KyTruoc": 20,
      "KyHienTai": 0,
      "KhoiLuongGiam": 20,
      "PhanTramGiam": 100
    },
    {
      "Danhba": "15073426565",
      "KyTruoc": 20,
      "KyHienTai": 0,
      "KhoiLuongGiam": 20,
      "PhanTramGiam": 100
    },
    {
      "Danhba": "15092623119",
      "KyTruoc": 20,
      "KyHienTai": 0,
      "KhoiLuongGiam": 20,
      "PhanTramGiam": 100
    },
    {
      "Danhba": "15112822513",
      "KyTruoc": 25,
      "KyHienTai": 5,
      "KhoiLuongGiam": 20,
      "PhanTramGiam": 80
    },
    {
      "Danhba": "15112825513",
      "KyTruoc": 23,
      "KyHienTai": 3,
      "KhoiLuongGiam": 20,
      "PhanTramGiam": 87
    },
    {
      "Danhba": "22073340197",
      "KyTruoc": 22,
      "KyHienTai": 2,
      "KhoiLuongGiam": 20,
      "PhanTramGiam": 90.9
    },
    {
      "Danhba": "22073240991",
      "KyTruoc": 24,
      "KyHienTai": 4,
      "KhoiLuongGiam": 20,
      "PhanTramGiam": 83.3
    },
    {
      "Danhba": "22043307445",
      "KyTruoc": 26,
      "KyHienTai": 6,
      "KhoiLuongGiam": 20,
      "PhanTramGiam": 76.9
    },
    {
      "Danhba": "22043309084",
      "KyTruoc": 26,
      "KyHienTai": 6,
      "KhoiLuongGiam": 20,
      "PhanTramGiam": 76.9
    },
    {
      "Danhba": "22043313982",
      "KyTruoc": 24,
      "KyHienTai": 4,
      "KhoiLuongGiam": 20,
      "PhanTramGiam": 83.3
    },
    {
      "Danhba": "22043314280",
      "KyTruoc": 23,
      "KyHienTai": 3,
      "KhoiLuongGiam": 20,
      "PhanTramGiam": 87
    },
    {
      "Danhba": "22043305143",
      "KyTruoc": 20,
      "KyHienTai": 0,
      "KhoiLuongGiam": 20,
      "PhanTramGiam": 100
    },
    {
      "Danhba": "22043305273",
      "KyTruoc": 20,
      "KyHienTai": 0,
      "KhoiLuongGiam": 20,
      "PhanTramGiam": 100
    },
    {
      "Danhba": "22043301607",
      "KyTruoc": 22,
      "KyHienTai": 2,
      "KhoiLuongGiam": 20,
      "PhanTramGiam": 90.9
    },
    {
      "Danhba": "22033332469",
      "KyTruoc": 20,
      "KyHienTai": 1,
      "KhoiLuongGiam": 19,
      "PhanTramGiam": 95
    },
    {
      "Danhba": "22033275168",
      "KyTruoc": 19,
      "KyHienTai": 0,
      "KhoiLuongGiam": 19,
      "PhanTramGiam": 100
    },
    {
      "Danhba": "22043310915",
      "KyTruoc": 19,
      "KyHienTai": 0,
      "KhoiLuongGiam": 19,
      "PhanTramGiam": 100
    },
    {
      "Danhba": "22073342629",
      "KyTruoc": 19,
      "KyHienTai": 0,
      "KhoiLuongGiam": 19,
      "PhanTramGiam": 100
    },
    {
      "Danhba": "22073239231",
      "KyTruoc": 21,
      "KyHienTai": 2,
      "KhoiLuongGiam": 19,
      "PhanTramGiam": 90.5
    },
    {
      "Danhba": "22043320052",
      "KyTruoc": 21,
      "KyHienTai": 2,
      "KhoiLuongGiam": 19,
      "PhanTramGiam": 90.5
    },
    {
      "Danhba": "15072420062",
      "KyTruoc": 23,
      "KyHienTai": 4,
      "KhoiLuongGiam": 19,
      "PhanTramGiam": 82.6
    },
    {
      "Danhba": "15062141307",
      "KyTruoc": 19,
      "KyHienTai": 0,
      "KhoiLuongGiam": 19,
      "PhanTramGiam": 100
    },
    {
      "Danhba": "15062139709",
      "KyTruoc": 21,
      "KyHienTai": 2,
      "KhoiLuongGiam": 19,
      "PhanTramGiam": 90.5
    },
    {
      "Danhba": "15031710349",
      "KyTruoc": 20,
      "KyHienTai": 1,
      "KhoiLuongGiam": 19,
      "PhanTramGiam": 95
    },
    {
      "Danhba": "15042021427",
      "KyTruoc": 19,
      "KyHienTai": 0,
      "KhoiLuongGiam": 19,
      "PhanTramGiam": 100
    },
    {
      "Danhba": "15112865379",
      "KyTruoc": 22,
      "KyHienTai": 3,
      "KhoiLuongGiam": 19,
      "PhanTramGiam": 86.4
    },
    {
      "Danhba": "15112867299",
      "KyTruoc": 20,
      "KyHienTai": 1,
      "KhoiLuongGiam": 19,
      "PhanTramGiam": 95
    },
    {
      "Danhba": "15122883346",
      "KyTruoc": 21,
      "KyHienTai": 2,
      "KhoiLuongGiam": 19,
      "PhanTramGiam": 90.5
    },
    {
      "Danhba": "15141931248",
      "KyTruoc": 25,
      "KyHienTai": 6,
      "KhoiLuongGiam": 19,
      "PhanTramGiam": 76
    },
    {
      "Danhba": "22103390150",
      "KyTruoc": 19,
      "KyHienTai": 0,
      "KhoiLuongGiam": 19,
      "PhanTramGiam": 100
    },
    {
      "Danhba": "22103391306",
      "KyTruoc": 25,
      "KyHienTai": 6,
      "KhoiLuongGiam": 19,
      "PhanTramGiam": 76
    },
    {
      "Danhba": "22103396177",
      "KyTruoc": 19,
      "KyHienTai": 0,
      "KhoiLuongGiam": 19,
      "PhanTramGiam": 100
    },
    {
      "Danhba": "22103398782",
      "KyTruoc": 19,
      "KyHienTai": 0,
      "KhoiLuongGiam": 19,
      "PhanTramGiam": 100
    },
    {
      "Danhba": "22103411357",
      "KyTruoc": 24,
      "KyHienTai": 5,
      "KhoiLuongGiam": 19,
      "PhanTramGiam": 79.2
    },
    {
      "Danhba": "22103411323",
      "KyTruoc": 20,
      "KyHienTai": 2,
      "KhoiLuongGiam": 18,
      "PhanTramGiam": 90
    },
    {
      "Danhba": "22103398475",
      "KyTruoc": 23,
      "KyHienTai": 5,
      "KhoiLuongGiam": 18,
      "PhanTramGiam": 78.3
    },
    {
      "Danhba": "22103396541",
      "KyTruoc": 21,
      "KyHienTai": 3,
      "KhoiLuongGiam": 18,
      "PhanTramGiam": 85.7
    },
    {
      "Danhba": "15122890976",
      "KyTruoc": 22,
      "KyHienTai": 4,
      "KhoiLuongGiam": 18,
      "PhanTramGiam": 81.8
    },
    {
      "Danhba": "15122888209",
      "KyTruoc": 18,
      "KyHienTai": 0,
      "KhoiLuongGiam": 18,
      "PhanTramGiam": 100
    },
    {
      "Danhba": "15112862223",
      "KyTruoc": 18,
      "KyHienTai": 0,
      "KhoiLuongGiam": 18,
      "PhanTramGiam": 100
    },
    {
      "Danhba": "15112840741",
      "KyTruoc": 20,
      "KyHienTai": 2,
      "KhoiLuongGiam": 18,
      "PhanTramGiam": 90
    },
    {
      "Danhba": "15062130179",
      "KyTruoc": 23,
      "KyHienTai": 5,
      "KhoiLuongGiam": 18,
      "PhanTramGiam": 78.3
    },
    {
      "Danhba": "15062130186",
      "KyTruoc": 18,
      "KyHienTai": 0,
      "KhoiLuongGiam": 18,
      "PhanTramGiam": 100
    },
    {
      "Danhba": "15062141308",
      "KyTruoc": 18,
      "KyHienTai": 0,
      "KhoiLuongGiam": 18,
      "PhanTramGiam": 100
    },
    {
      "Danhba": "15112828040",
      "KyTruoc": 18,
      "KyHienTai": 0,
      "KhoiLuongGiam": 18,
      "PhanTramGiam": 100
    },
    {
      "Danhba": "15102720183",
      "KyTruoc": 18,
      "KyHienTai": 0,
      "KhoiLuongGiam": 18,
      "PhanTramGiam": 100
    },
    {
      "Danhba": "22073230798",
      "KyTruoc": 18,
      "KyHienTai": 0,
      "KhoiLuongGiam": 18,
      "PhanTramGiam": 100
    },
    {
      "Danhba": "22043311185",
      "KyTruoc": 21,
      "KyHienTai": 3,
      "KhoiLuongGiam": 18,
      "PhanTramGiam": 85.7
    },
    {
      "Danhba": "22043308406",
      "KyTruoc": 21,
      "KyHienTai": 3,
      "KhoiLuongGiam": 18,
      "PhanTramGiam": 85.7
    },
    {
      "Danhba": "22043314503",
      "KyTruoc": 21,
      "KyHienTai": 3,
      "KhoiLuongGiam": 18,
      "PhanTramGiam": 85.7
    },
    {
      "Danhba": "22033275212",
      "KyTruoc": 21,
      "KyHienTai": 3,
      "KhoiLuongGiam": 18,
      "PhanTramGiam": 85.7
    },
    {
      "Danhba": "22033272656",
      "KyTruoc": 20,
      "KyHienTai": 2,
      "KhoiLuongGiam": 18,
      "PhanTramGiam": 90
    },
    {
      "Danhba": "22033275668",
      "KyTruoc": 18,
      "KyHienTai": 0,
      "KhoiLuongGiam": 18,
      "PhanTramGiam": 100
    },
    {
      "Danhba": "22033278561",
      "KyTruoc": 21,
      "KyHienTai": 3,
      "KhoiLuongGiam": 18,
      "PhanTramGiam": 85.7
    },
    {
      "Danhba": "22033332481",
      "KyTruoc": 21,
      "KyHienTai": 3,
      "KhoiLuongGiam": 18,
      "PhanTramGiam": 85.7
    },
    {
      "Danhba": "22033333731",
      "KyTruoc": 19,
      "KyHienTai": 1,
      "KhoiLuongGiam": 18,
      "PhanTramGiam": 94.7
    },
    {
      "Danhba": "22043300748",
      "KyTruoc": 19,
      "KyHienTai": 1,
      "KhoiLuongGiam": 18,
      "PhanTramGiam": 94.7
    },
    {
      "Danhba": "22033334085",
      "KyTruoc": 19,
      "KyHienTai": 1,
      "KhoiLuongGiam": 18,
      "PhanTramGiam": 94.7
    },
    {
      "Danhba": "22033334003",
      "KyTruoc": 21,
      "KyHienTai": 4,
      "KhoiLuongGiam": 17,
      "PhanTramGiam": 81
    },
    {
      "Danhba": "22043304413",
      "KyTruoc": 21,
      "KyHienTai": 4,
      "KhoiLuongGiam": 17,
      "PhanTramGiam": 81
    },
    {
      "Danhba": "22043304767",
      "KyTruoc": 17,
      "KyHienTai": 0,
      "KhoiLuongGiam": 17,
      "PhanTramGiam": 100
    },
    {
      "Danhba": "22033331284",
      "KyTruoc": 19,
      "KyHienTai": 2,
      "KhoiLuongGiam": 17,
      "PhanTramGiam": 89.5
    },
    {
      "Danhba": "22043313018",
      "KyTruoc": 17,
      "KyHienTai": 0,
      "KhoiLuongGiam": 17,
      "PhanTramGiam": 100
    },
    {
      "Danhba": "22043334491",
      "KyTruoc": 20,
      "KyHienTai": 3,
      "KhoiLuongGiam": 17,
      "PhanTramGiam": 85
    },
    {
      "Danhba": "22043305557",
      "KyTruoc": 17,
      "KyHienTai": 0,
      "KhoiLuongGiam": 17,
      "PhanTramGiam": 100
    },
    {
      "Danhba": "22073230628",
      "KyTruoc": 17,
      "KyHienTai": 0,
      "KhoiLuongGiam": 17,
      "PhanTramGiam": 100
    },
    {
      "Danhba": "15102720306",
      "KyTruoc": 17,
      "KyHienTai": 0,
      "KhoiLuongGiam": 17,
      "PhanTramGiam": 100
    },
    {
      "Danhba": "15102720905",
      "KyTruoc": 21,
      "KyHienTai": 4,
      "KhoiLuongGiam": 17,
      "PhanTramGiam": 81
    },
    {
      "Danhba": "15062141139",
      "KyTruoc": 22,
      "KyHienTai": 5,
      "KhoiLuongGiam": 17,
      "PhanTramGiam": 77.3
    },
    {
      "Danhba": "15062138945",
      "KyTruoc": 17,
      "KyHienTai": 0,
      "KhoiLuongGiam": 17,
      "PhanTramGiam": 100
    },
    {
      "Danhba": "15112828760",
      "KyTruoc": 17,
      "KyHienTai": 0,
      "KhoiLuongGiam": 17,
      "PhanTramGiam": 100
    },
    {
      "Danhba": "15112841057",
      "KyTruoc": 20,
      "KyHienTai": 3,
      "KhoiLuongGiam": 17,
      "PhanTramGiam": 85
    },
    {
      "Danhba": "22103393279",
      "KyTruoc": 17,
      "KyHienTai": 0,
      "KhoiLuongGiam": 17,
      "PhanTramGiam": 100
    },
    {
      "Danhba": "22073343108",
      "KyTruoc": 17,
      "KyHienTai": 0,
      "KhoiLuongGiam": 17,
      "PhanTramGiam": 100
    },
    {
      "Danhba": "22073343257",
      "KyTruoc": 22,
      "KyHienTai": 5,
      "KhoiLuongGiam": 17,
      "PhanTramGiam": 77.3
    },
    {
      "Danhba": "22103413752",
      "KyTruoc": 20,
      "KyHienTai": 3,
      "KhoiLuongGiam": 17,
      "PhanTramGiam": 85
    },
    {
      "Danhba": "22103391002",
      "KyTruoc": 18,
      "KyHienTai": 2,
      "KhoiLuongGiam": 16,
      "PhanTramGiam": 88.9
    },
    {
      "Danhba": "22103401105",
      "KyTruoc": 16,
      "KyHienTai": 0,
      "KhoiLuongGiam": 16,
      "PhanTramGiam": 100
    },
    {
      "Danhba": "22103408699",
      "KyTruoc": 20,
      "KyHienTai": 4,
      "KhoiLuongGiam": 16,
      "PhanTramGiam": 80
    },
    {
      "Danhba": "22103410467",
      "KyTruoc": 16,
      "KyHienTai": 0,
      "KhoiLuongGiam": 16,
      "PhanTramGiam": 100
    },
    {
      "Danhba": "15112841367",
      "KyTruoc": 16,
      "KyHienTai": 0,
      "KhoiLuongGiam": 16,
      "PhanTramGiam": 100
    },
    {
      "Danhba": "15112840911",
      "KyTruoc": 16,
      "KyHienTai": 0,
      "KhoiLuongGiam": 16,
      "PhanTramGiam": 100
    },
    {
      "Danhba": "15112867003",
      "KyTruoc": 16,
      "KyHienTai": 0,
      "KhoiLuongGiam": 16,
      "PhanTramGiam": 100
    },
    {
      "Danhba": "15122888965",
      "KyTruoc": 16,
      "KyHienTai": 0,
      "KhoiLuongGiam": 16,
      "PhanTramGiam": 100
    },
    {
      "Danhba": "15122886845",
      "KyTruoc": 18,
      "KyHienTai": 2,
      "KhoiLuongGiam": 16,
      "PhanTramGiam": 88.9
    },
    {
      "Danhba": "15122884778",
      "KyTruoc": 20,
      "KyHienTai": 4,
      "KhoiLuongGiam": 16,
      "PhanTramGiam": 80
    },
    {
      "Danhba": "15122890178",
      "KyTruoc": 17,
      "KyHienTai": 1,
      "KhoiLuongGiam": 16,
      "PhanTramGiam": 94.1
    },
    {
      "Danhba": "15141934186",
      "KyTruoc": 16,
      "KyHienTai": 0,
      "KhoiLuongGiam": 16,
      "PhanTramGiam": 100
    },
    {
      "Danhba": "15141950378",
      "KyTruoc": 16,
      "KyHienTai": 0,
      "KhoiLuongGiam": 16,
      "PhanTramGiam": 100
    },
    {
      "Danhba": "15072426786",
      "KyTruoc": 17,
      "KyHienTai": 1,
      "KhoiLuongGiam": 16,
      "PhanTramGiam": 94.1
    },
    {
      "Danhba": "15072441746",
      "KyTruoc": 16,
      "KyHienTai": 0,
      "KhoiLuongGiam": 16,
      "PhanTramGiam": 100
    },
    {
      "Danhba": "15072448521",
      "KyTruoc": 21,
      "KyHienTai": 5,
      "KhoiLuongGiam": 16,
      "PhanTramGiam": 76.2
    },
    {
      "Danhba": "15112823867",
      "KyTruoc": 16,
      "KyHienTai": 0,
      "KhoiLuongGiam": 16,
      "PhanTramGiam": 100
    },
    {
      "Danhba": "22073239485",
      "KyTruoc": 17,
      "KyHienTai": 1,
      "KhoiLuongGiam": 16,
      "PhanTramGiam": 94.1
    },
    {
      "Danhba": "22073240124",
      "KyTruoc": 16,
      "KyHienTai": 0,
      "KhoiLuongGiam": 16,
      "PhanTramGiam": 100
    },
    {
      "Danhba": "22073240215",
      "KyTruoc": 16,
      "KyHienTai": 0,
      "KhoiLuongGiam": 16,
      "PhanTramGiam": 100
    },
    {
      "Danhba": "22073240933",
      "KyTruoc": 16,
      "KyHienTai": 0,
      "KhoiLuongGiam": 16,
      "PhanTramGiam": 100
    },
    {
      "Danhba": "22043307349",
      "KyTruoc": 17,
      "KyHienTai": 1,
      "KhoiLuongGiam": 16,
      "PhanTramGiam": 94.1
    },
    {
      "Danhba": "22043308490",
      "KyTruoc": 21,
      "KyHienTai": 5,
      "KhoiLuongGiam": 16,
      "PhanTramGiam": 76.2
    },
    {
      "Danhba": "22043309911",
      "KyTruoc": 17,
      "KyHienTai": 1,
      "KhoiLuongGiam": 16,
      "PhanTramGiam": 94.1
    },
    {
      "Danhba": "22043309530",
      "KyTruoc": 16,
      "KyHienTai": 0,
      "KhoiLuongGiam": 16,
      "PhanTramGiam": 100
    },
    {
      "Danhba": "22043311417",
      "KyTruoc": 16,
      "KyHienTai": 0,
      "KhoiLuongGiam": 16,
      "PhanTramGiam": 100
    },
    {
      "Danhba": "22033330279",
      "KyTruoc": 18,
      "KyHienTai": 2,
      "KhoiLuongGiam": 16,
      "PhanTramGiam": 88.9
    },
    {
      "Danhba": "22033329440",
      "KyTruoc": 17,
      "KyHienTai": 1,
      "KhoiLuongGiam": 16,
      "PhanTramGiam": 94.1
    },
    {
      "Danhba": "22033331889",
      "KyTruoc": 16,
      "KyHienTai": 0,
      "KhoiLuongGiam": 16,
      "PhanTramGiam": 100
    },
    {
      "Danhba": "22043278575",
      "KyTruoc": 16,
      "KyHienTai": 0,
      "KhoiLuongGiam": 16,
      "PhanTramGiam": 100
    },
    {
      "Danhba": "22033255964",
      "KyTruoc": 16,
      "KyHienTai": 0,
      "KhoiLuongGiam": 16,
      "PhanTramGiam": 100
    }
  ],
  "nguong": {
    "roRiPct": ">300%",
    "roRiM3": ">15m³",
    "ketCoPct": ">75%",
    "ketCoM3": ">15m³"
  },
  "tienDo": {
    "tongDH": 246859,
    "daDoc": 86699,
    "chuaDoc": 160160,
    "pct": 35
  }
};
