// Auto-generated by fetch_abnormal_data.js – 10:20:19 6/5/2026
// Nguồn: SANLUONGDONGHOKHACHHANG SQL Server 192.168.17.19
const TAWACO_BATTHUONG = {
  "lastUpdated": "10:20:19 6/5/2026",
  "nguonDuLieu": "SANLUONGDONGHOKHACHHANG – Kỳ 05 / Năm 2026",
  "nam": 2026,
  "ky": "05",
  "tongSoKH": 30140,
  "leakCount": 151,
  "stuckCount": 114,
  "leakTop": [
    {
      "Danhba": "22033275303",
      "KyTruoc": 12,
      "KyHienTai": 681,
      "KhoiLuongTang": 669,
      "PhanTramTang": 5575
    },
    {
      "Danhba": "22043303367",
      "KyTruoc": 77,
      "KyHienTai": 447,
      "KhoiLuongTang": 370,
      "PhanTramTang": 480.5
    },
    {
      "Danhba": "15112866004",
      "KyTruoc": 20,
      "KyHienTai": 371,
      "KhoiLuongTang": 351,
      "PhanTramTang": 1755
    },
    {
      "Danhba": "15062130190",
      "KyTruoc": 58,
      "KyHienTai": 378,
      "KhoiLuongTang": 320,
      "PhanTramTang": 551.7
    },
    {
      "Danhba": "22043310051",
      "KyTruoc": 11,
      "KyHienTai": 295,
      "KhoiLuongTang": 284,
      "PhanTramTang": 2581.8
    },
    {
      "Danhba": "15062140023",
      "KyTruoc": 26,
      "KyHienTai": 235,
      "KhoiLuongTang": 209,
      "PhanTramTang": 803.8
    },
    {
      "Danhba": "22033278729",
      "KyTruoc": 21,
      "KyHienTai": 222,
      "KhoiLuongTang": 201,
      "PhanTramTang": 957.1
    },
    {
      "Danhba": "15062133370",
      "KyTruoc": 5,
      "KyHienTai": 161,
      "KhoiLuongTang": 156,
      "PhanTramTang": 3120
    },
    {
      "Danhba": "22103410706",
      "KyTruoc": 18,
      "KyHienTai": 169,
      "KhoiLuongTang": 151,
      "PhanTramTang": 838.9
    },
    {
      "Danhba": "22103413833",
      "KyTruoc": 19,
      "KyHienTai": 158,
      "KhoiLuongTang": 139,
      "PhanTramTang": 731.6
    },
    {
      "Danhba": "15112867395",
      "KyTruoc": 3,
      "KyHienTai": 118,
      "KhoiLuongTang": 115,
      "PhanTramTang": 3833.3
    },
    {
      "Danhba": "15112862577",
      "KyTruoc": 21,
      "KyHienTai": 127,
      "KhoiLuongTang": 106,
      "PhanTramTang": 504.8
    },
    {
      "Danhba": "22033273377",
      "KyTruoc": 2,
      "KyHienTai": 103,
      "KhoiLuongTang": 101,
      "PhanTramTang": 5050
    },
    {
      "Danhba": "22033279474",
      "KyTruoc": 15,
      "KyHienTai": 114,
      "KhoiLuongTang": 99,
      "PhanTramTang": 660
    },
    {
      "Danhba": "22103412227",
      "KyTruoc": 25,
      "KyHienTai": 121,
      "KhoiLuongTang": 96,
      "PhanTramTang": 384
    },
    {
      "Danhba": "22043312473",
      "KyTruoc": 1,
      "KyHienTai": 89,
      "KhoiLuongTang": 88,
      "PhanTramTang": 8800
    },
    {
      "Danhba": "22033278848",
      "KyTruoc": 6,
      "KyHienTai": 94,
      "KhoiLuongTang": 88,
      "PhanTramTang": 1466.7
    },
    {
      "Danhba": "15122880834",
      "KyTruoc": 3,
      "KyHienTai": 91,
      "KhoiLuongTang": 88,
      "PhanTramTang": 2933.3
    },
    {
      "Danhba": "22103391764",
      "KyTruoc": 21,
      "KyHienTai": 107,
      "KhoiLuongTang": 86,
      "PhanTramTang": 409.5
    },
    {
      "Danhba": "22043290775",
      "KyTruoc": 24,
      "KyHienTai": 102,
      "KhoiLuongTang": 78,
      "PhanTramTang": 325
    },
    {
      "Danhba": "15062134426",
      "KyTruoc": 2,
      "KyHienTai": 78,
      "KhoiLuongTang": 76,
      "PhanTramTang": 3800
    },
    {
      "Danhba": "15112829375",
      "KyTruoc": 1,
      "KyHienTai": 76,
      "KhoiLuongTang": 75,
      "PhanTramTang": 7500
    },
    {
      "Danhba": "15122890171",
      "KyTruoc": 1,
      "KyHienTai": 71,
      "KhoiLuongTang": 70,
      "PhanTramTang": 7000
    },
    {
      "Danhba": "15062140376",
      "KyTruoc": 4,
      "KyHienTai": 73,
      "KhoiLuongTang": 69,
      "PhanTramTang": 1725
    },
    {
      "Danhba": "22103411908",
      "KyTruoc": 22,
      "KyHienTai": 89,
      "KhoiLuongTang": 67,
      "PhanTramTang": 304.5
    },
    {
      "Danhba": "22033275934",
      "KyTruoc": 13,
      "KyHienTai": 78,
      "KhoiLuongTang": 65,
      "PhanTramTang": 500
    },
    {
      "Danhba": "22033332866",
      "KyTruoc": 17,
      "KyHienTai": 80,
      "KhoiLuongTang": 63,
      "PhanTramTang": 370.6
    },
    {
      "Danhba": "15112862451",
      "KyTruoc": 11,
      "KyHienTai": 74,
      "KhoiLuongTang": 63,
      "PhanTramTang": 572.7
    },
    {
      "Danhba": "15161925331",
      "KyTruoc": 2,
      "KyHienTai": 61,
      "KhoiLuongTang": 59,
      "PhanTramTang": 2950
    },
    {
      "Danhba": "22043303003",
      "KyTruoc": 1,
      "KyHienTai": 57,
      "KhoiLuongTang": 56,
      "PhanTramTang": 5600
    },
    {
      "Danhba": "22103413953",
      "KyTruoc": 4,
      "KyHienTai": 55,
      "KhoiLuongTang": 51,
      "PhanTramTang": 1275
    },
    {
      "Danhba": "22033274436",
      "KyTruoc": 14,
      "KyHienTai": 64,
      "KhoiLuongTang": 50,
      "PhanTramTang": 357.1
    },
    {
      "Danhba": "15122890553",
      "KyTruoc": 13,
      "KyHienTai": 63,
      "KhoiLuongTang": 50,
      "PhanTramTang": 384.6
    },
    {
      "Danhba": "15122842564",
      "KyTruoc": 6,
      "KyHienTai": 54,
      "KhoiLuongTang": 48,
      "PhanTramTang": 800
    },
    {
      "Danhba": "22033273578",
      "KyTruoc": 13,
      "KyHienTai": 58,
      "KhoiLuongTang": 45,
      "PhanTramTang": 346.2
    },
    {
      "Danhba": "22103408440",
      "KyTruoc": 14,
      "KyHienTai": 57,
      "KhoiLuongTang": 43,
      "PhanTramTang": 307.1
    },
    {
      "Danhba": "15112828718",
      "KyTruoc": 6,
      "KyHienTai": 49,
      "KhoiLuongTang": 43,
      "PhanTramTang": 716.7
    },
    {
      "Danhba": "15122891275",
      "KyTruoc": 4,
      "KyHienTai": 46,
      "KhoiLuongTang": 42,
      "PhanTramTang": 1050
    },
    {
      "Danhba": "22033275985",
      "KyTruoc": 7,
      "KyHienTai": 49,
      "KhoiLuongTang": 42,
      "PhanTramTang": 600
    },
    {
      "Danhba": "22103408381",
      "KyTruoc": 10,
      "KyHienTai": 50,
      "KhoiLuongTang": 40,
      "PhanTramTang": 400
    },
    {
      "Danhba": "22033277245",
      "KyTruoc": 3,
      "KyHienTai": 42,
      "KhoiLuongTang": 39,
      "PhanTramTang": 1300
    },
    {
      "Danhba": "22043314232",
      "KyTruoc": 3,
      "KyHienTai": 42,
      "KhoiLuongTang": 39,
      "PhanTramTang": 1300
    },
    {
      "Danhba": "15062134520",
      "KyTruoc": 9,
      "KyHienTai": 48,
      "KhoiLuongTang": 39,
      "PhanTramTang": 433.3
    },
    {
      "Danhba": "15112847010",
      "KyTruoc": 12,
      "KyHienTai": 51,
      "KhoiLuongTang": 39,
      "PhanTramTang": 325
    },
    {
      "Danhba": "15112842471",
      "KyTruoc": 5,
      "KyHienTai": 43,
      "KhoiLuongTang": 38,
      "PhanTramTang": 760
    },
    {
      "Danhba": "15161907941",
      "KyTruoc": 8,
      "KyHienTai": 45,
      "KhoiLuongTang": 37,
      "PhanTramTang": 462.5
    },
    {
      "Danhba": "15173420211",
      "KyTruoc": 12,
      "KyHienTai": 49,
      "KhoiLuongTang": 37,
      "PhanTramTang": 308.3
    },
    {
      "Danhba": "22043313277",
      "KyTruoc": 4,
      "KyHienTai": 41,
      "KhoiLuongTang": 37,
      "PhanTramTang": 925
    },
    {
      "Danhba": "22103393127",
      "KyTruoc": 10,
      "KyHienTai": 47,
      "KhoiLuongTang": 37,
      "PhanTramTang": 370
    },
    {
      "Danhba": "22033277980",
      "KyTruoc": 6,
      "KyHienTai": 43,
      "KhoiLuongTang": 37,
      "PhanTramTang": 616.7
    },
    {
      "Danhba": "22043290915",
      "KyTruoc": 10,
      "KyHienTai": 46,
      "KhoiLuongTang": 36,
      "PhanTramTang": 360
    },
    {
      "Danhba": "22043309793",
      "KyTruoc": 8,
      "KyHienTai": 43,
      "KhoiLuongTang": 35,
      "PhanTramTang": 437.5
    },
    {
      "Danhba": "22103414007",
      "KyTruoc": 4,
      "KyHienTai": 39,
      "KhoiLuongTang": 35,
      "PhanTramTang": 875
    },
    {
      "Danhba": "22033330178",
      "KyTruoc": 3,
      "KyHienTai": 38,
      "KhoiLuongTang": 35,
      "PhanTramTang": 1166.7
    },
    {
      "Danhba": "22033330729",
      "KyTruoc": 9,
      "KyHienTai": 43,
      "KhoiLuongTang": 34,
      "PhanTramTang": 377.8
    },
    {
      "Danhba": "15122881480",
      "KyTruoc": 3,
      "KyHienTai": 37,
      "KhoiLuongTang": 34,
      "PhanTramTang": 1133.3
    },
    {
      "Danhba": "15112862513",
      "KyTruoc": 3,
      "KyHienTai": 36,
      "KhoiLuongTang": 33,
      "PhanTramTang": 1100
    },
    {
      "Danhba": "15112844309",
      "KyTruoc": 2,
      "KyHienTai": 35,
      "KhoiLuongTang": 33,
      "PhanTramTang": 1650
    },
    {
      "Danhba": "15112846586",
      "KyTruoc": 2,
      "KyHienTai": 35,
      "KhoiLuongTang": 33,
      "PhanTramTang": 1650
    },
    {
      "Danhba": "22033330242",
      "KyTruoc": 8,
      "KyHienTai": 41,
      "KhoiLuongTang": 33,
      "PhanTramTang": 412.5
    },
    {
      "Danhba": "22103412070",
      "KyTruoc": 8,
      "KyHienTai": 41,
      "KhoiLuongTang": 33,
      "PhanTramTang": 412.5
    },
    {
      "Danhba": "22103398668",
      "KyTruoc": 5,
      "KyHienTai": 38,
      "KhoiLuongTang": 33,
      "PhanTramTang": 660
    },
    {
      "Danhba": "22043313755",
      "KyTruoc": 3,
      "KyHienTai": 35,
      "KhoiLuongTang": 32,
      "PhanTramTang": 1066.7
    },
    {
      "Danhba": "22033276026",
      "KyTruoc": 1,
      "KyHienTai": 33,
      "KhoiLuongTang": 32,
      "PhanTramTang": 3200
    },
    {
      "Danhba": "15062138271",
      "KyTruoc": 7,
      "KyHienTai": 38,
      "KhoiLuongTang": 31,
      "PhanTramTang": 442.9
    },
    {
      "Danhba": "15062138875",
      "KyTruoc": 7,
      "KyHienTai": 38,
      "KhoiLuongTang": 31,
      "PhanTramTang": 442.9
    },
    {
      "Danhba": "15122880774",
      "KyTruoc": 7,
      "KyHienTai": 37,
      "KhoiLuongTang": 30,
      "PhanTramTang": 428.6
    },
    {
      "Danhba": "22043314279",
      "KyTruoc": 6,
      "KyHienTai": 36,
      "KhoiLuongTang": 30,
      "PhanTramTang": 500
    },
    {
      "Danhba": "22033279157",
      "KyTruoc": 6,
      "KyHienTai": 35,
      "KhoiLuongTang": 29,
      "PhanTramTang": 483.3
    },
    {
      "Danhba": "15112866772",
      "KyTruoc": 5,
      "KyHienTai": 34,
      "KhoiLuongTang": 29,
      "PhanTramTang": 580
    },
    {
      "Danhba": "15122886971",
      "KyTruoc": 4,
      "KyHienTai": 33,
      "KhoiLuongTang": 29,
      "PhanTramTang": 725
    },
    {
      "Danhba": "15062141065",
      "KyTruoc": 5,
      "KyHienTai": 33,
      "KhoiLuongTang": 28,
      "PhanTramTang": 560
    },
    {
      "Danhba": "15062133622",
      "KyTruoc": 8,
      "KyHienTai": 36,
      "KhoiLuongTang": 28,
      "PhanTramTang": 350
    },
    {
      "Danhba": "22103408453",
      "KyTruoc": 1,
      "KyHienTai": 29,
      "KhoiLuongTang": 28,
      "PhanTramTang": 2800
    },
    {
      "Danhba": "22103410596",
      "KyTruoc": 1,
      "KyHienTai": 28,
      "KhoiLuongTang": 27,
      "PhanTramTang": 2700
    },
    {
      "Danhba": "22033330129",
      "KyTruoc": 5,
      "KyHienTai": 32,
      "KhoiLuongTang": 27,
      "PhanTramTang": 540
    },
    {
      "Danhba": "15112846675",
      "KyTruoc": 3,
      "KyHienTai": 30,
      "KhoiLuongTang": 27,
      "PhanTramTang": 900
    },
    {
      "Danhba": "15062141283",
      "KyTruoc": 3,
      "KyHienTai": 30,
      "KhoiLuongTang": 27,
      "PhanTramTang": 900
    },
    {
      "Danhba": "15112866696",
      "KyTruoc": 6,
      "KyHienTai": 33,
      "KhoiLuongTang": 27,
      "PhanTramTang": 450
    },
    {
      "Danhba": "15122840374",
      "KyTruoc": 7,
      "KyHienTai": 33,
      "KhoiLuongTang": 26,
      "PhanTramTang": 371.4
    },
    {
      "Danhba": "15122842192",
      "KyTruoc": 1,
      "KyHienTai": 27,
      "KhoiLuongTang": 26,
      "PhanTramTang": 2600
    },
    {
      "Danhba": "15112841020",
      "KyTruoc": 6,
      "KyHienTai": 32,
      "KhoiLuongTang": 26,
      "PhanTramTang": 433.3
    },
    {
      "Danhba": "22033271797",
      "KyTruoc": 6,
      "KyHienTai": 32,
      "KhoiLuongTang": 26,
      "PhanTramTang": 433.3
    },
    {
      "Danhba": "22043305985",
      "KyTruoc": 5,
      "KyHienTai": 31,
      "KhoiLuongTang": 26,
      "PhanTramTang": 520
    },
    {
      "Danhba": "22043270740",
      "KyTruoc": 5,
      "KyHienTai": 31,
      "KhoiLuongTang": 26,
      "PhanTramTang": 520
    },
    {
      "Danhba": "22043290123",
      "KyTruoc": 8,
      "KyHienTai": 33,
      "KhoiLuongTang": 25,
      "PhanTramTang": 312.5
    },
    {
      "Danhba": "22103413744",
      "KyTruoc": 6,
      "KyHienTai": 31,
      "KhoiLuongTang": 25,
      "PhanTramTang": 416.7
    },
    {
      "Danhba": "22103400731",
      "KyTruoc": 6,
      "KyHienTai": 31,
      "KhoiLuongTang": 25,
      "PhanTramTang": 416.7
    },
    {
      "Danhba": "22033275186",
      "KyTruoc": 4,
      "KyHienTai": 29,
      "KhoiLuongTang": 25,
      "PhanTramTang": 625
    },
    {
      "Danhba": "22033332782",
      "KyTruoc": 3,
      "KyHienTai": 28,
      "KhoiLuongTang": 25,
      "PhanTramTang": 833.3
    },
    {
      "Danhba": "15112829191",
      "KyTruoc": 7,
      "KyHienTai": 32,
      "KhoiLuongTang": 25,
      "PhanTramTang": 357.1
    },
    {
      "Danhba": "15062140414",
      "KyTruoc": 6,
      "KyHienTai": 31,
      "KhoiLuongTang": 25,
      "PhanTramTang": 416.7
    },
    {
      "Danhba": "15122840322",
      "KyTruoc": 3,
      "KyHienTai": 28,
      "KhoiLuongTang": 25,
      "PhanTramTang": 833.3
    },
    {
      "Danhba": "15173426477",
      "KyTruoc": 4,
      "KyHienTai": 29,
      "KhoiLuongTang": 25,
      "PhanTramTang": 625
    },
    {
      "Danhba": "15122891298",
      "KyTruoc": 2,
      "KyHienTai": 27,
      "KhoiLuongTang": 25,
      "PhanTramTang": 1250
    },
    {
      "Danhba": "15122864333",
      "KyTruoc": 5,
      "KyHienTai": 29,
      "KhoiLuongTang": 24,
      "PhanTramTang": 480
    },
    {
      "Danhba": "15112866752",
      "KyTruoc": 3,
      "KyHienTai": 27,
      "KhoiLuongTang": 24,
      "PhanTramTang": 800
    },
    {
      "Danhba": "22033279171",
      "KyTruoc": 2,
      "KyHienTai": 26,
      "KhoiLuongTang": 24,
      "PhanTramTang": 1200
    },
    {
      "Danhba": "22033279313",
      "KyTruoc": 2,
      "KyHienTai": 26,
      "KhoiLuongTang": 24,
      "PhanTramTang": 1200
    },
    {
      "Danhba": "22033275232",
      "KyTruoc": 1,
      "KyHienTai": 25,
      "KhoiLuongTang": 24,
      "PhanTramTang": 2400
    },
    {
      "Danhba": "22033272453",
      "KyTruoc": 3,
      "KyHienTai": 27,
      "KhoiLuongTang": 24,
      "PhanTramTang": 800
    },
    {
      "Danhba": "22043314035",
      "KyTruoc": 7,
      "KyHienTai": 31,
      "KhoiLuongTang": 24,
      "PhanTramTang": 342.9
    },
    {
      "Danhba": "15122885457",
      "KyTruoc": 2,
      "KyHienTai": 25,
      "KhoiLuongTang": 23,
      "PhanTramTang": 1150
    },
    {
      "Danhba": "15112820183",
      "KyTruoc": 5,
      "KyHienTai": 28,
      "KhoiLuongTang": 23,
      "PhanTramTang": 460
    },
    {
      "Danhba": "15062141308",
      "KyTruoc": 1,
      "KyHienTai": 24,
      "KhoiLuongTang": 23,
      "PhanTramTang": 2300
    },
    {
      "Danhba": "15122890704",
      "KyTruoc": 2,
      "KyHienTai": 24,
      "KhoiLuongTang": 22,
      "PhanTramTang": 1100
    },
    {
      "Danhba": "22043298417",
      "KyTruoc": 1,
      "KyHienTai": 22,
      "KhoiLuongTang": 21,
      "PhanTramTang": 2100
    },
    {
      "Danhba": "22043303696",
      "KyTruoc": 3,
      "KyHienTai": 24,
      "KhoiLuongTang": 21,
      "PhanTramTang": 700
    },
    {
      "Danhba": "15112841483",
      "KyTruoc": 2,
      "KyHienTai": 23,
      "KhoiLuongTang": 21,
      "PhanTramTang": 1050
    },
    {
      "Danhba": "15062137756",
      "KyTruoc": 5,
      "KyHienTai": 26,
      "KhoiLuongTang": 21,
      "PhanTramTang": 420
    },
    {
      "Danhba": "15112820831",
      "KyTruoc": 5,
      "KyHienTai": 25,
      "KhoiLuongTang": 20,
      "PhanTramTang": 400
    },
    {
      "Danhba": "15062141298",
      "KyTruoc": 6,
      "KyHienTai": 26,
      "KhoiLuongTang": 20,
      "PhanTramTang": 333.3
    },
    {
      "Danhba": "15112844237",
      "KyTruoc": 3,
      "KyHienTai": 23,
      "KhoiLuongTang": 20,
      "PhanTramTang": 666.7
    },
    {
      "Danhba": "15122882213",
      "KyTruoc": 2,
      "KyHienTai": 22,
      "KhoiLuongTang": 20,
      "PhanTramTang": 1000
    },
    {
      "Danhba": "15112867184",
      "KyTruoc": 1,
      "KyHienTai": 21,
      "KhoiLuongTang": 20,
      "PhanTramTang": 2000
    },
    {
      "Danhba": "22033333562",
      "KyTruoc": 1,
      "KyHienTai": 21,
      "KhoiLuongTang": 20,
      "PhanTramTang": 2000
    },
    {
      "Danhba": "22033333860",
      "KyTruoc": 2,
      "KyHienTai": 22,
      "KhoiLuongTang": 20,
      "PhanTramTang": 1000
    },
    {
      "Danhba": "15112867361",
      "KyTruoc": 5,
      "KyHienTai": 24,
      "KhoiLuongTang": 19,
      "PhanTramTang": 380
    },
    {
      "Danhba": "15122880258",
      "KyTruoc": 6,
      "KyHienTai": 25,
      "KhoiLuongTang": 19,
      "PhanTramTang": 316.7
    },
    {
      "Danhba": "15122882120",
      "KyTruoc": 1,
      "KyHienTai": 20,
      "KhoiLuongTang": 19,
      "PhanTramTang": 1900
    },
    {
      "Danhba": "15161925187",
      "KyTruoc": 3,
      "KyHienTai": 22,
      "KhoiLuongTang": 19,
      "PhanTramTang": 633.3
    },
    {
      "Danhba": "22033270393",
      "KyTruoc": 1,
      "KyHienTai": 20,
      "KhoiLuongTang": 19,
      "PhanTramTang": 1900
    },
    {
      "Danhba": "15062133087",
      "KyTruoc": 6,
      "KyHienTai": 25,
      "KhoiLuongTang": 19,
      "PhanTramTang": 316.7
    },
    {
      "Danhba": "22033270828",
      "KyTruoc": 1,
      "KyHienTai": 19,
      "KhoiLuongTang": 18,
      "PhanTramTang": 1800
    },
    {
      "Danhba": "15122884492",
      "KyTruoc": 1,
      "KyHienTai": 19,
      "KhoiLuongTang": 18,
      "PhanTramTang": 1800
    },
    {
      "Danhba": "15122880864",
      "KyTruoc": 5,
      "KyHienTai": 23,
      "KhoiLuongTang": 18,
      "PhanTramTang": 360
    },
    {
      "Danhba": "22033334150",
      "KyTruoc": 4,
      "KyHienTai": 22,
      "KhoiLuongTang": 18,
      "PhanTramTang": 450
    },
    {
      "Danhba": "22043270062",
      "KyTruoc": 3,
      "KyHienTai": 21,
      "KhoiLuongTang": 18,
      "PhanTramTang": 600
    },
    {
      "Danhba": "22033272647",
      "KyTruoc": 1,
      "KyHienTai": 19,
      "KhoiLuongTang": 18,
      "PhanTramTang": 1800
    },
    {
      "Danhba": "22033272305",
      "KyTruoc": 1,
      "KyHienTai": 19,
      "KhoiLuongTang": 18,
      "PhanTramTang": 1800
    },
    {
      "Danhba": "15161925614",
      "KyTruoc": 5,
      "KyHienTai": 23,
      "KhoiLuongTang": 18,
      "PhanTramTang": 360
    },
    {
      "Danhba": "22033278624",
      "KyTruoc": 5,
      "KyHienTai": 23,
      "KhoiLuongTang": 18,
      "PhanTramTang": 360
    },
    {
      "Danhba": "22043307155",
      "KyTruoc": 4,
      "KyHienTai": 22,
      "KhoiLuongTang": 18,
      "PhanTramTang": 450
    },
    {
      "Danhba": "22043307702",
      "KyTruoc": 3,
      "KyHienTai": 21,
      "KhoiLuongTang": 18,
      "PhanTramTang": 600
    },
    {
      "Danhba": "22043312853",
      "KyTruoc": 3,
      "KyHienTai": 20,
      "KhoiLuongTang": 17,
      "PhanTramTang": 566.7
    },
    {
      "Danhba": "22043305221",
      "KyTruoc": 3,
      "KyHienTai": 20,
      "KhoiLuongTang": 17,
      "PhanTramTang": 566.7
    },
    {
      "Danhba": "22043305607",
      "KyTruoc": 3,
      "KyHienTai": 20,
      "KhoiLuongTang": 17,
      "PhanTramTang": 566.7
    },
    {
      "Danhba": "15122842396",
      "KyTruoc": 4,
      "KyHienTai": 21,
      "KhoiLuongTang": 17,
      "PhanTramTang": 425
    },
    {
      "Danhba": "15122884486",
      "KyTruoc": 2,
      "KyHienTai": 19,
      "KhoiLuongTang": 17,
      "PhanTramTang": 850
    },
    {
      "Danhba": "15122885889",
      "KyTruoc": 3,
      "KyHienTai": 20,
      "KhoiLuongTang": 17,
      "PhanTramTang": 566.7
    },
    {
      "Danhba": "15062140035",
      "KyTruoc": 4,
      "KyHienTai": 21,
      "KhoiLuongTang": 17,
      "PhanTramTang": 425
    },
    {
      "Danhba": "15112865381",
      "KyTruoc": 3,
      "KyHienTai": 20,
      "KhoiLuongTang": 17,
      "PhanTramTang": 566.7
    },
    {
      "Danhba": "15062141249",
      "KyTruoc": 3,
      "KyHienTai": 20,
      "KhoiLuongTang": 17,
      "PhanTramTang": 566.7
    },
    {
      "Danhba": "15062139846",
      "KyTruoc": 1,
      "KyHienTai": 18,
      "KhoiLuongTang": 17,
      "PhanTramTang": 1700
    },
    {
      "Danhba": "15112840737",
      "KyTruoc": 1,
      "KyHienTai": 17,
      "KhoiLuongTang": 16,
      "PhanTramTang": 1600
    },
    {
      "Danhba": "15062140046",
      "KyTruoc": 4,
      "KyHienTai": 20,
      "KhoiLuongTang": 16,
      "PhanTramTang": 400
    },
    {
      "Danhba": "15122890568",
      "KyTruoc": 1,
      "KyHienTai": 17,
      "KhoiLuongTang": 16,
      "PhanTramTang": 1600
    },
    {
      "Danhba": "15112867410",
      "KyTruoc": 3,
      "KyHienTai": 19,
      "KhoiLuongTang": 16,
      "PhanTramTang": 533.3
    },
    {
      "Danhba": "22043312028",
      "KyTruoc": 5,
      "KyHienTai": 21,
      "KhoiLuongTang": 16,
      "PhanTramTang": 320
    },
    {
      "Danhba": "22033276028",
      "KyTruoc": 5,
      "KyHienTai": 21,
      "KhoiLuongTang": 16,
      "PhanTramTang": 320
    },
    {
      "Danhba": "22033279797",
      "KyTruoc": 3,
      "KyHienTai": 19,
      "KhoiLuongTang": 16,
      "PhanTramTang": 533.3
    }
  ],
  "stuckTop": [
    {
      "Danhba": "15112829423",
      "KyTruoc": 590,
      "KyHienTai": 89,
      "KhoiLuongGiam": 501,
      "PhanTramGiam": 84.9
    },
    {
      "Danhba": "15112829422",
      "KyTruoc": 542,
      "KyHienTai": 74,
      "KhoiLuongGiam": 468,
      "PhanTramGiam": 86.3
    },
    {
      "Danhba": "22033334264",
      "KyTruoc": 394,
      "KyHienTai": 1,
      "KhoiLuongGiam": 393,
      "PhanTramGiam": 99.7
    },
    {
      "Danhba": "15112868240",
      "KyTruoc": 5,
      "KyHienTai": -346,
      "KhoiLuongGiam": 351,
      "PhanTramGiam": 7020
    },
    {
      "Danhba": "15112840755",
      "KyTruoc": 166,
      "KyHienTai": 10,
      "KhoiLuongGiam": 156,
      "PhanTramGiam": 94
    },
    {
      "Danhba": "22103408658",
      "KyTruoc": 171,
      "KyHienTai": 23,
      "KhoiLuongGiam": 148,
      "PhanTramGiam": 86.5
    },
    {
      "Danhba": "15062137955",
      "KyTruoc": 177,
      "KyHienTai": 32,
      "KhoiLuongGiam": 145,
      "PhanTramGiam": 81.9
    },
    {
      "Danhba": "22043334310",
      "KyTruoc": 122,
      "KyHienTai": 7,
      "KhoiLuongGiam": 115,
      "PhanTramGiam": 94.3
    },
    {
      "Danhba": "15122891003",
      "KyTruoc": 109,
      "KyHienTai": 4,
      "KhoiLuongGiam": 105,
      "PhanTramGiam": 96.3
    },
    {
      "Danhba": "15062134116",
      "KyTruoc": 133,
      "KyHienTai": 29,
      "KhoiLuongGiam": 104,
      "PhanTramGiam": 78.2
    },
    {
      "Danhba": "15122848227",
      "KyTruoc": 101,
      "KyHienTai": 11,
      "KhoiLuongGiam": 90,
      "PhanTramGiam": 89.1
    },
    {
      "Danhba": "15112868949",
      "KyTruoc": 106,
      "KyHienTai": 18,
      "KhoiLuongGiam": 88,
      "PhanTramGiam": 83
    },
    {
      "Danhba": "15122889953",
      "KyTruoc": 109,
      "KyHienTai": 21,
      "KhoiLuongGiam": 88,
      "PhanTramGiam": 80.7
    },
    {
      "Danhba": "22033334233",
      "KyTruoc": 89,
      "KyHienTai": 6,
      "KhoiLuongGiam": 83,
      "PhanTramGiam": 93.3
    },
    {
      "Danhba": "15122890264",
      "KyTruoc": 82,
      "KyHienTai": 0,
      "KhoiLuongGiam": 82,
      "PhanTramGiam": 100
    },
    {
      "Danhba": "22103414130",
      "KyTruoc": 93,
      "KyHienTai": 14,
      "KhoiLuongGiam": 79,
      "PhanTramGiam": 84.9
    },
    {
      "Danhba": "22043314454",
      "KyTruoc": 87,
      "KyHienTai": 13,
      "KhoiLuongGiam": 74,
      "PhanTramGiam": 85.1
    },
    {
      "Danhba": "15112868281",
      "KyTruoc": 10,
      "KyHienTai": -60,
      "KhoiLuongGiam": 70,
      "PhanTramGiam": 700
    },
    {
      "Danhba": "15112846799",
      "KyTruoc": 71,
      "KyHienTai": 4,
      "KhoiLuongGiam": 67,
      "PhanTramGiam": 94.4
    },
    {
      "Danhba": "22033277373",
      "KyTruoc": 66,
      "KyHienTai": 0,
      "KhoiLuongGiam": 66,
      "PhanTramGiam": 100
    },
    {
      "Danhba": "22043302988",
      "KyTruoc": 70,
      "KyHienTai": 5,
      "KhoiLuongGiam": 65,
      "PhanTramGiam": 92.9
    },
    {
      "Danhba": "15062139840",
      "KyTruoc": 65,
      "KyHienTai": 0,
      "KhoiLuongGiam": 65,
      "PhanTramGiam": 100
    },
    {
      "Danhba": "22103390576",
      "KyTruoc": 59,
      "KyHienTai": 0,
      "KhoiLuongGiam": 59,
      "PhanTramGiam": 100
    },
    {
      "Danhba": "22043310319",
      "KyTruoc": 64,
      "KyHienTai": 10,
      "KhoiLuongGiam": 54,
      "PhanTramGiam": 84.4
    },
    {
      "Danhba": "15062132186",
      "KyTruoc": 53,
      "KyHienTai": 0,
      "KhoiLuongGiam": 53,
      "PhanTramGiam": 100
    },
    {
      "Danhba": "15112869095",
      "KyTruoc": 28,
      "KyHienTai": -23,
      "KhoiLuongGiam": 51,
      "PhanTramGiam": 182.1
    },
    {
      "Danhba": "15062131322",
      "KyTruoc": 61,
      "KyHienTai": 11,
      "KhoiLuongGiam": 50,
      "PhanTramGiam": 82
    },
    {
      "Danhba": "15112829483",
      "KyTruoc": 52,
      "KyHienTai": 4,
      "KhoiLuongGiam": 48,
      "PhanTramGiam": 92.3
    },
    {
      "Danhba": "22103414127",
      "KyTruoc": 62,
      "KyHienTai": 14,
      "KhoiLuongGiam": 48,
      "PhanTramGiam": 77.4
    },
    {
      "Danhba": "22103413548",
      "KyTruoc": 61,
      "KyHienTai": 15,
      "KhoiLuongGiam": 46,
      "PhanTramGiam": 75.4
    },
    {
      "Danhba": "22043307358",
      "KyTruoc": 45,
      "KyHienTai": 0,
      "KhoiLuongGiam": 45,
      "PhanTramGiam": 100
    },
    {
      "Danhba": "22033330609",
      "KyTruoc": 45,
      "KyHienTai": 0,
      "KhoiLuongGiam": 45,
      "PhanTramGiam": 100
    },
    {
      "Danhba": "15112860935",
      "KyTruoc": 56,
      "KyHienTai": 12,
      "KhoiLuongGiam": 44,
      "PhanTramGiam": 78.6
    },
    {
      "Danhba": "15161925610",
      "KyTruoc": 44,
      "KyHienTai": 0,
      "KhoiLuongGiam": 44,
      "PhanTramGiam": 100
    },
    {
      "Danhba": "22033277262",
      "KyTruoc": 54,
      "KyHienTai": 11,
      "KhoiLuongGiam": 43,
      "PhanTramGiam": 79.6
    },
    {
      "Danhba": "15122840281",
      "KyTruoc": 42,
      "KyHienTai": 0,
      "KhoiLuongGiam": 42,
      "PhanTramGiam": 100
    },
    {
      "Danhba": "15062134383",
      "KyTruoc": 49,
      "KyHienTai": 7,
      "KhoiLuongGiam": 42,
      "PhanTramGiam": 85.7
    },
    {
      "Danhba": "15062139501",
      "KyTruoc": 40,
      "KyHienTai": 1,
      "KhoiLuongGiam": 39,
      "PhanTramGiam": 97.5
    },
    {
      "Danhba": "22033273020",
      "KyTruoc": 47,
      "KyHienTai": 8,
      "KhoiLuongGiam": 39,
      "PhanTramGiam": 83
    },
    {
      "Danhba": "15161922138",
      "KyTruoc": 22,
      "KyHienTai": -16,
      "KhoiLuongGiam": 38,
      "PhanTramGiam": 172.7
    },
    {
      "Danhba": "15062141112",
      "KyTruoc": 38,
      "KyHienTai": 1,
      "KhoiLuongGiam": 37,
      "PhanTramGiam": 97.4
    },
    {
      "Danhba": "15112846102",
      "KyTruoc": 42,
      "KyHienTai": 6,
      "KhoiLuongGiam": 36,
      "PhanTramGiam": 85.7
    },
    {
      "Danhba": "15122884701",
      "KyTruoc": 34,
      "KyHienTai": 1,
      "KhoiLuongGiam": 33,
      "PhanTramGiam": 97.1
    },
    {
      "Danhba": "22043309325",
      "KyTruoc": 33,
      "KyHienTai": 0,
      "KhoiLuongGiam": 33,
      "PhanTramGiam": 100
    },
    {
      "Danhba": "22043334435",
      "KyTruoc": 38,
      "KyHienTai": 6,
      "KhoiLuongGiam": 32,
      "PhanTramGiam": 84.2
    },
    {
      "Danhba": "15122886758",
      "KyTruoc": 32,
      "KyHienTai": 0,
      "KhoiLuongGiam": 32,
      "PhanTramGiam": 100
    },
    {
      "Danhba": "15062141102",
      "KyTruoc": 36,
      "KyHienTai": 4,
      "KhoiLuongGiam": 32,
      "PhanTramGiam": 88.9
    },
    {
      "Danhba": "15122881305",
      "KyTruoc": 32,
      "KyHienTai": 1,
      "KhoiLuongGiam": 31,
      "PhanTramGiam": 96.9
    },
    {
      "Danhba": "15062133503",
      "KyTruoc": 30,
      "KyHienTai": 0,
      "KhoiLuongGiam": 30,
      "PhanTramGiam": 100
    },
    {
      "Danhba": "22043314038",
      "KyTruoc": 32,
      "KyHienTai": 2,
      "KhoiLuongGiam": 30,
      "PhanTramGiam": 93.8
    },
    {
      "Danhba": "22103391707",
      "KyTruoc": 34,
      "KyHienTai": 4,
      "KhoiLuongGiam": 30,
      "PhanTramGiam": 88.2
    },
    {
      "Danhba": "22033331610",
      "KyTruoc": 32,
      "KyHienTai": 3,
      "KhoiLuongGiam": 29,
      "PhanTramGiam": 90.6
    },
    {
      "Danhba": "22103412977",
      "KyTruoc": 29,
      "KyHienTai": 0,
      "KhoiLuongGiam": 29,
      "PhanTramGiam": 100
    },
    {
      "Danhba": "15062130452",
      "KyTruoc": 35,
      "KyHienTai": 6,
      "KhoiLuongGiam": 29,
      "PhanTramGiam": 82.9
    },
    {
      "Danhba": "15122890838",
      "KyTruoc": 33,
      "KyHienTai": 4,
      "KhoiLuongGiam": 29,
      "PhanTramGiam": 87.9
    },
    {
      "Danhba": "15173420436",
      "KyTruoc": 35,
      "KyHienTai": 7,
      "KhoiLuongGiam": 28,
      "PhanTramGiam": 80
    },
    {
      "Danhba": "22033273000",
      "KyTruoc": 32,
      "KyHienTai": 4,
      "KhoiLuongGiam": 28,
      "PhanTramGiam": 87.5
    },
    {
      "Danhba": "15112862597",
      "KyTruoc": 32,
      "KyHienTai": 4,
      "KhoiLuongGiam": 28,
      "PhanTramGiam": 87.5
    },
    {
      "Danhba": "15112860739",
      "KyTruoc": 28,
      "KyHienTai": 0,
      "KhoiLuongGiam": 28,
      "PhanTramGiam": 100
    },
    {
      "Danhba": "22103413323",
      "KyTruoc": 33,
      "KyHienTai": 5,
      "KhoiLuongGiam": 28,
      "PhanTramGiam": 84.8
    },
    {
      "Danhba": "22033275993",
      "KyTruoc": 28,
      "KyHienTai": 0,
      "KhoiLuongGiam": 28,
      "PhanTramGiam": 100
    },
    {
      "Danhba": "22103410551",
      "KyTruoc": 34,
      "KyHienTai": 7,
      "KhoiLuongGiam": 27,
      "PhanTramGiam": 79.4
    },
    {
      "Danhba": "22043311563",
      "KyTruoc": 30,
      "KyHienTai": 3,
      "KhoiLuongGiam": 27,
      "PhanTramGiam": 90
    },
    {
      "Danhba": "15122889217",
      "KyTruoc": 27,
      "KyHienTai": 0,
      "KhoiLuongGiam": 27,
      "PhanTramGiam": 100
    },
    {
      "Danhba": "22043278401",
      "KyTruoc": 27,
      "KyHienTai": 2,
      "KhoiLuongGiam": 25,
      "PhanTramGiam": 92.6
    },
    {
      "Danhba": "22103411362",
      "KyTruoc": 27,
      "KyHienTai": 2,
      "KhoiLuongGiam": 25,
      "PhanTramGiam": 92.6
    },
    {
      "Danhba": "22033278998",
      "KyTruoc": 24,
      "KyHienTai": 1,
      "KhoiLuongGiam": 23,
      "PhanTramGiam": 95.8
    },
    {
      "Danhba": "22103411127",
      "KyTruoc": 28,
      "KyHienTai": 5,
      "KhoiLuongGiam": 23,
      "PhanTramGiam": 82.1
    },
    {
      "Danhba": "15122882099",
      "KyTruoc": 28,
      "KyHienTai": 5,
      "KhoiLuongGiam": 23,
      "PhanTramGiam": 82.1
    },
    {
      "Danhba": "15062140766",
      "KyTruoc": 26,
      "KyHienTai": 3,
      "KhoiLuongGiam": 23,
      "PhanTramGiam": 88.5
    },
    {
      "Danhba": "15112860483",
      "KyTruoc": 28,
      "KyHienTai": 6,
      "KhoiLuongGiam": 22,
      "PhanTramGiam": 78.6
    },
    {
      "Danhba": "15062141307",
      "KyTruoc": 29,
      "KyHienTai": 7,
      "KhoiLuongGiam": 22,
      "PhanTramGiam": 75.9
    },
    {
      "Danhba": "15062139124",
      "KyTruoc": 22,
      "KyHienTai": 0,
      "KhoiLuongGiam": 22,
      "PhanTramGiam": 100
    },
    {
      "Danhba": "15062140141",
      "KyTruoc": 26,
      "KyHienTai": 4,
      "KhoiLuongGiam": 22,
      "PhanTramGiam": 84.6
    },
    {
      "Danhba": "22033272787",
      "KyTruoc": 26,
      "KyHienTai": 4,
      "KhoiLuongGiam": 22,
      "PhanTramGiam": 84.6
    },
    {
      "Danhba": "22103391561",
      "KyTruoc": 19,
      "KyHienTai": -3,
      "KhoiLuongGiam": 22,
      "PhanTramGiam": 115.8
    },
    {
      "Danhba": "22043314233",
      "KyTruoc": 22,
      "KyHienTai": 0,
      "KhoiLuongGiam": 22,
      "PhanTramGiam": 100
    },
    {
      "Danhba": "22043303346",
      "KyTruoc": 24,
      "KyHienTai": 2,
      "KhoiLuongGiam": 22,
      "PhanTramGiam": 91.7
    },
    {
      "Danhba": "22103413708",
      "KyTruoc": 27,
      "KyHienTai": 5,
      "KhoiLuongGiam": 22,
      "PhanTramGiam": 81.5
    },
    {
      "Danhba": "22103401142",
      "KyTruoc": 21,
      "KyHienTai": 0,
      "KhoiLuongGiam": 21,
      "PhanTramGiam": 100
    },
    {
      "Danhba": "22103401384",
      "KyTruoc": 21,
      "KyHienTai": 0,
      "KhoiLuongGiam": 21,
      "PhanTramGiam": 100
    },
    {
      "Danhba": "22103393089",
      "KyTruoc": 25,
      "KyHienTai": 5,
      "KhoiLuongGiam": 20,
      "PhanTramGiam": 80
    },
    {
      "Danhba": "22033330276",
      "KyTruoc": 14,
      "KyHienTai": -6,
      "KhoiLuongGiam": 20,
      "PhanTramGiam": 142.9
    },
    {
      "Danhba": "22043278429",
      "KyTruoc": 23,
      "KyHienTai": 3,
      "KhoiLuongGiam": 20,
      "PhanTramGiam": 87
    },
    {
      "Danhba": "15122890066",
      "KyTruoc": 20,
      "KyHienTai": 0,
      "KhoiLuongGiam": 20,
      "PhanTramGiam": 100
    },
    {
      "Danhba": "15122889721",
      "KyTruoc": 20,
      "KyHienTai": 0,
      "KhoiLuongGiam": 20,
      "PhanTramGiam": 100
    },
    {
      "Danhba": "15122885167",
      "KyTruoc": 20,
      "KyHienTai": 0,
      "KhoiLuongGiam": 20,
      "PhanTramGiam": 100
    },
    {
      "Danhba": "15122842315",
      "KyTruoc": 24,
      "KyHienTai": 4,
      "KhoiLuongGiam": 20,
      "PhanTramGiam": 83.3
    },
    {
      "Danhba": "15062140440",
      "KyTruoc": 20,
      "KyHienTai": 0,
      "KhoiLuongGiam": 20,
      "PhanTramGiam": 100
    },
    {
      "Danhba": "15112861659",
      "KyTruoc": 19,
      "KyHienTai": 0,
      "KhoiLuongGiam": 19,
      "PhanTramGiam": 100
    },
    {
      "Danhba": "15112840908",
      "KyTruoc": 20,
      "KyHienTai": 1,
      "KhoiLuongGiam": 19,
      "PhanTramGiam": 95
    },
    {
      "Danhba": "15112867233",
      "KyTruoc": 20,
      "KyHienTai": 1,
      "KhoiLuongGiam": 19,
      "PhanTramGiam": 95
    },
    {
      "Danhba": "15122889970",
      "KyTruoc": 20,
      "KyHienTai": 1,
      "KhoiLuongGiam": 19,
      "PhanTramGiam": 95
    },
    {
      "Danhba": "22043305507",
      "KyTruoc": 20,
      "KyHienTai": 1,
      "KhoiLuongGiam": 19,
      "PhanTramGiam": 95
    },
    {
      "Danhba": "22033334249",
      "KyTruoc": 19,
      "KyHienTai": 0,
      "KhoiLuongGiam": 19,
      "PhanTramGiam": 100
    },
    {
      "Danhba": "22033330090",
      "KyTruoc": 20,
      "KyHienTai": 2,
      "KhoiLuongGiam": 18,
      "PhanTramGiam": 90
    },
    {
      "Danhba": "22043334444",
      "KyTruoc": 23,
      "KyHienTai": 5,
      "KhoiLuongGiam": 18,
      "PhanTramGiam": 78.3
    },
    {
      "Danhba": "15122886239",
      "KyTruoc": 18,
      "KyHienTai": 0,
      "KhoiLuongGiam": 18,
      "PhanTramGiam": 100
    },
    {
      "Danhba": "15122885209",
      "KyTruoc": 23,
      "KyHienTai": 5,
      "KhoiLuongGiam": 18,
      "PhanTramGiam": 78.3
    },
    {
      "Danhba": "15122889527",
      "KyTruoc": 23,
      "KyHienTai": 5,
      "KhoiLuongGiam": 18,
      "PhanTramGiam": 78.3
    },
    {
      "Danhba": "15112840928",
      "KyTruoc": 20,
      "KyHienTai": 2,
      "KhoiLuongGiam": 18,
      "PhanTramGiam": 90
    },
    {
      "Danhba": "15062141050",
      "KyTruoc": 17,
      "KyHienTai": 0,
      "KhoiLuongGiam": 17,
      "PhanTramGiam": 100
    },
    {
      "Danhba": "15122885985",
      "KyTruoc": 17,
      "KyHienTai": 0,
      "KhoiLuongGiam": 17,
      "PhanTramGiam": 100
    },
    {
      "Danhba": "22033275989",
      "KyTruoc": 22,
      "KyHienTai": 5,
      "KhoiLuongGiam": 17,
      "PhanTramGiam": 77.3
    },
    {
      "Danhba": "22043311346",
      "KyTruoc": 20,
      "KyHienTai": 3,
      "KhoiLuongGiam": 17,
      "PhanTramGiam": 85
    },
    {
      "Danhba": "22033332896",
      "KyTruoc": 16,
      "KyHienTai": 0,
      "KhoiLuongGiam": 16,
      "PhanTramGiam": 100
    },
    {
      "Danhba": "22103391129",
      "KyTruoc": 16,
      "KyHienTai": 0,
      "KhoiLuongGiam": 16,
      "PhanTramGiam": 100
    },
    {
      "Danhba": "22103398230",
      "KyTruoc": 19,
      "KyHienTai": 3,
      "KhoiLuongGiam": 16,
      "PhanTramGiam": 84.2
    },
    {
      "Danhba": "22033275984",
      "KyTruoc": 18,
      "KyHienTai": 2,
      "KhoiLuongGiam": 16,
      "PhanTramGiam": 88.9
    },
    {
      "Danhba": "15122891289",
      "KyTruoc": 16,
      "KyHienTai": 0,
      "KhoiLuongGiam": 16,
      "PhanTramGiam": 100
    },
    {
      "Danhba": "15062141240",
      "KyTruoc": 21,
      "KyHienTai": 5,
      "KhoiLuongGiam": 16,
      "PhanTramGiam": 76.2
    },
    {
      "Danhba": "15112840739",
      "KyTruoc": 16,
      "KyHienTai": 0,
      "KhoiLuongGiam": 16,
      "PhanTramGiam": 100
    },
    {
      "Danhba": "15112840988",
      "KyTruoc": 17,
      "KyHienTai": 1,
      "KhoiLuongGiam": 16,
      "PhanTramGiam": 94.1
    },
    {
      "Danhba": "15062136940",
      "KyTruoc": 17,
      "KyHienTai": 1,
      "KhoiLuongGiam": 16,
      "PhanTramGiam": 94.1
    }
  ],
  "nguong": {
    "roRiPct": ">300%",
    "roRiM3": ">15m³",
    "ketCoPct": ">75%",
    "ketCoM3": ">15m³"
  },
  "tienDo": {
    "tongDH": 246859,
    "daDoc": 30140,
    "chuaDoc": 216719,
    "pct": 12
  }
};
