// Auto-generated by fetch_sai_gia_bieu_prev.py
const TAWACO_SAIGIABIEU_PREV = {
  "lastUpdated": "2026-05-11 10:08:33",
  "ky_hien_tai": "04/2026",
  "tong_sinh_hoat": 47467,
  "tong_nghi_ngo": 170,
  "level_1_count": 9,
  "level_2_count": 122,
  "level_3_count": 39,
  "danh_sach": [
    {
      "DanhBa": "22043311376",
      "TenKH": "CONG TY TNHH TM VA DICH VU Y TE THANH XUAN",
      "GiaBieu": "11",
      "DinhMuc": 184,
      "Mean_6M": 194.0,
      "Std_6M": 36.11,
      "Alert_Level": 1
    },
    {
      "DanhBa": "22103391690",
      "TenKH": "CT TNHH MAY-IN-THEU M & J",
      "GiaBieu": "11",
      "DinhMuc": 0,
      "Mean_6M": 173.33,
      "Std_6M": 77.51,
      "Alert_Level": 1
    },
    {
      "DanhBa": "22103411584",
      "TenKH": "CTY TNHH TM-SX S.G.M",
      "GiaBieu": "11",
      "DinhMuc": 0,
      "Mean_6M": 139.0,
      "Std_6M": 11.51,
      "Alert_Level": 1
    },
    {
      "DanhBa": "15122861571",
      "TenKH": "CONG TY TNHH SAN XUAT THUONG MAI DICH VU VINH HIEN",
      "GiaBieu": "11",
      "DinhMuc": 16,
      "Mean_6M": 26.5,
      "Std_6M": 4.23,
      "Alert_Level": 1
    },
    {
      "DanhBa": "15072444147",
      "TenKH": "CT TNHH SX CK TM DV THANH SON",
      "GiaBieu": "11",
      "DinhMuc": 24,
      "Mean_6M": 16.0,
      "Std_6M": 4.0,
      "Alert_Level": 1
    },
    {
      "DanhBa": "22103412836",
      "TenKH": "CHI NHANH CONG TY TNHH THUAN BUOM",
      "GiaBieu": "11",
      "DinhMuc": 0,
      "Mean_6M": 11.67,
      "Std_6M": 2.58,
      "Alert_Level": 1
    },
    {
      "DanhBa": "22103412220",
      "TenKH": "CONG TY TNHH DET LUA TO TAM TOAN THINH",
      "GiaBieu": "11",
      "DinhMuc": 0,
      "Mean_6M": 6.33,
      "Std_6M": 1.75,
      "Alert_Level": 1
    },
    {
      "DanhBa": "22033333150",
      "TenKH": "CONG TY TNHH THUC PHAM AROMA",
      "GiaBieu": "11",
      "DinhMuc": 0,
      "Mean_6M": 4.17,
      "Std_6M": 3.82,
      "Alert_Level": 1
    },
    {
      "DanhBa": "22103413827",
      "TenKH": "CONG TY TNHH VIET UC AUTO",
      "GiaBieu": "11",
      "DinhMuc": 0,
      "Mean_6M": 0.0,
      "Std_6M": 0.0,
      "Alert_Level": 1
    },
    {
      "DanhBa": "22073343285",
      "TenKH": "NGUYEN DUY LINH",
      "GiaBieu": "11",
      "DinhMuc": 0,
      "Mean_6M": 494.83,
      "Std_6M": 88.75,
      "Alert_Level": 2
    },
    {
      "DanhBa": "22103412290",
      "TenKH": "HA HOANG HAI",
      "GiaBieu": "11",
      "DinhMuc": 536,
      "Mean_6M": 479.33,
      "Std_6M": 116.66,
      "Alert_Level": 2
    },
    {
      "DanhBa": "15112823137",
      "TenKH": "TRAN DAI HAI",
      "GiaBieu": "11",
      "DinhMuc": 444,
      "Mean_6M": 459.33,
      "Std_6M": 105.07,
      "Alert_Level": 2
    },
    {
      "DanhBa": "15062138848",
      "TenKH": "NGUYEN VAN HANH",
      "GiaBieu": "11",
      "DinhMuc": 328,
      "Mean_6M": 440.5,
      "Std_6M": 137.1,
      "Alert_Level": 2
    },
    {
      "DanhBa": "22103410501",
      "TenKH": "HOANG THI THUY TRANG",
      "GiaBieu": "11",
      "DinhMuc": 0,
      "Mean_6M": 438.67,
      "Std_6M": 1072.55,
      "Alert_Level": 2
    },
    {
      "DanhBa": "15062141062",
      "TenKH": "NGUYEN MINH TRI",
      "GiaBieu": "11",
      "DinhMuc": 120,
      "Mean_6M": 372.83,
      "Std_6M": 90.78,
      "Alert_Level": 2
    },
    {
      "DanhBa": "15112829418",
      "TenKH": "LE ANH TUAN",
      "GiaBieu": "11",
      "DinhMuc": 304,
      "Mean_6M": 371.33,
      "Std_6M": 165.62,
      "Alert_Level": 2
    },
    {
      "DanhBa": "15062135394",
      "TenKH": "TRUONG THI NAM",
      "GiaBieu": "11",
      "DinhMuc": 700,
      "Mean_6M": 362.83,
      "Std_6M": 75.49,
      "Alert_Level": 2
    },
    {
      "DanhBa": "22103412770",
      "TenKH": "CHU DINH VIEN",
      "GiaBieu": "11",
      "DinhMuc": 344,
      "Mean_6M": 362.67,
      "Std_6M": 56.87,
      "Alert_Level": 2
    },
    {
      "DanhBa": "15062133585",
      "TenKH": "PHAM THI KIM PHUONG",
      "GiaBieu": "11",
      "DinhMuc": 444,
      "Mean_6M": 361.67,
      "Std_6M": 75.57,
      "Alert_Level": 2
    },
    {
      "DanhBa": "15062141187",
      "TenKH": "TRUONG THI NGOC LIEN",
      "GiaBieu": "11",
      "DinhMuc": 0,
      "Mean_6M": 310.0,
      "Std_6M": 85.16,
      "Alert_Level": 2
    },
    {
      "DanhBa": "15062133596",
      "TenKH": "NGUYEN THU HANG",
      "GiaBieu": "11",
      "DinhMuc": 264,
      "Mean_6M": 306.67,
      "Std_6M": 57.39,
      "Alert_Level": 2
    },
    {
      "DanhBa": "15112867087",
      "TenKH": "TRAN DINH TRUNG",
      "GiaBieu": "11",
      "DinhMuc": 8,
      "Mean_6M": 303.0,
      "Std_6M": 35.69,
      "Alert_Level": 2
    },
    {
      "DanhBa": "15062130167",
      "TenKH": "DO MINH TIEN",
      "GiaBieu": "11",
      "DinhMuc": 0,
      "Mean_6M": 288.33,
      "Std_6M": 68.2,
      "Alert_Level": 2
    },
    {
      "DanhBa": "22103410512",
      "TenKH": "VU HOANG LONG",
      "GiaBieu": "11",
      "DinhMuc": 200,
      "Mean_6M": 287.0,
      "Std_6M": 94.44,
      "Alert_Level": 2
    },
    {
      "DanhBa": "15062141197",
      "TenKH": "TRAN THI XIN",
      "GiaBieu": "11",
      "DinhMuc": 224,
      "Mean_6M": 286.17,
      "Std_6M": 52.78,
      "Alert_Level": 2
    },
    {
      "DanhBa": "22073342777",
      "TenKH": "NGUYEN DUY DAI",
      "GiaBieu": "11",
      "DinhMuc": 316,
      "Mean_6M": 286.0,
      "Std_6M": 48.69,
      "Alert_Level": 2
    },
    {
      "DanhBa": "22073238437",
      "TenKH": "NGUYEN QUOC CHIEN",
      "GiaBieu": "11",
      "DinhMuc": 80,
      "Mean_6M": 285.33,
      "Std_6M": 52.02,
      "Alert_Level": 2
    },
    {
      "DanhBa": "22103396344",
      "TenKH": "NGUYEN THI NGOC HA",
      "GiaBieu": "11",
      "DinhMuc": 240,
      "Mean_6M": 272.0,
      "Std_6M": 39.81,
      "Alert_Level": 2
    },
    {
      "DanhBa": "15062140367",
      "TenKH": "LE THI HUONG",
      "GiaBieu": "11",
      "DinhMuc": 296,
      "Mean_6M": 271.5,
      "Std_6M": 46.98,
      "Alert_Level": 2
    },
    {
      "DanhBa": "15112864181",
      "TenKH": "NGUYEN THI DOAN",
      "GiaBieu": "11",
      "DinhMuc": 288,
      "Mean_6M": 269.83,
      "Std_6M": 61.85,
      "Alert_Level": 2
    },
    {
      "DanhBa": "15112827004",
      "TenKH": "PHAN THI SUONG",
      "GiaBieu": "11",
      "DinhMuc": 0,
      "Mean_6M": 263.33,
      "Std_6M": 45.68,
      "Alert_Level": 2
    },
    {
      "DanhBa": "15062140254",
      "TenKH": "NGUYEN MINH THAI",
      "GiaBieu": "11",
      "DinhMuc": 0,
      "Mean_6M": 251.67,
      "Std_6M": 42.42,
      "Alert_Level": 2
    },
    {
      "DanhBa": "15062140947",
      "TenKH": "LE THI NGOC HONG",
      "GiaBieu": "11",
      "DinhMuc": 0,
      "Mean_6M": 251.17,
      "Std_6M": 63.64,
      "Alert_Level": 2
    },
    {
      "DanhBa": "15062141137",
      "TenKH": "NGUYEN THI TRUONG",
      "GiaBieu": "11",
      "DinhMuc": 16,
      "Mean_6M": 247.67,
      "Std_6M": 38.56,
      "Alert_Level": 2
    },
    {
      "DanhBa": "22103406200",
      "TenKH": "PHAN VAN THO",
      "GiaBieu": "11",
      "DinhMuc": 228,
      "Mean_6M": 244.83,
      "Std_6M": 28.72,
      "Alert_Level": 2
    },
    {
      "DanhBa": "15062140022",
      "TenKH": "NGUYEN THI THANH THUY",
      "GiaBieu": "11",
      "DinhMuc": 0,
      "Mean_6M": 244.5,
      "Std_6M": 257.68,
      "Alert_Level": 2
    },
    {
      "DanhBa": "15112829086",
      "TenKH": "HUYNH VAN TAN",
      "GiaBieu": "11",
      "DinhMuc": 228,
      "Mean_6M": 243.67,
      "Std_6M": 54.68,
      "Alert_Level": 2
    },
    {
      "DanhBa": "15062132406",
      "TenKH": "NGUYEN THI BINH",
      "GiaBieu": "11",
      "DinhMuc": 240,
      "Mean_6M": 241.83,
      "Std_6M": 51.45,
      "Alert_Level": 2
    },
    {
      "DanhBa": "15062132424",
      "TenKH": "TRAN HUU TUAN",
      "GiaBieu": "11",
      "DinhMuc": 4,
      "Mean_6M": 240.17,
      "Std_6M": 34.71,
      "Alert_Level": 2
    },
    {
      "DanhBa": "15112869024",
      "TenKH": "VO VAN TAM",
      "GiaBieu": "11",
      "DinhMuc": 180,
      "Mean_6M": 240.17,
      "Std_6M": 35.8,
      "Alert_Level": 2
    },
    {
      "DanhBa": "22103410149",
      "TenKH": "VUONG TRI DUNG",
      "GiaBieu": "11",
      "DinhMuc": 24,
      "Mean_6M": 238.67,
      "Std_6M": 16.97,
      "Alert_Level": 2
    },
    {
      "DanhBa": "15062140136",
      "TenKH": "DUONG THI MY LINH",
      "GiaBieu": "11",
      "DinhMuc": 292,
      "Mean_6M": 238.0,
      "Std_6M": 36.66,
      "Alert_Level": 2
    },
    {
      "DanhBa": "15062140644",
      "TenKH": "PHAN THI KIM CHUNG",
      "GiaBieu": "11",
      "DinhMuc": 152,
      "Mean_6M": 238.0,
      "Std_6M": 24.96,
      "Alert_Level": 2
    },
    {
      "DanhBa": "15062132325",
      "TenKH": "NGUYEN THI HUONG",
      "GiaBieu": "11",
      "DinhMuc": 20,
      "Mean_6M": 237.67,
      "Std_6M": 14.35,
      "Alert_Level": 2
    },
    {
      "DanhBa": "15062132435",
      "TenKH": "NGUYEN THI BINH",
      "GiaBieu": "11",
      "DinhMuc": 0,
      "Mean_6M": 233.67,
      "Std_6M": 319.08,
      "Alert_Level": 2
    },
    {
      "DanhBa": "15062133408",
      "TenKH": "LY DIEU NGA",
      "GiaBieu": "11",
      "DinhMuc": 0,
      "Mean_6M": 231.33,
      "Std_6M": 63.56,
      "Alert_Level": 2
    },
    {
      "DanhBa": "15062140291",
      "TenKH": "TRAN VAN MINH",
      "GiaBieu": "11",
      "DinhMuc": 500,
      "Mean_6M": 230.5,
      "Std_6M": 209.0,
      "Alert_Level": 2
    },
    {
      "DanhBa": "15112869092",
      "TenKH": "DO THANH BINH",
      "GiaBieu": "11",
      "DinhMuc": 0,
      "Mean_6M": 225.67,
      "Std_6M": 45.79,
      "Alert_Level": 2
    },
    {
      "DanhBa": "15062132258",
      "TenKH": "LE THI MIEN(DD 2 HO)",
      "GiaBieu": "11",
      "DinhMuc": 48,
      "Mean_6M": 224.67,
      "Std_6M": 45.38,
      "Alert_Level": 2
    },
    {
      "DanhBa": "22043310271",
      "TenKH": "TU THI THU NGUYET",
      "GiaBieu": "11",
      "DinhMuc": 0,
      "Mean_6M": 223.83,
      "Std_6M": 61.41,
      "Alert_Level": 2
    },
    {
      "DanhBa": "15112822451",
      "TenKH": "TRINH THI DOAN TRANG",
      "GiaBieu": "11",
      "DinhMuc": 16,
      "Mean_6M": 222.67,
      "Std_6M": 74.05,
      "Alert_Level": 2
    },
    {
      "DanhBa": "15062135393",
      "TenKH": "LA THI THU THAO",
      "GiaBieu": "11",
      "DinhMuc": 276,
      "Mean_6M": 218.33,
      "Std_6M": 46.94,
      "Alert_Level": 2
    },
    {
      "DanhBa": "15062138770",
      "TenKH": "VO MINH HIEU",
      "GiaBieu": "11",
      "DinhMuc": 368,
      "Mean_6M": 216.0,
      "Std_6M": 32.83,
      "Alert_Level": 2
    },
    {
      "DanhBa": "22103410984",
      "TenKH": "NGUYEN THI VY",
      "GiaBieu": "11",
      "DinhMuc": 0,
      "Mean_6M": 212.67,
      "Std_6M": 24.78,
      "Alert_Level": 2
    },
    {
      "DanhBa": "22033276934",
      "TenKH": "TRAN VAN BINH",
      "GiaBieu": "11",
      "DinhMuc": 220,
      "Mean_6M": 211.5,
      "Std_6M": 21.46,
      "Alert_Level": 2
    },
    {
      "DanhBa": "22103410823",
      "TenKH": "NGUYEN PHUC LOC",
      "GiaBieu": "11",
      "DinhMuc": 196,
      "Mean_6M": 210.17,
      "Std_6M": 25.21,
      "Alert_Level": 2
    },
    {
      "DanhBa": "22043310946",
      "TenKH": "VU THI BICH",
      "GiaBieu": "11",
      "DinhMuc": 232,
      "Mean_6M": 208.83,
      "Std_6M": 17.31,
      "Alert_Level": 2
    },
    {
      "DanhBa": "15173421549",
      "TenKH": "NG NGOC NGAN",
      "GiaBieu": "11",
      "DinhMuc": 0,
      "Mean_6M": 205.83,
      "Std_6M": 51.02,
      "Alert_Level": 2
    },
    {
      "DanhBa": "15062133457",
      "TenKH": "NGUYEN TRUNG DAN",
      "GiaBieu": "11",
      "DinhMuc": 144,
      "Mean_6M": 202.33,
      "Std_6M": 53.45,
      "Alert_Level": 2
    },
    {
      "DanhBa": "15112841327",
      "TenKH": "NGUYEN VAN LUONG",
      "GiaBieu": "11",
      "DinhMuc": 0,
      "Mean_6M": 202.0,
      "Std_6M": 45.33,
      "Alert_Level": 2
    },
    {
      "DanhBa": "15062133850",
      "TenKH": "THAN TRONG NINH",
      "GiaBieu": "11",
      "DinhMuc": 0,
      "Mean_6M": 198.33,
      "Std_6M": 28.36,
      "Alert_Level": 2
    },
    {
      "DanhBa": "22073230085",
      "TenKH": "PHAN THI NGOC",
      "GiaBieu": "11",
      "DinhMuc": 252,
      "Mean_6M": 196.33,
      "Std_6M": 26.45,
      "Alert_Level": 2
    },
    {
      "DanhBa": "22103413168",
      "TenKH": "NGUYEN THANH SON",
      "GiaBieu": "11",
      "DinhMuc": 0,
      "Mean_6M": 195.0,
      "Std_6M": 24.07,
      "Alert_Level": 2
    },
    {
      "DanhBa": "15062140980",
      "TenKH": "NGUYEN THI LIEU",
      "GiaBieu": "11",
      "DinhMuc": 212,
      "Mean_6M": 194.0,
      "Std_6M": 23.55,
      "Alert_Level": 2
    },
    {
      "DanhBa": "22043312179",
      "TenKH": "NGUYEN THANH TUOC",
      "GiaBieu": "11",
      "DinhMuc": 60,
      "Mean_6M": 192.83,
      "Std_6M": 31.33,
      "Alert_Level": 2
    },
    {
      "DanhBa": "22043310495",
      "TenKH": "NGUYEN THI HOANG YEN",
      "GiaBieu": "11",
      "DinhMuc": 204,
      "Mean_6M": 188.67,
      "Std_6M": 25.35,
      "Alert_Level": 2
    },
    {
      "DanhBa": "15062134495",
      "TenKH": "PHUNG HUU HAT",
      "GiaBieu": "11",
      "DinhMuc": 12,
      "Mean_6M": 186.83,
      "Std_6M": 20.87,
      "Alert_Level": 2
    },
    {
      "DanhBa": "15062134475",
      "TenKH": "LE THI TINH",
      "GiaBieu": "11",
      "DinhMuc": 20,
      "Mean_6M": 185.17,
      "Std_6M": 29.98,
      "Alert_Level": 2
    },
    {
      "DanhBa": "15122884634",
      "TenKH": "NGUYEN TRONG THANH",
      "GiaBieu": "11",
      "DinhMuc": 0,
      "Mean_6M": 182.83,
      "Std_6M": 39.52,
      "Alert_Level": 2
    },
    {
      "DanhBa": "15062140879",
      "TenKH": "TRUONG THI ANH",
      "GiaBieu": "11",
      "DinhMuc": 276,
      "Mean_6M": 182.0,
      "Std_6M": 32.78,
      "Alert_Level": 2
    },
    {
      "DanhBa": "15062138209",
      "TenKH": "NGUYEN THANH DUY",
      "GiaBieu": "11",
      "DinhMuc": 4,
      "Mean_6M": 181.67,
      "Std_6M": 39.27,
      "Alert_Level": 2
    },
    {
      "DanhBa": "22043271135",
      "TenKH": "NGUYEN THANH BINH",
      "GiaBieu": "11",
      "DinhMuc": 0,
      "Mean_6M": 180.83,
      "Std_6M": 22.09,
      "Alert_Level": 2
    },
    {
      "DanhBa": "22043308322",
      "TenKH": "DO THI TAN",
      "GiaBieu": "11",
      "DinhMuc": 12,
      "Mean_6M": 178.5,
      "Std_6M": 29.37,
      "Alert_Level": 2
    },
    {
      "DanhBa": "22103405060",
      "TenKH": "NGUYEN VAN CHAO",
      "GiaBieu": "11",
      "DinhMuc": 204,
      "Mean_6M": 178.33,
      "Std_6M": 25.59,
      "Alert_Level": 2
    },
    {
      "DanhBa": "15062140848",
      "TenKH": "NGUYEN THI THUY HANG",
      "GiaBieu": "11",
      "DinhMuc": 0,
      "Mean_6M": 178.33,
      "Std_6M": 23.84,
      "Alert_Level": 2
    },
    {
      "DanhBa": "15112829208",
      "TenKH": "LE NGOC NGHIA",
      "GiaBieu": "11",
      "DinhMuc": 240,
      "Mean_6M": 177.5,
      "Std_6M": 44.14,
      "Alert_Level": 2
    },
    {
      "DanhBa": "22033254890",
      "TenKH": "NGUYEN DUC PHUONG",
      "GiaBieu": "11",
      "DinhMuc": 292,
      "Mean_6M": 177.33,
      "Std_6M": 29.76,
      "Alert_Level": 2
    },
    {
      "DanhBa": "22033276267",
      "TenKH": "NGUYEN VAN TA",
      "GiaBieu": "11",
      "DinhMuc": 256,
      "Mean_6M": 176.67,
      "Std_6M": 23.38,
      "Alert_Level": 2
    },
    {
      "DanhBa": "15072461144",
      "TenKH": "TRAN THI THANH VAN",
      "GiaBieu": "11",
      "DinhMuc": 196,
      "Mean_6M": 175.5,
      "Std_6M": 43.61,
      "Alert_Level": 2
    },
    {
      "DanhBa": "15062137955",
      "TenKH": "TRAN THI PHAI (DD 47 HO)",
      "GiaBieu": "11",
      "DinhMuc": 28,
      "Mean_6M": 175.33,
      "Std_6M": 15.21,
      "Alert_Level": 2
    },
    {
      "DanhBa": "15062131288",
      "TenKH": "VU THI ANH TUYET",
      "GiaBieu": "11",
      "DinhMuc": 128,
      "Mean_6M": 174.17,
      "Std_6M": 59.09,
      "Alert_Level": 2
    },
    {
      "DanhBa": "15062135398",
      "TenKH": "NGUYEN THI HONG NHUNG",
      "GiaBieu": "11",
      "DinhMuc": 0,
      "Mean_6M": 174.0,
      "Std_6M": 40.21,
      "Alert_Level": 2
    },
    {
      "DanhBa": "22043290121",
      "TenKH": "NGUYEN NGOC THANH",
      "GiaBieu": "11",
      "DinhMuc": 76,
      "Mean_6M": 170.5,
      "Std_6M": 15.53,
      "Alert_Level": 2
    },
    {
      "DanhBa": "15062134467",
      "TenKH": "PHAN MAU NINH",
      "GiaBieu": "11",
      "DinhMuc": 220,
      "Mean_6M": 169.0,
      "Std_6M": 61.53,
      "Alert_Level": 2
    },
    {
      "DanhBa": "22043290152",
      "TenKH": "DANG THI MY PHUONG",
      "GiaBieu": "11",
      "DinhMuc": 12,
      "Mean_6M": 168.33,
      "Std_6M": 19.72,
      "Alert_Level": 2
    },
    {
      "DanhBa": "22103408338",
      "TenKH": "LE THI THANH VAN",
      "GiaBieu": "11",
      "DinhMuc": 244,
      "Mean_6M": 167.83,
      "Std_6M": 22.84,
      "Alert_Level": 2
    },
    {
      "DanhBa": "22033272081",
      "TenKH": "LE THI THAI LAN",
      "GiaBieu": "11",
      "DinhMuc": 268,
      "Mean_6M": 166.17,
      "Std_6M": 18.31,
      "Alert_Level": 2
    },
    {
      "DanhBa": "22103396350",
      "TenKH": "NGUYEN VAN TRONG",
      "GiaBieu": "11",
      "DinhMuc": 144,
      "Mean_6M": 165.5,
      "Std_6M": 22.16,
      "Alert_Level": 2
    },
    {
      "DanhBa": "22103413306",
      "TenKH": "NGUYEN THANH SON",
      "GiaBieu": "11",
      "DinhMuc": 0,
      "Mean_6M": 164.17,
      "Std_6M": 26.5,
      "Alert_Level": 2
    },
    {
      "DanhBa": "22043304048",
      "TenKH": "TRAN VAN SUNG",
      "GiaBieu": "11",
      "DinhMuc": 188,
      "Mean_6M": 164.0,
      "Std_6M": 7.4,
      "Alert_Level": 2
    },
    {
      "DanhBa": "15102743304",
      "TenKH": "PHAM XUAN CANH",
      "GiaBieu": "11",
      "DinhMuc": 112,
      "Mean_6M": 163.83,
      "Std_6M": 21.61,
      "Alert_Level": 2
    },
    {
      "DanhBa": "22103411063",
      "TenKH": "VUONG TRI DUNG",
      "GiaBieu": "11",
      "DinhMuc": 92,
      "Mean_6M": 163.0,
      "Std_6M": 109.58,
      "Alert_Level": 2
    },
    {
      "DanhBa": "22043304414",
      "TenKH": "NGUYEN VAN KHUYEN",
      "GiaBieu": "11",
      "DinhMuc": 128,
      "Mean_6M": 162.67,
      "Std_6M": 17.91,
      "Alert_Level": 2
    },
    {
      "DanhBa": "15122886912",
      "TenKH": "NGUYEN THI SAU",
      "GiaBieu": "11",
      "DinhMuc": 4,
      "Mean_6M": 162.67,
      "Std_6M": 99.51,
      "Alert_Level": 2
    },
    {
      "DanhBa": "15062133579",
      "TenKH": "NGUYEN THI PHONG",
      "GiaBieu": "11",
      "DinhMuc": 68,
      "Mean_6M": 162.17,
      "Std_6M": 21.98,
      "Alert_Level": 2
    },
    {
      "DanhBa": "22103394033",
      "TenKH": "NGUYEN VAN QUANG",
      "GiaBieu": "11",
      "DinhMuc": 0,
      "Mean_6M": 161.83,
      "Std_6M": 63.59,
      "Alert_Level": 2
    },
    {
      "DanhBa": "15112866333",
      "TenKH": "NGO HOANG YEN",
      "GiaBieu": "11",
      "DinhMuc": 0,
      "Mean_6M": 161.83,
      "Std_6M": 263.14,
      "Alert_Level": 2
    },
    {
      "DanhBa": "15062135950",
      "TenKH": "BUI THI PHUONG",
      "GiaBieu": "11",
      "DinhMuc": 28,
      "Mean_6M": 160.83,
      "Std_6M": 14.74,
      "Alert_Level": 2
    },
    {
      "DanhBa": "15122891165",
      "TenKH": "LE HONG NGOC",
      "GiaBieu": "11",
      "DinhMuc": 0,
      "Mean_6M": 160.0,
      "Std_6M": 28.2,
      "Alert_Level": 2
    },
    {
      "DanhBa": "15062132193",
      "TenKH": "BUI THI LONG THUY",
      "GiaBieu": "11",
      "DinhMuc": 108,
      "Mean_6M": 157.5,
      "Std_6M": 28.87,
      "Alert_Level": 2
    },
    {
      "DanhBa": "15062132439",
      "TenKH": "TRAN THI BUOI",
      "GiaBieu": "11",
      "DinhMuc": 96,
      "Mean_6M": 157.17,
      "Std_6M": 51.32,
      "Alert_Level": 2
    },
    {
      "DanhBa": "22103408734",
      "TenKH": "TRINH KHAC CONG",
      "GiaBieu": "11",
      "DinhMuc": 0,
      "Mean_6M": 157.0,
      "Std_6M": 16.84,
      "Alert_Level": 2
    },
    {
      "DanhBa": "15112848044",
      "TenKH": "HOANG THI HUONG",
      "GiaBieu": "11",
      "DinhMuc": 108,
      "Mean_6M": 156.33,
      "Std_6M": 34.29,
      "Alert_Level": 2
    },
    {
      "DanhBa": "15062133795",
      "TenKH": "NGUYEN VO THU CHAU",
      "GiaBieu": "11",
      "DinhMuc": 160,
      "Mean_6M": 156.0,
      "Std_6M": 26.23,
      "Alert_Level": 2
    },
    {
      "DanhBa": "22103410817",
      "TenKH": "NGUYEN HUYNH KIM NGAN",
      "GiaBieu": "11",
      "DinhMuc": 32,
      "Mean_6M": 156.0,
      "Std_6M": 75.84,
      "Alert_Level": 2
    },
    {
      "DanhBa": "15062140005",
      "TenKH": "PHAM THI THU VAN",
      "GiaBieu": "11",
      "DinhMuc": 148,
      "Mean_6M": 155.83,
      "Std_6M": 53.09,
      "Alert_Level": 2
    },
    {
      "DanhBa": "15062141230",
      "TenKH": "TRAN DUOC",
      "GiaBieu": "11",
      "DinhMuc": 92,
      "Mean_6M": 155.33,
      "Std_6M": 34.02,
      "Alert_Level": 2
    },
    {
      "DanhBa": "15122860729",
      "TenKH": "BUI XUAN LOI",
      "GiaBieu": "11",
      "DinhMuc": 0,
      "Mean_6M": 154.17,
      "Std_6M": 46.5,
      "Alert_Level": 2
    },
    {
      "DanhBa": "15112823286",
      "TenKH": "HUYNH MINH TIEN",
      "GiaBieu": "11",
      "DinhMuc": 0,
      "Mean_6M": 154.17,
      "Std_6M": 56.29,
      "Alert_Level": 2
    },
    {
      "DanhBa": "15112868984",
      "TenKH": "NGUYEN TRUONG HONG THAI",
      "GiaBieu": "11",
      "DinhMuc": 0,
      "Mean_6M": 154.0,
      "Std_6M": 27.0,
      "Alert_Level": 2
    },
    {
      "DanhBa": "15062138249",
      "TenKH": "TRAN THI KIM CUC",
      "GiaBieu": "11",
      "DinhMuc": 24,
      "Mean_6M": 153.67,
      "Std_6M": 148.21,
      "Alert_Level": 2
    },
    {
      "DanhBa": "22103410818",
      "TenKH": "NGUYEN HUYNH KIM NGAN",
      "GiaBieu": "11",
      "DinhMuc": 56,
      "Mean_6M": 153.33,
      "Std_6M": 25.23,
      "Alert_Level": 2
    },
    {
      "DanhBa": "15062133370",
      "TenKH": "NGUYEN NGOC THANH",
      "GiaBieu": "11",
      "DinhMuc": 0,
      "Mean_6M": 153.17,
      "Std_6M": 111.8,
      "Alert_Level": 2
    },
    {
      "DanhBa": "22073231002",
      "TenKH": "VO THI TUONG VY",
      "GiaBieu": "11",
      "DinhMuc": 168,
      "Mean_6M": 153.17,
      "Std_6M": 24.32,
      "Alert_Level": 2
    },
    {
      "DanhBa": "15062135406",
      "TenKH": "NGUYEN  HUU NGHIA (DD 17 HO)",
      "GiaBieu": "11",
      "DinhMuc": 92,
      "Mean_6M": 151.5,
      "Std_6M": 54.91,
      "Alert_Level": 2
    },
    {
      "DanhBa": "22103413127",
      "TenKH": "NGUYEN THANH TUNG",
      "GiaBieu": "11",
      "DinhMuc": 0,
      "Mean_6M": 151.0,
      "Std_6M": 71.99,
      "Alert_Level": 2
    },
    {
      "DanhBa": "15062132117",
      "TenKH": "HUYNH HOAI SON",
      "GiaBieu": "11",
      "DinhMuc": 76,
      "Mean_6M": 150.0,
      "Std_6M": 77.83,
      "Alert_Level": 2
    },
    {
      "DanhBa": "22103396680",
      "TenKH": "BUI THANH SANG",
      "GiaBieu": "11",
      "DinhMuc": 20,
      "Mean_6M": 149.0,
      "Std_6M": 306.21,
      "Alert_Level": 2
    },
    {
      "DanhBa": "22073234421",
      "TenKH": "DO VAN QUYET",
      "GiaBieu": "11",
      "DinhMuc": 0,
      "Mean_6M": 146.83,
      "Std_6M": 45.99,
      "Alert_Level": 2
    },
    {
      "DanhBa": "22043311165",
      "TenKH": "VO THI LAN HUONG",
      "GiaBieu": "11",
      "DinhMuc": 108,
      "Mean_6M": 146.0,
      "Std_6M": 67.89,
      "Alert_Level": 2
    },
    {
      "DanhBa": "15112868557",
      "TenKH": "VU VAN DOAN",
      "GiaBieu": "11",
      "DinhMuc": 128,
      "Mean_6M": 141.67,
      "Std_6M": 54.81,
      "Alert_Level": 2
    },
    {
      "DanhBa": "15062141289",
      "TenKH": "HUỲNH THỊ THANH THỦY",
      "GiaBieu": "11",
      "DinhMuc": 0,
      "Mean_6M": 138.67,
      "Std_6M": 96.09,
      "Alert_Level": 2
    },
    {
      "DanhBa": "15062133561",
      "TenKH": "TRAN MINH QUANG",
      "GiaBieu": "11",
      "DinhMuc": 156,
      "Mean_6M": 138.5,
      "Std_6M": 59.4,
      "Alert_Level": 2
    },
    {
      "DanhBa": "22043303251",
      "TenKH": "NGUYEN THI NGOC NGAN",
      "GiaBieu": "11",
      "DinhMuc": 12,
      "Mean_6M": 135.17,
      "Std_6M": 126.15,
      "Alert_Level": 2
    },
    {
      "DanhBa": "15062137351",
      "TenKH": "NGUYEN QUYET THANG",
      "GiaBieu": "11",
      "DinhMuc": 4,
      "Mean_6M": 133.17,
      "Std_6M": 317.38,
      "Alert_Level": 2
    },
    {
      "DanhBa": "15062141195",
      "TenKH": "TRINH THAI QUYNH LAM",
      "GiaBieu": "11",
      "DinhMuc": 128,
      "Mean_6M": 125.0,
      "Std_6M": 129.17,
      "Alert_Level": 2
    },
    {
      "DanhBa": "22103411336",
      "TenKH": "HUYNH VAN TAI",
      "GiaBieu": "11",
      "DinhMuc": 0,
      "Mean_6M": 123.5,
      "Std_6M": 301.04,
      "Alert_Level": 2
    },
    {
      "DanhBa": "15112828829",
      "TenKH": "HA DUC TRONG",
      "GiaBieu": "11",
      "DinhMuc": 0,
      "Mean_6M": 121.67,
      "Std_6M": 168.55,
      "Alert_Level": 2
    },
    {
      "DanhBa": "22043310289",
      "TenKH": "DO MAU BINH MINH",
      "GiaBieu": "11",
      "DinhMuc": 0,
      "Mean_6M": 114.33,
      "Std_6M": 237.04,
      "Alert_Level": 2
    },
    {
      "DanhBa": "22033270572",
      "TenKH": "TRAN THI HANG",
      "GiaBieu": "11",
      "DinhMuc": 0,
      "Mean_6M": 112.5,
      "Std_6M": 275.57,
      "Alert_Level": 2
    },
    {
      "DanhBa": "22043290252",
      "TenKH": "LE THI TRINH",
      "GiaBieu": "11",
      "DinhMuc": 0,
      "Mean_6M": 109.67,
      "Std_6M": 184.51,
      "Alert_Level": 2
    },
    {
      "DanhBa": "22043313300",
      "TenKH": "DANG THANH VIET",
      "GiaBieu": "11",
      "DinhMuc": 4,
      "Mean_6M": 125.5,
      "Std_6M": 27.92,
      "Alert_Level": 3
    },
    {
      "DanhBa": "22103408736",
      "TenKH": "NGUYEN VAN HUONG",
      "GiaBieu": "11",
      "DinhMuc": 4,
      "Mean_6M": 123.67,
      "Std_6M": 13.11,
      "Alert_Level": 3
    },
    {
      "DanhBa": "22043304402",
      "TenKH": "NGUYEN THI BAY",
      "GiaBieu": "11",
      "DinhMuc": 4,
      "Mean_6M": 114.0,
      "Std_6M": 13.04,
      "Alert_Level": 3
    },
    {
      "DanhBa": "22043309947",
      "TenKH": "TRAN DINH SAN",
      "GiaBieu": "11",
      "DinhMuc": 4,
      "Mean_6M": 113.17,
      "Std_6M": 50.87,
      "Alert_Level": 3
    },
    {
      "DanhBa": "15062140993",
      "TenKH": "NGUYEN TRAN KHUONG",
      "GiaBieu": "11",
      "DinhMuc": 4,
      "Mean_6M": 110.83,
      "Std_6M": 22.34,
      "Alert_Level": 3
    },
    {
      "DanhBa": "15112828508",
      "TenKH": NaN,
      "GiaBieu": "11",
      "DinhMuc": 4,
      "Mean_6M": 105.67,
      "Std_6M": 32.18,
      "Alert_Level": 3
    },
    {
      "DanhBa": "15072428792",
      "TenKH": "LU QUOC TRUNG",
      "GiaBieu": "11",
      "DinhMuc": 4,
      "Mean_6M": 99.83,
      "Std_6M": 39.7,
      "Alert_Level": 3
    },
    {
      "DanhBa": "15122889844",
      "TenKH": "NGUYEN VAN CHUC",
      "GiaBieu": "11",
      "DinhMuc": 4,
      "Mean_6M": 88.5,
      "Std_6M": 10.52,
      "Alert_Level": 3
    },
    {
      "DanhBa": "15062138301",
      "TenKH": "NGUYEN VAN PHONG",
      "GiaBieu": "11",
      "DinhMuc": 4,
      "Mean_6M": 88.17,
      "Std_6M": 86.03,
      "Alert_Level": 3
    },
    {
      "DanhBa": "22033278412",
      "TenKH": "TRUONG THI LUYEN",
      "GiaBieu": "11",
      "DinhMuc": 4,
      "Mean_6M": 85.83,
      "Std_6M": 4.49,
      "Alert_Level": 3
    },
    {
      "DanhBa": "15112846600",
      "TenKH": "LA QUOC THAI",
      "GiaBieu": "11",
      "DinhMuc": 4,
      "Mean_6M": 83.0,
      "Std_6M": 13.99,
      "Alert_Level": 3
    },
    {
      "DanhBa": "15112826000",
      "TenKH": "PHAM THUY LINH",
      "GiaBieu": "11",
      "DinhMuc": 4,
      "Mean_6M": 82.67,
      "Std_6M": 110.88,
      "Alert_Level": 3
    },
    {
      "DanhBa": "15122886561",
      "TenKH": "PHUNG QUOC DUNG",
      "GiaBieu": "11",
      "DinhMuc": 4,
      "Mean_6M": 76.33,
      "Std_6M": 10.33,
      "Alert_Level": 3
    },
    {
      "DanhBa": "15122890487",
      "TenKH": "HO NHU TAM",
      "GiaBieu": "11",
      "DinhMuc": 4,
      "Mean_6M": 74.83,
      "Std_6M": 11.43,
      "Alert_Level": 3
    },
    {
      "DanhBa": "22103413844",
      "TenKH": "DINH QUANG TRI",
      "GiaBieu": "11",
      "DinhMuc": 4,
      "Mean_6M": 71.0,
      "Std_6M": 15.58,
      "Alert_Level": 3
    },
    {
      "DanhBa": "22103390801",
      "TenKH": "VAN NU PHAN THANH THAO",
      "GiaBieu": "11",
      "DinhMuc": 4,
      "Mean_6M": 69.83,
      "Std_6M": 13.0,
      "Alert_Level": 3
    },
    {
      "DanhBa": "15122890775",
      "TenKH": "NGUYEN BA CANH",
      "GiaBieu": "11",
      "DinhMuc": 4,
      "Mean_6M": 69.83,
      "Std_6M": 60.97,
      "Alert_Level": 3
    },
    {
      "DanhBa": "22033257862",
      "TenKH": "HUYNH XUAN HIEP",
      "GiaBieu": "11",
      "DinhMuc": 4,
      "Mean_6M": 68.5,
      "Std_6M": 1.05,
      "Alert_Level": 3
    },
    {
      "DanhBa": "15112822397",
      "TenKH": "CAO THI MINH TAM",
      "GiaBieu": "11",
      "DinhMuc": 4,
      "Mean_6M": 67.83,
      "Std_6M": 10.38,
      "Alert_Level": 3
    },
    {
      "DanhBa": "22033273104",
      "TenKH": "TRAN TRONG DAI",
      "GiaBieu": "11",
      "DinhMuc": 4,
      "Mean_6M": 65.0,
      "Std_6M": 8.67,
      "Alert_Level": 3
    },
    {
      "DanhBa": "22103391241",
      "TenKH": "BUI QUANG TRU",
      "GiaBieu": "11",
      "DinhMuc": 4,
      "Mean_6M": 64.5,
      "Std_6M": 3.15,
      "Alert_Level": 3
    },
    {
      "DanhBa": "22043300175",
      "TenKH": "HA THI NGOC SUONG",
      "GiaBieu": "11",
      "DinhMuc": 4,
      "Mean_6M": 63.67,
      "Std_6M": 32.57,
      "Alert_Level": 3
    },
    {
      "DanhBa": "15062141177",
      "TenKH": "NGUYEN QUANG THAO",
      "GiaBieu": "11",
      "DinhMuc": 4,
      "Mean_6M": 63.67,
      "Std_6M": 16.72,
      "Alert_Level": 3
    },
    {
      "DanhBa": "22103413845",
      "TenKH": "HO THI HIEP",
      "GiaBieu": "11",
      "DinhMuc": 4,
      "Mean_6M": 60.33,
      "Std_6M": 10.35,
      "Alert_Level": 3
    },
    {
      "DanhBa": "22043298609",
      "TenKH": "NGUYEN THI HONG HUE",
      "GiaBieu": "11",
      "DinhMuc": 4,
      "Mean_6M": 60.0,
      "Std_6M": 3.95,
      "Alert_Level": 3
    },
    {
      "DanhBa": "22043313345",
      "TenKH": "LUU THANH BINH",
      "GiaBieu": "11",
      "DinhMuc": 4,
      "Mean_6M": 60.0,
      "Std_6M": 8.58,
      "Alert_Level": 3
    },
    {
      "DanhBa": "15062141131",
      "TenKH": "DO NGOC HOANG",
      "GiaBieu": "11",
      "DinhMuc": 4,
      "Mean_6M": 58.83,
      "Std_6M": 14.66,
      "Alert_Level": 3
    },
    {
      "DanhBa": "15062141156",
      "TenKH": "NGUYEN QUANG THAO",
      "GiaBieu": "11",
      "DinhMuc": 4,
      "Mean_6M": 58.33,
      "Std_6M": 6.35,
      "Alert_Level": 3
    },
    {
      "DanhBa": "15112821478",
      "TenKH": "TRAN QUOC DINH",
      "GiaBieu": "11",
      "DinhMuc": 4,
      "Mean_6M": 57.67,
      "Std_6M": 31.94,
      "Alert_Level": 3
    },
    {
      "DanhBa": "15062133096",
      "TenKH": "DINH QUANG HONG",
      "GiaBieu": "11",
      "DinhMuc": 4,
      "Mean_6M": 56.17,
      "Std_6M": 17.34,
      "Alert_Level": 3
    },
    {
      "DanhBa": "22043313218",
      "TenKH": "NGUYEN THANH THANH",
      "GiaBieu": "11",
      "DinhMuc": 4,
      "Mean_6M": 55.33,
      "Std_6M": 59.12,
      "Alert_Level": 3
    },
    {
      "DanhBa": "15062130190",
      "TenKH": "TRUONG TRI TU HUYNH",
      "GiaBieu": "11",
      "DinhMuc": 4,
      "Mean_6M": 55.17,
      "Std_6M": 19.46,
      "Alert_Level": 3
    },
    {
      "DanhBa": "22103400868",
      "TenKH": "PHAN MINH THANH",
      "GiaBieu": "11",
      "DinhMuc": 4,
      "Mean_6M": 55.0,
      "Std_6M": 12.96,
      "Alert_Level": 3
    },
    {
      "DanhBa": "15062136849",
      "TenKH": "LE THI HUE",
      "GiaBieu": "11",
      "DinhMuc": 4,
      "Mean_6M": 53.5,
      "Std_6M": 8.85,
      "Alert_Level": 3
    },
    {
      "DanhBa": "22043270090",
      "TenKH": "HOANG MANH TUNG",
      "GiaBieu": "11",
      "DinhMuc": 4,
      "Mean_6M": 51.33,
      "Std_6M": 4.93,
      "Alert_Level": 3
    },
    {
      "DanhBa": "15062141158",
      "TenKH": "TRAN MANH CUONG",
      "GiaBieu": "11",
      "DinhMuc": 4,
      "Mean_6M": 51.0,
      "Std_6M": 13.65,
      "Alert_Level": 3
    },
    {
      "DanhBa": "15062133212",
      "TenKH": "DAO NGOC QUAN",
      "GiaBieu": "11",
      "DinhMuc": 4,
      "Mean_6M": 50.33,
      "Std_6M": 14.35,
      "Alert_Level": 3
    },
    {
      "DanhBa": "22043309605",
      "TenKH": "HUYNH THI NHON THIEN",
      "GiaBieu": "11",
      "DinhMuc": 4,
      "Mean_6M": 50.33,
      "Std_6M": 48.21,
      "Alert_Level": 3
    },
    {
      "DanhBa": "22043311167",
      "TenKH": "VU VAN TAM",
      "GiaBieu": "11",
      "DinhMuc": 4,
      "Mean_6M": 50.33,
      "Std_6M": 5.79,
      "Alert_Level": 3
    }
  ]
};