// Auto-generated by fetch_doc_nguoc.js – 09:20:14 28/4/2026
// Nguồn: DULIEU.dbo.SANLUONG – SQL Server 192.168.17.19
const TAWACO_DOC_NGUOC = {
  "lastUpdated": "09:20:14 28/4/2026",
  "nguonDuLieu": "Bảng SANLUONG – Kỳ 03 / Năm 2026",
  "nam": 2026,
  "ky": "03",
  "tongKH": 246216,
  "nguong_tyLe": 10,
  "nguong_absM3": 100,
  "tongLoi": {
    "docNguoc": 0,
    "batKhaThi": 67,
    "dotNgot0": 76,
    "total": 143
  },
  "phanBoDMA": [
    {
      "dma": "Không rõ",
      "docNguoc": 0,
      "batKhaThi": 12,
      "dotNgot0": 15,
      "tong": 27
    },
    {
      "dma": "17.7.1",
      "docNguoc": 0,
      "batKhaThi": 2,
      "dotNgot0": 9,
      "tong": 11
    },
    {
      "dma": "APD.1",
      "docNguoc": 0,
      "batKhaThi": 5,
      "dotNgot0": 3,
      "tong": 8
    },
    {
      "dma": "6.7.1",
      "docNguoc": 0,
      "batKhaThi": 1,
      "dotNgot0": 7,
      "tong": 8
    },
    {
      "dma": "5.7.1",
      "docNguoc": 0,
      "batKhaThi": 2,
      "dotNgot0": 2,
      "tong": 4
    },
    {
      "dma": "TX-TL.2",
      "docNguoc": 0,
      "batKhaThi": 1,
      "dotNgot0": 3,
      "tong": 4
    },
    {
      "dma": "HT.2",
      "docNguoc": 0,
      "batKhaThi": 3,
      "dotNgot0": 0,
      "tong": 3
    },
    {
      "dma": "12.1",
      "docNguoc": 0,
      "batKhaThi": 3,
      "dotNgot0": 0,
      "tong": 3
    },
    {
      "dma": "TL.2",
      "docNguoc": 0,
      "batKhaThi": 2,
      "dotNgot0": 1,
      "tong": 3
    },
    {
      "dma": "TCH.4_2",
      "docNguoc": 0,
      "batKhaThi": 1,
      "dotNgot0": 2,
      "tong": 3
    },
    {
      "dma": "HT-TTH.1",
      "docNguoc": 0,
      "batKhaThi": 1,
      "dotNgot0": 2,
      "tong": 3
    },
    {
      "dma": "4.1",
      "docNguoc": 0,
      "batKhaThi": 0,
      "dotNgot0": 3,
      "tong": 3
    },
    {
      "dma": "5.1",
      "docNguoc": 0,
      "batKhaThi": 0,
      "dotNgot0": 3,
      "tong": 3
    },
    {
      "dma": "TTN.2",
      "docNguoc": 0,
      "batKhaThi": 1,
      "dotNgot0": 1,
      "tong": 2
    },
    {
      "dma": "DHT.1",
      "docNguoc": 0,
      "batKhaThi": 1,
      "dotNgot0": 1,
      "tong": 2
    },
    {
      "dma": "TMT.1",
      "docNguoc": 0,
      "batKhaThi": 1,
      "dotNgot0": 1,
      "tong": 2
    },
    {
      "dma": "TA.1",
      "docNguoc": 0,
      "batKhaThi": 2,
      "dotNgot0": 0,
      "tong": 2
    },
    {
      "dma": "TTN.1_MR",
      "docNguoc": 0,
      "batKhaThi": 1,
      "dotNgot0": 1,
      "tong": 2
    },
    {
      "dma": "TMT.2",
      "docNguoc": 0,
      "batKhaThi": 2,
      "dotNgot0": 0,
      "tong": 2
    },
    {
      "dma": "TTH.1",
      "docNguoc": 0,
      "batKhaThi": 2,
      "dotNgot0": 0,
      "tong": 2
    },
    {
      "dma": "9.1.1",
      "docNguoc": 0,
      "batKhaThi": 1,
      "dotNgot0": 1,
      "tong": 2
    },
    {
      "dma": "6.1.2",
      "docNguoc": 0,
      "batKhaThi": 1,
      "dotNgot0": 1,
      "tong": 2
    },
    {
      "dma": "3.1.1",
      "docNguoc": 0,
      "batKhaThi": 1,
      "dotNgot0": 1,
      "tong": 2
    },
    {
      "dma": "DHT.3",
      "docNguoc": 0,
      "batKhaThi": 1,
      "dotNgot0": 1,
      "tong": 2
    },
    {
      "dma": "3.3",
      "docNguoc": 0,
      "batKhaThi": 0,
      "dotNgot0": 2,
      "tong": 2
    },
    {
      "dma": "6.1.1",
      "docNguoc": 0,
      "batKhaThi": 0,
      "dotNgot0": 2,
      "tong": 2
    },
    {
      "dma": "10.3",
      "docNguoc": 0,
      "batKhaThi": 0,
      "dotNgot0": 2,
      "tong": 2
    },
    {
      "dma": "7.1.2",
      "docNguoc": 0,
      "batKhaThi": 0,
      "dotNgot0": 2,
      "tong": 2
    },
    {
      "dma": "TA.2.1",
      "docNguoc": 0,
      "batKhaThi": 1,
      "dotNgot0": 0,
      "tong": 1
    },
    {
      "dma": "4.7.1b",
      "docNguoc": 0,
      "batKhaThi": 1,
      "dotNgot0": 0,
      "tong": 1
    },
    {
      "dma": "10.2",
      "docNguoc": 0,
      "batKhaThi": 1,
      "dotNgot0": 0,
      "tong": 1
    },
    {
      "dma": "HT.3_1",
      "docNguoc": 0,
      "batKhaThi": 1,
      "dotNgot0": 0,
      "tong": 1
    },
    {
      "dma": "14.1",
      "docNguoc": 0,
      "batKhaThi": 1,
      "dotNgot0": 0,
      "tong": 1
    },
    {
      "dma": "10.1.1",
      "docNguoc": 0,
      "batKhaThi": 1,
      "dotNgot0": 0,
      "tong": 1
    },
    {
      "dma": "TCH.2",
      "docNguoc": 0,
      "batKhaThi": 1,
      "dotNgot0": 0,
      "tong": 1
    },
    {
      "dma": "HT.1",
      "docNguoc": 0,
      "batKhaThi": 1,
      "dotNgot0": 0,
      "tong": 1
    },
    {
      "dma": "HT.1_MR3",
      "docNguoc": 0,
      "batKhaThi": 1,
      "dotNgot0": 0,
      "tong": 1
    },
    {
      "dma": "HT.1_MR2",
      "docNguoc": 0,
      "batKhaThi": 1,
      "dotNgot0": 0,
      "tong": 1
    },
    {
      "dma": "9.1.3",
      "docNguoc": 0,
      "batKhaThi": 1,
      "dotNgot0": 0,
      "tong": 1
    },
    {
      "dma": "TA.1.1",
      "docNguoc": 0,
      "batKhaThi": 1,
      "dotNgot0": 0,
      "tong": 1
    },
    {
      "dma": "10.1.2",
      "docNguoc": 0,
      "batKhaThi": 1,
      "dotNgot0": 0,
      "tong": 1
    },
    {
      "dma": "TTN.3",
      "docNguoc": 0,
      "batKhaThi": 1,
      "dotNgot0": 0,
      "tong": 1
    },
    {
      "dma": "APD.2",
      "docNguoc": 0,
      "batKhaThi": 1,
      "dotNgot0": 0,
      "tong": 1
    },
    {
      "dma": "14.2",
      "docNguoc": 0,
      "batKhaThi": 1,
      "dotNgot0": 0,
      "tong": 1
    },
    {
      "dma": "HT.2_1",
      "docNguoc": 0,
      "batKhaThi": 1,
      "dotNgot0": 0,
      "tong": 1
    },
    {
      "dma": "HT.2_2",
      "docNguoc": 0,
      "batKhaThi": 1,
      "dotNgot0": 0,
      "tong": 1
    },
    {
      "dma": "TL_1",
      "docNguoc": 0,
      "batKhaThi": 1,
      "dotNgot0": 0,
      "tong": 1
    },
    {
      "dma": "DHT.2",
      "docNguoc": 0,
      "batKhaThi": 1,
      "dotNgot0": 0,
      "tong": 1
    },
    {
      "dma": "8.1",
      "docNguoc": 0,
      "batKhaThi": 0,
      "dotNgot0": 1,
      "tong": 1
    },
    {
      "dma": "9.1.2",
      "docNguoc": 0,
      "batKhaThi": 0,
      "dotNgot0": 1,
      "tong": 1
    },
    {
      "dma": "13.2",
      "docNguoc": 0,
      "batKhaThi": 0,
      "dotNgot0": 1,
      "tong": 1
    },
    {
      "dma": "8.2",
      "docNguoc": 0,
      "batKhaThi": 0,
      "dotNgot0": 1,
      "tong": 1
    },
    {
      "dma": "TMT.3",
      "docNguoc": 0,
      "batKhaThi": 0,
      "dotNgot0": 1,
      "tong": 1
    },
    {
      "dma": "TX.1",
      "docNguoc": 0,
      "batKhaThi": 0,
      "dotNgot0": 1,
      "tong": 1
    },
    {
      "dma": "15.1",
      "docNguoc": 0,
      "batKhaThi": 0,
      "dotNgot0": 1,
      "tong": 1
    },
    {
      "dma": "11.1",
      "docNguoc": 0,
      "batKhaThi": 0,
      "dotNgot0": 1,
      "tong": 1
    },
    {
      "dma": "5.2",
      "docNguoc": 0,
      "batKhaThi": 0,
      "dotNgot0": 1,
      "tong": 1
    },
    {
      "dma": "TA.2",
      "docNguoc": 0,
      "batKhaThi": 0,
      "dotNgot0": 1,
      "tong": 1
    }
  ],
  "docNguocList": [],
  "batKhaThiList": [
    {
      "Danhba": "22033329391",
      "MaDMA": "HT.2",
      "TinhTrang": "DSD",
      "ChiSoCu": 1,
      "ChiSoMoi": 687,
      "KhoiLuongThem": 686,
      "TyLeTang": 687,
      "PhanTramTang": 68600,
      "LoaiLoi": "Tăng Đột Biến"
    },
    {
      "Danhba": "22113420276",
      "MaDMA": "Không rõ",
      "TinhTrang": "DSD",
      "ChiSoCu": 2,
      "ChiSoMoi": 655,
      "KhoiLuongThem": 653,
      "TyLeTang": 327.5,
      "PhanTramTang": 32650,
      "LoaiLoi": "Tăng Đột Biến"
    },
    {
      "Danhba": "22103410808",
      "MaDMA": "TTN.2",
      "TinhTrang": "DSD",
      "ChiSoCu": 2,
      "ChiSoMoi": 338,
      "KhoiLuongThem": 336,
      "TyLeTang": 169,
      "PhanTramTang": 16800,
      "LoaiLoi": "Tăng Đột Biến"
    },
    {
      "Danhba": "22073342752",
      "MaDMA": "TA.2.1",
      "TinhTrang": "DSD",
      "ChiSoCu": 1,
      "ChiSoMoi": 145,
      "KhoiLuongThem": 144,
      "TyLeTang": 145,
      "PhanTramTang": 14400,
      "LoaiLoi": "Tăng Đột Biến"
    },
    {
      "Danhba": "15112867082",
      "MaDMA": "Không rõ",
      "TinhTrang": "DSD",
      "ChiSoCu": 1,
      "ChiSoMoi": 138,
      "KhoiLuongThem": 137,
      "TyLeTang": 138,
      "PhanTramTang": 13700,
      "LoaiLoi": "Tăng Đột Biến"
    },
    {
      "Danhba": "22043312473",
      "MaDMA": "Không rõ",
      "TinhTrang": "DSD",
      "ChiSoCu": 1,
      "ChiSoMoi": 134,
      "KhoiLuongThem": 133,
      "TyLeTang": 134,
      "PhanTramTang": 13300,
      "LoaiLoi": "Tăng Đột Biến"
    },
    {
      "Danhba": "15072460821",
      "MaDMA": "4.7.1b",
      "TinhTrang": "DSD",
      "ChiSoCu": 1,
      "ChiSoMoi": 129,
      "KhoiLuongThem": 128,
      "TyLeTang": 129,
      "PhanTramTang": 12800,
      "LoaiLoi": "Tăng Đột Biến"
    },
    {
      "Danhba": "22113419659",
      "MaDMA": "DHT.1",
      "TinhTrang": "DSD",
      "ChiSoCu": 1,
      "ChiSoMoi": 123,
      "KhoiLuongThem": 122,
      "TyLeTang": 123,
      "PhanTramTang": 12200,
      "LoaiLoi": "Tăng Đột Biến"
    },
    {
      "Danhba": "15122843471",
      "MaDMA": "12.1",
      "TinhTrang": "DSD",
      "ChiSoCu": 1,
      "ChiSoMoi": 116,
      "KhoiLuongThem": 115,
      "TyLeTang": 116,
      "PhanTramTang": 11500,
      "LoaiLoi": "Tăng Đột Biến"
    },
    {
      "Danhba": "22063327157",
      "MaDMA": "APD.1",
      "TinhTrang": "DSD",
      "ChiSoCu": 1,
      "ChiSoMoi": 107,
      "KhoiLuongThem": 106,
      "TyLeTang": 107,
      "PhanTramTang": 10600,
      "LoaiLoi": "Tăng Đột Biến"
    },
    {
      "Danhba": "15102745232",
      "MaDMA": "10.2",
      "TinhTrang": "DSD",
      "ChiSoCu": 5,
      "ChiSoMoi": 409,
      "KhoiLuongThem": 404,
      "TyLeTang": 81.8,
      "PhanTramTang": 8080,
      "LoaiLoi": "Tăng Đột Biến"
    },
    {
      "Danhba": "22013217581",
      "MaDMA": "TMT.1",
      "TinhTrang": "DSD",
      "ChiSoCu": 6,
      "ChiSoMoi": 464,
      "KhoiLuongThem": 458,
      "TyLeTang": 77.3,
      "PhanTramTang": 7633.3,
      "LoaiLoi": "Tăng Đột Biến"
    },
    {
      "Danhba": "22033275942",
      "MaDMA": "HT.3_1",
      "TinhTrang": "DSD",
      "ChiSoCu": 2,
      "ChiSoMoi": 140,
      "KhoiLuongThem": 138,
      "TyLeTang": 70,
      "PhanTramTang": 6900,
      "LoaiLoi": "Tăng Đột Biến"
    },
    {
      "Danhba": "15141934134",
      "MaDMA": "14.1",
      "TinhTrang": "DSD",
      "ChiSoCu": 4,
      "ChiSoMoi": 257,
      "KhoiLuongThem": 253,
      "TyLeTang": 64.3,
      "PhanTramTang": 6325,
      "LoaiLoi": "Tăng Đột Biến"
    },
    {
      "Danhba": "15173427379",
      "MaDMA": "Không rõ",
      "TinhTrang": "DSD",
      "ChiSoCu": 2,
      "ChiSoMoi": 120,
      "KhoiLuongThem": 118,
      "TyLeTang": 60,
      "PhanTramTang": 5900,
      "LoaiLoi": "Tăng Đột Biến"
    },
    {
      "Danhba": "15102728797",
      "MaDMA": "10.1.1",
      "TinhTrang": "DSD",
      "ChiSoCu": 2,
      "ChiSoMoi": 113,
      "KhoiLuongThem": 111,
      "TyLeTang": 56.5,
      "PhanTramTang": 5550,
      "LoaiLoi": "Tăng Đột Biến"
    },
    {
      "Danhba": "22023240719",
      "MaDMA": "TCH.2",
      "TinhTrang": "DSD",
      "ChiSoCu": 15,
      "ChiSoMoi": 772,
      "KhoiLuongThem": 757,
      "TyLeTang": 51.5,
      "PhanTramTang": 5046.7,
      "LoaiLoi": "Tăng Đột Biến"
    },
    {
      "Danhba": "15161905619",
      "MaDMA": "Không rõ",
      "TinhTrang": "DSD",
      "ChiSoCu": 4,
      "ChiSoMoi": 186,
      "KhoiLuongThem": 182,
      "TyLeTang": 46.5,
      "PhanTramTang": 4550,
      "LoaiLoi": "Tăng Đột Biến"
    },
    {
      "Danhba": "22053329311",
      "MaDMA": "Không rõ",
      "TinhTrang": "DSD",
      "ChiSoCu": 27,
      "ChiSoMoi": 1089,
      "KhoiLuongThem": 1062,
      "TyLeTang": 40.3,
      "PhanTramTang": 3933.3,
      "LoaiLoi": "Tăng Đột Biến"
    },
    {
      "Danhba": "22063320005",
      "MaDMA": "APD.1",
      "TinhTrang": "DSD",
      "ChiSoCu": 3,
      "ChiSoMoi": 116,
      "KhoiLuongThem": 113,
      "TyLeTang": 38.7,
      "PhanTramTang": 3766.7,
      "LoaiLoi": "Tăng Đột Biến"
    },
    {
      "Danhba": "15161929897",
      "MaDMA": "Không rõ",
      "TinhTrang": "DSD",
      "ChiSoCu": 5,
      "ChiSoMoi": 188,
      "KhoiLuongThem": 183,
      "TyLeTang": 37.6,
      "PhanTramTang": 3660,
      "LoaiLoi": "Tăng Đột Biến"
    },
    {
      "Danhba": "22063310210",
      "MaDMA": "APD.1",
      "TinhTrang": "DSD",
      "ChiSoCu": 6,
      "ChiSoMoi": 192,
      "KhoiLuongThem": 186,
      "TyLeTang": 32,
      "PhanTramTang": 3100,
      "LoaiLoi": "Tăng Đột Biến"
    },
    {
      "Danhba": "22053299373",
      "MaDMA": "TL.2",
      "TinhTrang": "DSD",
      "ChiSoCu": 4,
      "ChiSoMoi": 127,
      "KhoiLuongThem": 123,
      "TyLeTang": 31.8,
      "PhanTramTang": 3075,
      "LoaiLoi": "Tăng Đột Biến"
    },
    {
      "Danhba": "22033328371",
      "MaDMA": "HT.1",
      "TinhTrang": "DSD",
      "ChiSoCu": 4,
      "ChiSoMoi": 126,
      "KhoiLuongThem": 122,
      "TyLeTang": 31.5,
      "PhanTramTang": 3050,
      "LoaiLoi": "Tăng Đột Biến"
    },
    {
      "Danhba": "22053296146",
      "MaDMA": "Không rõ",
      "TinhTrang": "DSD",
      "ChiSoCu": 4,
      "ChiSoMoi": 125,
      "KhoiLuongThem": 121,
      "TyLeTang": 31.3,
      "PhanTramTang": 3025,
      "LoaiLoi": "Tăng Đột Biến"
    },
    {
      "Danhba": "15173420557",
      "MaDMA": "Không rõ",
      "TinhTrang": "DSD",
      "ChiSoCu": 8,
      "ChiSoMoi": 226,
      "KhoiLuongThem": 218,
      "TyLeTang": 28.3,
      "PhanTramTang": 2725,
      "LoaiLoi": "Tăng Đột Biến"
    },
    {
      "Danhba": "22033271595",
      "MaDMA": "HT.1_MR3",
      "TinhTrang": "DSD",
      "ChiSoCu": 9,
      "ChiSoMoi": 230,
      "KhoiLuongThem": 221,
      "TyLeTang": 25.6,
      "PhanTramTang": 2455.6,
      "LoaiLoi": "Tăng Đột Biến"
    },
    {
      "Danhba": "15052162567",
      "MaDMA": "Không rõ",
      "TinhTrang": "DSD",
      "ChiSoCu": 7,
      "ChiSoMoi": 179,
      "KhoiLuongThem": 172,
      "TyLeTang": 25.6,
      "PhanTramTang": 2457.1,
      "LoaiLoi": "Tăng Đột Biến"
    },
    {
      "Danhba": "22033277552",
      "MaDMA": "HT.1_MR2",
      "TinhTrang": "DSD",
      "ChiSoCu": 5,
      "ChiSoMoi": 128,
      "KhoiLuongThem": 123,
      "TyLeTang": 25.6,
      "PhanTramTang": 2460,
      "LoaiLoi": "Tăng Đột Biến"
    },
    {
      "Danhba": "15122860245",
      "MaDMA": "9.1.3",
      "TinhTrang": "DSD",
      "ChiSoCu": 6,
      "ChiSoMoi": 135,
      "KhoiLuongThem": 129,
      "TyLeTang": 22.5,
      "PhanTramTang": 2150,
      "LoaiLoi": "Tăng Đột Biến"
    },
    {
      "Danhba": "22073242195",
      "MaDMA": "TA.1",
      "TinhTrang": "DSD",
      "ChiSoCu": 8,
      "ChiSoMoi": 173,
      "KhoiLuongThem": 165,
      "TyLeTang": 21.6,
      "PhanTramTang": 2062.5,
      "LoaiLoi": "Tăng Đột Biến"
    },
    {
      "Danhba": "22073230469",
      "MaDMA": "TA.1.1",
      "TinhTrang": "DSD",
      "ChiSoCu": 10,
      "ChiSoMoi": 215,
      "KhoiLuongThem": 205,
      "TyLeTang": 21.5,
      "PhanTramTang": 2050,
      "LoaiLoi": "Tăng Đột Biến"
    },
    {
      "Danhba": "15102721717",
      "MaDMA": "10.1.2",
      "TinhTrang": "DSD",
      "ChiSoCu": 11,
      "ChiSoMoi": 231,
      "KhoiLuongThem": 220,
      "TyLeTang": 21,
      "PhanTramTang": 2000,
      "LoaiLoi": "Tăng Đột Biến"
    },
    {
      "Danhba": "22103401218",
      "MaDMA": "TTN.3",
      "TinhTrang": "DSD",
      "ChiSoCu": 7,
      "ChiSoMoi": 147,
      "KhoiLuongThem": 140,
      "TyLeTang": 21,
      "PhanTramTang": 2000,
      "LoaiLoi": "Tăng Đột Biến"
    },
    {
      "Danhba": "22063324480",
      "MaDMA": "APD.2",
      "TinhTrang": "DSD",
      "ChiSoCu": 7,
      "ChiSoMoi": 131,
      "KhoiLuongThem": 124,
      "TyLeTang": 18.7,
      "PhanTramTang": 1771.4,
      "LoaiLoi": "Tăng Đột Biến"
    },
    {
      "Danhba": "15141937482",
      "MaDMA": "14.2",
      "TinhTrang": "DSD",
      "ChiSoCu": 18,
      "ChiSoMoi": 321,
      "KhoiLuongThem": 303,
      "TyLeTang": 17.8,
      "PhanTramTang": 1683.3,
      "LoaiLoi": "Tăng Đột Biến"
    },
    {
      "Danhba": "22103411819",
      "MaDMA": "TTN.1_MR",
      "TinhTrang": "DSD",
      "ChiSoCu": 7,
      "ChiSoMoi": 121,
      "KhoiLuongThem": 114,
      "TyLeTang": 17.3,
      "PhanTramTang": 1628.6,
      "LoaiLoi": "Tăng Đột Biến"
    },
    {
      "Danhba": "22033277882",
      "MaDMA": "HT.2_1",
      "TinhTrang": "DSD",
      "ChiSoCu": 10,
      "ChiSoMoi": 166,
      "KhoiLuongThem": 156,
      "TyLeTang": 16.6,
      "PhanTramTang": 1560,
      "LoaiLoi": "Tăng Đột Biến"
    },
    {
      "Danhba": "15052170842",
      "MaDMA": "5.7.1",
      "TinhTrang": "DSD",
      "ChiSoCu": 14,
      "ChiSoMoi": 231,
      "KhoiLuongThem": 217,
      "TyLeTang": 16.5,
      "PhanTramTang": 1550,
      "LoaiLoi": "Tăng Đột Biến"
    },
    {
      "Danhba": "22033268322",
      "MaDMA": "HT.2_2",
      "TinhTrang": "DSD",
      "ChiSoCu": 14,
      "ChiSoMoi": 231,
      "KhoiLuongThem": 217,
      "TyLeTang": 16.5,
      "PhanTramTang": 1550,
      "LoaiLoi": "Tăng Đột Biến"
    },
    {
      "Danhba": "15072442453",
      "MaDMA": "17.7.1",
      "TinhTrang": "DSD",
      "ChiSoCu": 13,
      "ChiSoMoi": 210,
      "KhoiLuongThem": 197,
      "TyLeTang": 16.2,
      "PhanTramTang": 1515.4,
      "LoaiLoi": "Tăng Đột Biến"
    },
    {
      "Danhba": "22063320692",
      "MaDMA": "APD.1",
      "TinhTrang": "DSD",
      "ChiSoCu": 31,
      "ChiSoMoi": 485,
      "KhoiLuongThem": 454,
      "TyLeTang": 15.6,
      "PhanTramTang": 1464.5,
      "LoaiLoi": "Tăng Đột Biến"
    },
    {
      "Danhba": "15062132188",
      "MaDMA": "6.7.1",
      "TinhTrang": "DSD",
      "ChiSoCu": 8,
      "ChiSoMoi": 118,
      "KhoiLuongThem": 110,
      "TyLeTang": 14.8,
      "PhanTramTang": 1375,
      "LoaiLoi": "Tăng Đột Biến"
    },
    {
      "Danhba": "22033332787",
      "MaDMA": "HT.2",
      "TinhTrang": "DSD",
      "ChiSoCu": 8,
      "ChiSoMoi": 118,
      "KhoiLuongThem": 110,
      "TyLeTang": 14.8,
      "PhanTramTang": 1375,
      "LoaiLoi": "Tăng Đột Biến"
    },
    {
      "Danhba": "22013220519",
      "MaDMA": "TMT.2",
      "TinhTrang": "DSD",
      "ChiSoCu": 17,
      "ChiSoMoi": 248,
      "KhoiLuongThem": 231,
      "TyLeTang": 14.6,
      "PhanTramTang": 1358.8,
      "LoaiLoi": "Tăng Đột Biến"
    },
    {
      "Danhba": "22053300173",
      "MaDMA": "TL.2",
      "TinhTrang": "DSD",
      "ChiSoCu": 24,
      "ChiSoMoi": 336,
      "KhoiLuongThem": 312,
      "TyLeTang": 14,
      "PhanTramTang": 1300,
      "LoaiLoi": "Tăng Đột Biến"
    },
    {
      "Danhba": "22083369741",
      "MaDMA": "TTH.1",
      "TinhTrang": "DSD",
      "ChiSoCu": 47,
      "ChiSoMoi": 652,
      "KhoiLuongThem": 605,
      "TyLeTang": 13.9,
      "PhanTramTang": 1287.2,
      "LoaiLoi": "Tăng Đột Biến"
    },
    {
      "Danhba": "22043310958",
      "MaDMA": "TL_1",
      "TinhTrang": "DSD",
      "ChiSoCu": 18,
      "ChiSoMoi": 249,
      "KhoiLuongThem": 231,
      "TyLeTang": 13.8,
      "PhanTramTang": 1283.3,
      "LoaiLoi": "Tăng Đột Biến"
    },
    {
      "Danhba": "15072443367",
      "MaDMA": "17.7.1",
      "TinhTrang": "DSD",
      "ChiSoCu": 12,
      "ChiSoMoi": 162,
      "KhoiLuongThem": 150,
      "TyLeTang": 13.5,
      "PhanTramTang": 1250,
      "LoaiLoi": "Tăng Đột Biến"
    },
    {
      "Danhba": "22013223103",
      "MaDMA": "TMT.2",
      "TinhTrang": "DSD",
      "ChiSoCu": 20,
      "ChiSoMoi": 267,
      "KhoiLuongThem": 247,
      "TyLeTang": 13.4,
      "PhanTramTang": 1235,
      "LoaiLoi": "Tăng Đột Biến"
    },
    {
      "Danhba": "22023231303",
      "MaDMA": "TCH.4_2",
      "TinhTrang": "DSD",
      "ChiSoCu": 12,
      "ChiSoMoi": 157,
      "KhoiLuongThem": 145,
      "TyLeTang": 13.1,
      "PhanTramTang": 1208.3,
      "LoaiLoi": "Tăng Đột Biến"
    },
    {
      "Danhba": "15122841228",
      "MaDMA": "12.1",
      "TinhTrang": "DSD",
      "ChiSoCu": 16,
      "ChiSoMoi": 198,
      "KhoiLuongThem": 182,
      "TyLeTang": 12.4,
      "PhanTramTang": 1137.5,
      "LoaiLoi": "Tăng Đột Biến"
    },
    {
      "Danhba": "15031728831",
      "MaDMA": "Không rõ",
      "TinhTrang": "DSD",
      "ChiSoCu": 9,
      "ChiSoMoi": 112,
      "KhoiLuongThem": 103,
      "TyLeTang": 12.4,
      "PhanTramTang": 1144.4,
      "LoaiLoi": "Tăng Đột Biến"
    },
    {
      "Danhba": "15052166583",
      "MaDMA": "5.7.1",
      "TinhTrang": "DSD",
      "ChiSoCu": 23,
      "ChiSoMoi": 277,
      "KhoiLuongThem": 254,
      "TyLeTang": 12,
      "PhanTramTang": 1104.3,
      "LoaiLoi": "Tăng Đột Biến"
    },
    {
      "Danhba": "22053326658",
      "MaDMA": "TX-TL.2",
      "TinhTrang": "DSD",
      "ChiSoCu": 22,
      "ChiSoMoi": 257,
      "KhoiLuongThem": 235,
      "TyLeTang": 11.7,
      "PhanTramTang": 1068.2,
      "LoaiLoi": "Tăng Đột Biến"
    },
    {
      "Danhba": "22083366434",
      "MaDMA": "HT-TTH.1",
      "TinhTrang": "DSD",
      "ChiSoCu": 12,
      "ChiSoMoi": 137,
      "KhoiLuongThem": 125,
      "TyLeTang": 11.4,
      "PhanTramTang": 1041.7,
      "LoaiLoi": "Tăng Đột Biến"
    },
    {
      "Danhba": "22083369392",
      "MaDMA": "TTH.1",
      "TinhTrang": "DSD",
      "ChiSoCu": 19,
      "ChiSoMoi": 209,
      "KhoiLuongThem": 190,
      "TyLeTang": 11,
      "PhanTramTang": 1000,
      "LoaiLoi": "Tăng Đột Biến"
    },
    {
      "Danhba": "15092647915",
      "MaDMA": "9.1.1",
      "TinhTrang": "DSD",
      "ChiSoCu": 33,
      "ChiSoMoi": 360,
      "KhoiLuongThem": 327,
      "TyLeTang": 10.9,
      "PhanTramTang": 990.9,
      "LoaiLoi": "Tăng Đột Biến"
    },
    {
      "Danhba": "22093220063",
      "MaDMA": "DHT.2",
      "TinhTrang": "DSD",
      "ChiSoCu": 13,
      "ChiSoMoi": 142,
      "KhoiLuongThem": 129,
      "TyLeTang": 10.9,
      "PhanTramTang": 992.3,
      "LoaiLoi": "Tăng Đột Biến"
    },
    {
      "Danhba": "22033334193",
      "MaDMA": "HT.2",
      "TinhTrang": "DSD",
      "ChiSoCu": 16,
      "ChiSoMoi": 172,
      "KhoiLuongThem": 156,
      "TyLeTang": 10.8,
      "PhanTramTang": 975,
      "LoaiLoi": "Tăng Đột Biến"
    },
    {
      "Danhba": "15062131320",
      "MaDMA": "6.1.2",
      "TinhTrang": "DSD",
      "ChiSoCu": 12,
      "ChiSoMoi": 128,
      "KhoiLuongThem": 116,
      "TyLeTang": 10.7,
      "PhanTramTang": 966.7,
      "LoaiLoi": "Tăng Đột Biến"
    },
    {
      "Danhba": "15122840814",
      "MaDMA": "12.1",
      "TinhTrang": "DSD",
      "ChiSoCu": 11,
      "ChiSoMoi": 117,
      "KhoiLuongThem": 106,
      "TyLeTang": 10.6,
      "PhanTramTang": 963.6,
      "LoaiLoi": "Tăng Đột Biến"
    },
    {
      "Danhba": "15031700962",
      "MaDMA": "3.1.1",
      "TinhTrang": "DSD",
      "ChiSoCu": 18,
      "ChiSoMoi": 186,
      "KhoiLuongThem": 168,
      "TyLeTang": 10.3,
      "PhanTramTang": 933.3,
      "LoaiLoi": "Tăng Đột Biến"
    },
    {
      "Danhba": "22043302461",
      "MaDMA": "Không rõ",
      "TinhTrang": "DSD",
      "ChiSoCu": 13,
      "ChiSoMoi": 134,
      "KhoiLuongThem": 121,
      "TyLeTang": 10.3,
      "PhanTramTang": 930.8,
      "LoaiLoi": "Tăng Đột Biến"
    },
    {
      "Danhba": "22073330400",
      "MaDMA": "TA.1",
      "TinhTrang": "DSD",
      "ChiSoCu": 13,
      "ChiSoMoi": 134,
      "KhoiLuongThem": 121,
      "TyLeTang": 10.3,
      "PhanTramTang": 930.8,
      "LoaiLoi": "Tăng Đột Biến"
    },
    {
      "Danhba": "22093217090",
      "MaDMA": "DHT.3",
      "TinhTrang": "DSD",
      "ChiSoCu": 23,
      "ChiSoMoi": 234,
      "KhoiLuongThem": 211,
      "TyLeTang": 10.2,
      "PhanTramTang": 917.4,
      "LoaiLoi": "Tăng Đột Biến"
    },
    {
      "Danhba": "22063328252",
      "MaDMA": "APD.1",
      "TinhTrang": "DSD",
      "ChiSoCu": 14,
      "ChiSoMoi": 143,
      "KhoiLuongThem": 129,
      "TyLeTang": 10.2,
      "PhanTramTang": 921.4,
      "LoaiLoi": "Tăng Đột Biến"
    }
  ],
  "dotNgot0List": [
    {
      "Danhba": "15062137351",
      "MaDMA": "6.7.1",
      "TinhTrang": "DSD",
      "ChiSoCu": 781,
      "ChiSoMoi": 0,
      "KhoiLuongMat": 781,
      "LoaiLoi": "Đột Ngột 0"
    },
    {
      "Danhba": "22113421425",
      "MaDMA": "DHT.1",
      "TinhTrang": "DSD",
      "ChiSoCu": 387,
      "ChiSoMoi": 0,
      "KhoiLuongMat": 387,
      "LoaiLoi": "Đột Ngột 0"
    },
    {
      "Danhba": "15082510035",
      "MaDMA": "8.1",
      "TinhTrang": "DSD",
      "ChiSoCu": 292,
      "ChiSoMoi": 0,
      "KhoiLuongMat": 292,
      "LoaiLoi": "Đột Ngột 0"
    },
    {
      "Danhba": "15173421953",
      "MaDMA": "17.7.1",
      "TinhTrang": "DSD",
      "ChiSoCu": 264,
      "ChiSoMoi": 0,
      "KhoiLuongMat": 264,
      "LoaiLoi": "Đột Ngột 0"
    },
    {
      "Danhba": "15173421479",
      "MaDMA": "17.7.1",
      "TinhTrang": "DSD",
      "ChiSoCu": 218,
      "ChiSoMoi": 0,
      "KhoiLuongMat": 218,
      "LoaiLoi": "Đột Ngột 0"
    },
    {
      "Danhba": "15173424894",
      "MaDMA": "17.7.1",
      "TinhTrang": "DSD",
      "ChiSoCu": 200,
      "ChiSoMoi": 0,
      "KhoiLuongMat": 200,
      "LoaiLoi": "Đột Ngột 0"
    },
    {
      "Danhba": "15173425067",
      "MaDMA": "17.7.1",
      "TinhTrang": "DSD",
      "ChiSoCu": 177,
      "ChiSoMoi": 0,
      "KhoiLuongMat": 177,
      "LoaiLoi": "Đột Ngột 0"
    },
    {
      "Danhba": "15041909705",
      "MaDMA": "3.3",
      "TinhTrang": "DSD",
      "ChiSoCu": 154,
      "ChiSoMoi": 0,
      "KhoiLuongMat": 154,
      "LoaiLoi": "Đột Ngột 0"
    },
    {
      "Danhba": "15042000011",
      "MaDMA": "4.1",
      "TinhTrang": "DSD",
      "ChiSoCu": 153,
      "ChiSoMoi": 0,
      "KhoiLuongMat": 153,
      "LoaiLoi": "Đột Ngột 0"
    },
    {
      "Danhba": "15052120700",
      "MaDMA": "5.1",
      "TinhTrang": "DSD",
      "ChiSoCu": 141,
      "ChiSoMoi": 0,
      "KhoiLuongMat": 141,
      "LoaiLoi": "Đột Ngột 0"
    },
    {
      "Danhba": "15092644875",
      "MaDMA": "9.1.2",
      "TinhTrang": "DSD",
      "ChiSoCu": 129,
      "ChiSoMoi": 0,
      "KhoiLuongMat": 129,
      "LoaiLoi": "Đột Ngột 0"
    },
    {
      "Danhba": "15072444393",
      "MaDMA": "6.7.1",
      "TinhTrang": "DSD",
      "ChiSoCu": 129,
      "ChiSoMoi": 0,
      "KhoiLuongMat": 129,
      "LoaiLoi": "Đột Ngột 0"
    },
    {
      "Danhba": "15062132435",
      "MaDMA": "6.7.1",
      "TinhTrang": "DSD",
      "ChiSoCu": 118,
      "ChiSoMoi": 0,
      "KhoiLuongMat": 118,
      "LoaiLoi": "Đột Ngột 0"
    },
    {
      "Danhba": "15173424772",
      "MaDMA": "17.7.1",
      "TinhTrang": "DSD",
      "ChiSoCu": 114,
      "ChiSoMoi": 0,
      "KhoiLuongMat": 114,
      "LoaiLoi": "Đột Ngột 0"
    },
    {
      "Danhba": "15062139931",
      "MaDMA": "6.1.1",
      "TinhTrang": "DSD",
      "ChiSoCu": 112,
      "ChiSoMoi": 0,
      "KhoiLuongMat": 112,
      "LoaiLoi": "Đột Ngột 0"
    },
    {
      "Danhba": "15031726299",
      "MaDMA": "3.3",
      "TinhTrang": "DSD",
      "ChiSoCu": 107,
      "ChiSoMoi": 0,
      "KhoiLuongMat": 107,
      "LoaiLoi": "Đột Ngột 0"
    },
    {
      "Danhba": "15161909001",
      "MaDMA": "Không rõ",
      "TinhTrang": "DSD",
      "ChiSoCu": 107,
      "ChiSoMoi": 0,
      "KhoiLuongMat": 107,
      "LoaiLoi": "Đột Ngột 0"
    },
    {
      "Danhba": "15102740993",
      "MaDMA": "10.3",
      "TinhTrang": "DSD",
      "ChiSoCu": 105,
      "ChiSoMoi": 0,
      "KhoiLuongMat": 105,
      "LoaiLoi": "Đột Ngột 0"
    },
    {
      "Danhba": "15062134099",
      "MaDMA": "6.1.1",
      "TinhTrang": "DSD",
      "ChiSoCu": 105,
      "ChiSoMoi": 0,
      "KhoiLuongMat": 105,
      "LoaiLoi": "Đột Ngột 0"
    },
    {
      "Danhba": "22043276090",
      "MaDMA": "Không rõ",
      "TinhTrang": "DSD",
      "ChiSoCu": 105,
      "ChiSoMoi": 0,
      "KhoiLuongMat": 105,
      "LoaiLoi": "Đột Ngột 0"
    },
    {
      "Danhba": "22063328343",
      "MaDMA": "APD.1",
      "TinhTrang": "DSD",
      "ChiSoCu": 97,
      "ChiSoMoi": 0,
      "KhoiLuongMat": 97,
      "LoaiLoi": "Đột Ngột 0"
    },
    {
      "Danhba": "15141949077",
      "MaDMA": "Không rõ",
      "TinhTrang": "DSD",
      "ChiSoCu": 95,
      "ChiSoMoi": 0,
      "KhoiLuongMat": 95,
      "LoaiLoi": "Đột Ngột 0"
    },
    {
      "Danhba": "15072427705",
      "MaDMA": "7.1.2",
      "TinhTrang": "DSD",
      "ChiSoCu": 95,
      "ChiSoMoi": 0,
      "KhoiLuongMat": 95,
      "LoaiLoi": "Đột Ngột 0"
    },
    {
      "Danhba": "15011500149",
      "MaDMA": "5.1",
      "TinhTrang": "DSD",
      "ChiSoCu": 91,
      "ChiSoMoi": 0,
      "KhoiLuongMat": 91,
      "LoaiLoi": "Đột Ngột 0"
    },
    {
      "Danhba": "22043308672",
      "MaDMA": "Không rõ",
      "TinhTrang": "DSD",
      "ChiSoCu": 89,
      "ChiSoMoi": 0,
      "KhoiLuongMat": 89,
      "LoaiLoi": "Đột Ngột 0"
    },
    {
      "Danhba": "15042000181",
      "MaDMA": "4.1",
      "TinhTrang": "DSD",
      "ChiSoCu": 85,
      "ChiSoMoi": 0,
      "KhoiLuongMat": 85,
      "LoaiLoi": "Đột Ngột 0"
    },
    {
      "Danhba": "22093381656",
      "MaDMA": "DHT.3",
      "TinhTrang": "DSD",
      "ChiSoCu": 85,
      "ChiSoMoi": 0,
      "KhoiLuongMat": 85,
      "LoaiLoi": "Đột Ngột 0"
    },
    {
      "Danhba": "15031704921",
      "MaDMA": "3.1.1",
      "TinhTrang": "DSD",
      "ChiSoCu": 84,
      "ChiSoMoi": 0,
      "KhoiLuongMat": 84,
      "LoaiLoi": "Đột Ngột 0"
    },
    {
      "Danhba": "15132023213",
      "MaDMA": "13.2",
      "TinhTrang": "DSD",
      "ChiSoCu": 84,
      "ChiSoMoi": 0,
      "KhoiLuongMat": 84,
      "LoaiLoi": "Đột Ngột 0"
    },
    {
      "Danhba": "22103413504",
      "MaDMA": "TTN.2",
      "TinhTrang": "DSD",
      "ChiSoCu": 82,
      "ChiSoMoi": 0,
      "KhoiLuongMat": 82,
      "LoaiLoi": "Đột Ngột 0"
    },
    {
      "Danhba": "15102742869",
      "MaDMA": "17.7.1",
      "TinhTrang": "DSD",
      "ChiSoCu": 80,
      "ChiSoMoi": 0,
      "KhoiLuongMat": 80,
      "LoaiLoi": "Đột Ngột 0"
    },
    {
      "Danhba": "15082520031",
      "MaDMA": "8.2",
      "TinhTrang": "DSD",
      "ChiSoCu": 78,
      "ChiSoMoi": 0,
      "KhoiLuongMat": 78,
      "LoaiLoi": "Đột Ngột 0"
    },
    {
      "Danhba": "22013210894",
      "MaDMA": "TMT.3",
      "TinhTrang": "DSD",
      "ChiSoCu": 78,
      "ChiSoMoi": 0,
      "KhoiLuongMat": 78,
      "LoaiLoi": "Đột Ngột 0"
    },
    {
      "Danhba": "15052160933",
      "MaDMA": "Không rõ",
      "TinhTrang": "DSD",
      "ChiSoCu": 77,
      "ChiSoMoi": 0,
      "KhoiLuongMat": 77,
      "LoaiLoi": "Đột Ngột 0"
    },
    {
      "Danhba": "22053298212",
      "MaDMA": "TX-TL.2",
      "TinhTrang": "DSD",
      "ChiSoCu": 77,
      "ChiSoMoi": 0,
      "KhoiLuongMat": 77,
      "LoaiLoi": "Đột Ngột 0"
    },
    {
      "Danhba": "22013216000",
      "MaDMA": "TMT.1",
      "TinhTrang": "DSD",
      "ChiSoCu": 73,
      "ChiSoMoi": 0,
      "KhoiLuongMat": 73,
      "LoaiLoi": "Đột Ngột 0"
    },
    {
      "Danhba": "15173425694",
      "MaDMA": "17.7.1",
      "TinhTrang": "DSD",
      "ChiSoCu": 72,
      "ChiSoMoi": 0,
      "KhoiLuongMat": 72,
      "LoaiLoi": "Đột Ngột 0"
    },
    {
      "Danhba": "15052167995",
      "MaDMA": "5.7.1",
      "TinhTrang": "DSD",
      "ChiSoCu": 70,
      "ChiSoMoi": 0,
      "KhoiLuongMat": 70,
      "LoaiLoi": "Đột Ngột 0"
    },
    {
      "Danhba": "22063325671",
      "MaDMA": "APD.1",
      "TinhTrang": "DSD",
      "ChiSoCu": 70,
      "ChiSoMoi": 0,
      "KhoiLuongMat": 70,
      "LoaiLoi": "Đột Ngột 0"
    },
    {
      "Danhba": "15173436839",
      "MaDMA": "Không rõ",
      "TinhTrang": "DSD",
      "ChiSoCu": 69,
      "ChiSoMoi": 0,
      "KhoiLuongMat": 69,
      "LoaiLoi": "Đột Ngột 0"
    },
    {
      "Danhba": "22053310677",
      "MaDMA": "TX-TL.2",
      "TinhTrang": "DSD",
      "ChiSoCu": 68,
      "ChiSoMoi": 0,
      "KhoiLuongMat": 68,
      "LoaiLoi": "Đột Ngột 0"
    },
    {
      "Danhba": "22043277972",
      "MaDMA": "TX.1",
      "TinhTrang": "DSD",
      "ChiSoCu": 68,
      "ChiSoMoi": 0,
      "KhoiLuongMat": 68,
      "LoaiLoi": "Đột Ngột 0"
    },
    {
      "Danhba": "15072444300",
      "MaDMA": "6.7.1",
      "TinhTrang": "DSD",
      "ChiSoCu": 67,
      "ChiSoMoi": 0,
      "KhoiLuongMat": 67,
      "LoaiLoi": "Đột Ngột 0"
    },
    {
      "Danhba": "22023245659",
      "MaDMA": "TCH.4_2",
      "TinhTrang": "DSD",
      "ChiSoCu": 67,
      "ChiSoMoi": 0,
      "KhoiLuongMat": 67,
      "LoaiLoi": "Đột Ngột 0"
    },
    {
      "Danhba": "15151890040",
      "MaDMA": "15.1",
      "TinhTrang": "DSD",
      "ChiSoCu": 66,
      "ChiSoMoi": 0,
      "KhoiLuongMat": 66,
      "LoaiLoi": "Đột Ngột 0"
    },
    {
      "Danhba": "22043309605",
      "MaDMA": "Không rõ",
      "TinhTrang": "DSD",
      "ChiSoCu": 66,
      "ChiSoMoi": 0,
      "KhoiLuongMat": 66,
      "LoaiLoi": "Đột Ngột 0"
    },
    {
      "Danhba": "15112846102",
      "MaDMA": "11.1",
      "TinhTrang": "DSD",
      "ChiSoCu": 66,
      "ChiSoMoi": 0,
      "KhoiLuongMat": 66,
      "LoaiLoi": "Đột Ngột 0"
    },
    {
      "Danhba": "22063325720",
      "MaDMA": "APD.1",
      "TinhTrang": "DSD",
      "ChiSoCu": 66,
      "ChiSoMoi": 0,
      "KhoiLuongMat": 66,
      "LoaiLoi": "Đột Ngột 0"
    },
    {
      "Danhba": "15062131357",
      "MaDMA": "6.1.2",
      "TinhTrang": "DSD",
      "ChiSoCu": 65,
      "ChiSoMoi": 0,
      "KhoiLuongMat": 65,
      "LoaiLoi": "Đột Ngột 0"
    },
    {
      "Danhba": "15052164695",
      "MaDMA": "5.2",
      "TinhTrang": "DSD",
      "ChiSoCu": 64,
      "ChiSoMoi": 0,
      "KhoiLuongMat": 64,
      "LoaiLoi": "Đột Ngột 0"
    },
    {
      "Danhba": "22053326799",
      "MaDMA": "TX-TL.2",
      "TinhTrang": "DSD",
      "ChiSoCu": 64,
      "ChiSoMoi": 0,
      "KhoiLuongMat": 64,
      "LoaiLoi": "Đột Ngột 0"
    },
    {
      "Danhba": "15102748493",
      "MaDMA": "10.3",
      "TinhTrang": "DSD",
      "ChiSoCu": 64,
      "ChiSoMoi": 0,
      "KhoiLuongMat": 64,
      "LoaiLoi": "Đột Ngột 0"
    },
    {
      "Danhba": "22053321216",
      "MaDMA": "Không rõ",
      "TinhTrang": "DSD",
      "ChiSoCu": 62,
      "ChiSoMoi": 0,
      "KhoiLuongMat": 62,
      "LoaiLoi": "Đột Ngột 0"
    },
    {
      "Danhba": "15072443857",
      "MaDMA": "6.7.1",
      "TinhTrang": "DSD",
      "ChiSoCu": 62,
      "ChiSoMoi": 0,
      "KhoiLuongMat": 62,
      "LoaiLoi": "Đột Ngột 0"
    },
    {
      "Danhba": "15052121320",
      "MaDMA": "5.1",
      "TinhTrang": "DSD",
      "ChiSoCu": 62,
      "ChiSoMoi": 0,
      "KhoiLuongMat": 62,
      "LoaiLoi": "Đột Ngột 0"
    },
    {
      "Danhba": "15173421243",
      "MaDMA": "7.1.2",
      "TinhTrang": "DSD",
      "ChiSoCu": 62,
      "ChiSoMoi": 0,
      "KhoiLuongMat": 62,
      "LoaiLoi": "Đột Ngột 0"
    },
    {
      "Danhba": "15141947005",
      "MaDMA": "Không rõ",
      "TinhTrang": "DSD",
      "ChiSoCu": 61,
      "ChiSoMoi": 0,
      "KhoiLuongMat": 61,
      "LoaiLoi": "Đột Ngột 0"
    },
    {
      "Danhba": "22103401099",
      "MaDMA": "TTN.1_MR",
      "TinhTrang": "DSD",
      "ChiSoCu": 61,
      "ChiSoMoi": 0,
      "KhoiLuongMat": 61,
      "LoaiLoi": "Đột Ngột 0"
    },
    {
      "Danhba": "15072443018",
      "MaDMA": "17.7.1",
      "TinhTrang": "DSD",
      "ChiSoCu": 60,
      "ChiSoMoi": 0,
      "KhoiLuongMat": 60,
      "LoaiLoi": "Đột Ngột 0"
    },
    {
      "Danhba": "15161923714",
      "MaDMA": "Không rõ",
      "TinhTrang": "DSD",
      "ChiSoCu": 60,
      "ChiSoMoi": 0,
      "KhoiLuongMat": 60,
      "LoaiLoi": "Đột Ngột 0"
    },
    {
      "Danhba": "15041960542",
      "MaDMA": "4.1",
      "TinhTrang": "DSD",
      "ChiSoCu": 58,
      "ChiSoMoi": 0,
      "KhoiLuongMat": 58,
      "LoaiLoi": "Đột Ngột 0"
    },
    {
      "Danhba": "22083362563",
      "MaDMA": "HT-TTH.1",
      "TinhTrang": "DSD",
      "ChiSoCu": 58,
      "ChiSoMoi": 0,
      "KhoiLuongMat": 58,
      "LoaiLoi": "Đột Ngột 0"
    },
    {
      "Danhba": "22053329290",
      "MaDMA": "TL.2",
      "TinhTrang": "DSD",
      "ChiSoCu": 58,
      "ChiSoMoi": 0,
      "KhoiLuongMat": 58,
      "LoaiLoi": "Đột Ngột 0"
    },
    {
      "Danhba": "22023240829",
      "MaDMA": "TCH.4_2",
      "TinhTrang": "DSD",
      "ChiSoCu": 57,
      "ChiSoMoi": 0,
      "KhoiLuongMat": 57,
      "LoaiLoi": "Đột Ngột 0"
    },
    {
      "Danhba": "15141949604",
      "MaDMA": "Không rõ",
      "TinhTrang": "DSD",
      "ChiSoCu": 57,
      "ChiSoMoi": 0,
      "KhoiLuongMat": 57,
      "LoaiLoi": "Đột Ngột 0"
    },
    {
      "Danhba": "15112822738",
      "MaDMA": "Không rõ",
      "TinhTrang": "DSD",
      "ChiSoCu": 57,
      "ChiSoMoi": 0,
      "KhoiLuongMat": 57,
      "LoaiLoi": "Đột Ngột 0"
    },
    {
      "Danhba": "15052166111",
      "MaDMA": "5.7.1",
      "TinhTrang": "DSD",
      "ChiSoCu": 55,
      "ChiSoMoi": 0,
      "KhoiLuongMat": 55,
      "LoaiLoi": "Đột Ngột 0"
    },
    {
      "Danhba": "22083361947",
      "MaDMA": "HT-TTH.1",
      "TinhTrang": "DSD",
      "ChiSoCu": 55,
      "ChiSoMoi": 0,
      "KhoiLuongMat": 55,
      "LoaiLoi": "Đột Ngột 0"
    },
    {
      "Danhba": "22043278585",
      "MaDMA": "Không rõ",
      "TinhTrang": "DSD",
      "ChiSoCu": 54,
      "ChiSoMoi": 0,
      "KhoiLuongMat": 54,
      "LoaiLoi": "Đột Ngột 0"
    },
    {
      "Danhba": "15092647632",
      "MaDMA": "9.1.1",
      "TinhTrang": "DSD",
      "ChiSoCu": 54,
      "ChiSoMoi": 0,
      "KhoiLuongMat": 54,
      "LoaiLoi": "Đột Ngột 0"
    },
    {
      "Danhba": "15062133919",
      "MaDMA": "6.7.1",
      "TinhTrang": "DSD",
      "ChiSoCu": 54,
      "ChiSoMoi": 0,
      "KhoiLuongMat": 54,
      "LoaiLoi": "Đột Ngột 0"
    },
    {
      "Danhba": "22043272691",
      "MaDMA": "Không rõ",
      "TinhTrang": "DSD",
      "ChiSoCu": 54,
      "ChiSoMoi": 0,
      "KhoiLuongMat": 54,
      "LoaiLoi": "Đột Ngột 0"
    },
    {
      "Danhba": "15102743511",
      "MaDMA": "Không rõ",
      "TinhTrang": "DSD",
      "ChiSoCu": 54,
      "ChiSoMoi": 0,
      "KhoiLuongMat": 54,
      "LoaiLoi": "Đột Ngột 0"
    },
    {
      "Danhba": "15062132281",
      "MaDMA": "6.7.1",
      "TinhTrang": "DSD",
      "ChiSoCu": 53,
      "ChiSoMoi": 0,
      "KhoiLuongMat": 53,
      "LoaiLoi": "Đột Ngột 0"
    },
    {
      "Danhba": "22073342097",
      "MaDMA": "TA.2",
      "TinhTrang": "DSD",
      "ChiSoCu": 53,
      "ChiSoMoi": 0,
      "KhoiLuongMat": 53,
      "LoaiLoi": "Đột Ngột 0"
    },
    {
      "Danhba": "15072443372",
      "MaDMA": "17.7.1",
      "TinhTrang": "DSD",
      "ChiSoCu": 53,
      "ChiSoMoi": 0,
      "KhoiLuongMat": 53,
      "LoaiLoi": "Đột Ngột 0"
    }
  ]
};
